### ISSUE TITLE
Panic with clear error message when workflow commands are produced in a side-effect/query function

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-go#1000]
The snippet below looks like valid code but will cause replay issues since the side effect function is not called on replay and thus not generating the StartTimer command.

```go
workflow.SideEffect(ctx, func(ctx workflow.Context) interface{} {
   return workflow.Sleep(ctx, 45 * time.Second)
})
```

**Comment by cretz** [comment]
We should also do this for if commands are produced in a query handler
