### ISSUE TITLE
Not able to execute activity which is on another service.

### ISSUE THREAD

**Issue by VAIBHAV7500** [temporalio/sdk-go#1008]
## Expected Behavior
https://community.temporal.io/t/not-able-to-call-activity-on-another-service/6992

I’m calling activity in my nodejs service from my golang workflow.
The name of the activity is same as what error is suggesting but still not able to pass through.

**Comment by giautm** [comment]
Do you try `nodeActivity` yet?

**Comment by VAIBHAV7500** [comment]
When I tried executing it from the workflow within the same service, the activity ran fine.

**Comment by VAIBHAV7500** [comment]
This issue got resolved by just passing the activity name.
```
err := workflow.ExecuteActivity(ctx, "nodeActivity").Get(ctx, nil)
```
