### ISSUE TITLE
WorkflowReplayer.ReplayWorkflowHistory doesn't return error when there is a de-serialization problem with the input

### ISSUE THREAD

**Issue by ericvg97** [temporalio/sdk-go#1011]
## Expected Behavior
When replaying a workflow for a given history, if the initial input of the workflow can't be de-serialized during the replay, the replayer should return an error

## Actual Behavior
It doesn't return an error. In fact, it doesn't replay the workflow, it just returns without error.
This is problematic because we use the replayer to do a compatibility check on running workflows. Because of this, if there is a de-serialization problem we can't really test compatibility, as the replayer always returns nil.

## Steps to Reproduce the Problem

  1. Define any workflow
  2. Replay the workflow with a history that can't be de-serialized by the workflow (example: use a different format than what the workflow expects)

## Specifications

  - Version: v1.17.0
  - Platform: go

**Comment by cretz** [comment]
Can you confirm this issue still exists on the latest SDK? We have made a few replayer fixes. But yes, it does seem correct that a deserialization failure should be a task failure and therefore a replay failure.

**Comment by ericvg97** [comment]
We have tested with version 20 and it is solved!! Thank you @cretz :)
