### ISSUE TITLE
The memory usage from including the Temporal SDK is very large

### ISSUE THREAD

**Issue by RyanLettieri** [temporalio/sdk-go#1018]
Background: Developer on Dapr ( [GitHub - dapr/dapr: Dapr](https://github.com/dapr/dapr))
We are trying to include Temporal as a workflow engine in our current release (1.10)

Issue: When including the SDK in our project our memory increase spikes up by around 7MB.

SDK Versions:
[go.temporal.io/api](http://go.temporal.io/api) v1.12.0
[go.temporal.io/sdk](http://go.temporal.io/sdk) v1.17.0

Is this the expected memory usage of the inclusion of the SDK? If so, is there a “lite” version of the SDK that won’t consume this amount of memory? If not, is there any way to decrease the memory usage that comes with the inclusion of the SDK?

## Expected Behavior
Including the go SDKs for temporal should be minor in terms of the memory usage.

## Actual Behavior

When including the temporal SDK into the project, the memory usage of the project increases by 7MB.

## Steps to Reproduce the Problem

  1. Include the temporal api and sdk into the project.
  1. Run the project.
  1.

## Specifications

  - Version: (api v1.12.0.) (SDK 1.17.0)
  - Platform:

**Comment by cretz** [comment]
Can you clarify memory usage? Are you saying the binary size are talking about runtime memory use? If runtime memory use, is it only after you start a Temporal worker? 7MB is usually not a heavy burden for a library like Temporal, but profiling can help determine where the memory is used.

**Comment by yaron2** [comment]
Hi, Dapr maintainer here. We're talking about runtime memory use.

**Comment by yaron2** [comment]
What we're seeing is increased memory after this method is executed: https://github.com/dapr/components-contrib/blob/master/workflows/temporal/temporal.go#LL49C2-L49C2.

**Comment by cretz** [comment]
7MB sounds within reasonable range for a full gRPC client. It may be worth profiling and seeing if there's anything obvious. We can do the same if too problematic.

**Comment by yaron2** [comment]
Update: the memory increase occurs just by importing the package.

**Comment by cretz** [comment]
That would make sense. Protobuf creates a big map of all registered types globally in `init()` clauses and we have a decent amount of protobufs. Though there may be other places too that a memory profile could uncover.

**Comment by RyanLettieri** [comment]
In lieu of the size of the import, is it possible to simply use the HTTP endpoint as a hackish workaround for the time being? If so, could you point me in the right direction to get started on that implementation?

**Comment by cretz** [comment]
I am afraid we do not (yet) have a publicly facing HTTP interface for the low-level Temporal API. The Temporal API is a bit low-level and therefore can be difficult to navigate without the higher level client. The whole reason we lean on Protobuf is to have that type safety at an acceptable cost of a few megs.

You can use the CLI as a subprocess, but that CLI is gonna use more than 7MB too.

**Comment by yaron2** [comment]
> I am afraid we do not (yet) have a publicly facing HTTP interface for the low-level Temporal API. The Temporal API is a bit low-level and therefore can be difficult to navigate without the higher level client. The whole reason we lean on Protobuf is to have that type safety at an acceptable cost of a few megs.
> 
> You can use the CLI as a subprocess, but that CLI is gonna use more than 7MB too.

Thanks for the prompt response here, we appreciate this. We will remove Temporal support for 1.10 and look to include it again if anything changes in time for our 1.11 release.
