### ISSUE TITLE
Expose session state to users

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#1021]
**Is your feature request related to a problem? Please describe.**

People need a way to know whether session has failed, specifically if an activity has failed due to being cancelled by session failure.

**Describe the solution you'd like**

Can expose the already-existing session state on session info. We need to make sure that it is set to failed if an activity is failed because of session failure.

**Comment by Quinn-With-Two-Ns** [comment]
How is this different then the error we already have in the SDK `ErrSessionFailed`?

>We need to make sure that it is set to failed if an activity is failed because of session failure.

How do you propose we tell an activity failed because it was the session that failed?

**Comment by cretz** [comment]
> How is this different then the error we already have in the SDK ErrSessionFailed?

I believe based on docs that an already-in-progress activity on a session just gets cancelled, you can't tell from the error returned by the activity that it was due to session failure. (I could be wrong about this, did not test)

> How do you propose we tell an activity failed because it was the session that failed?

While there are technically some race conditions, if the activity failed due to cancellation the user can check if the session is failed and _may_ make reasonable a judgement that that may be the reason. It's about the best we can offer I think without changing error approaches.

**Comment by Quinn-With-Two-Ns** [comment]
>While there are technically some race conditions, if the activity failed due to cancellation the user can check if the session is failed and may make reasonable a judgement that that may be the reason. It's about the best we can offer I think without changing error approaches.

I'd need to test but I think depending on worker and activity settings it could be pretty easy to have false positives and false negatives. I agree it is the best we can do so I am fine with this approach.

In your original comment you suggested we should mark the session failed if an activity is failed because of session failure. That I don't like because I don't think it is possible to reliably do and is a breaking change to the session API as we explicitly call out we don't fail the session on activity failure in the documentation.

**Comment by cretz** [comment]
> In your original comment you suggested we should mark the session failed if an activity is failed because of session failure

I am not suggesting changing anything with how sessions are marked. I am just suggesting we expose session state/status. By "we need to make sure" I just mean a test to confirm that the session status is as expected when an in-flight activity cancel/failure is caused by session failure. Sorry for the wording confusion.

**Comment by armoona** [comment]
From the user's perspective, it would be simplest if ExecuteActivity().Get() always returned ErrSessionFailed on session failure, whether it happened while an activity is in progress or otherwise.

Thinking out loud, I think the following hack would work now to reliably trigger session restarts in all cases. It uses a dummy activity that does nothing.

```
	err := workflow.ExecuteActivity(ctx, "RealActivity").Get(ctx, nil)
	var canceledErr *temporal.CanceledError
	if err == workflow.ErrSessionFailed {
		// restart session
	} else if errors.As(err, &canceledErr) {
		err = workflow.ExecuteActivity(ctx, "DummyActivity").Get(ctx, nil)
		if err == workflow.ErrSessionFailed {
			// restart session
		}
	}

```

**Comment by Quinn-With-Two-Ns** [comment]
>From the user's perspective, it would be simplest if ExecuteActivity().Get() always returned ErrSessionFailed on session failure, whether it happened while an activity is in progress or otherwise.

I agree that would be the simplest, I just don't believe it is possible for the SDK to be confident the activity failed 100% of the time because the session did/did not fail. The best we can do is expose the session state and Users can make that judgement on why the activity failed.

**Comment by cretz** [comment]
Also, cancellation is a request not a requirement. Activities can respond to cancellations in different ways. There are many reasons an activity can be cancelled (session close, workflow close, etc) and we don't expose cancellation reasons in any cases. And yes, technically an activity could be cancelled for another reason and you can't tell it was session cancel that was the real reason. All you can do is check whether the session context is closed.

**Comment by Quinn-With-Two-Ns** [comment]
This should be exposed in the go sdk v1.21.0 under `SessionInfo.SessionState `

As noted in the PR
```
Note: Sessions have an inherently stale view of the worker they are running on. Session
	state may be stale up the the SessionOptions.HeartbeatTimeout. SessionOptions.HeartbeatTimeout
	should be less than half the activity timeout for the state to be accurate when checking after activity failure.
```
