### ISSUE TITLE
Channel.Receive consumes message before goroutine is woken up

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-go#1048]
## Expected Behavior
`Channel.ReceiveAsync` should be able to receive all pending messages in a Channel.

## Actual Behavior
1. A goroutine blocked on `Channel.Receive` and then a message is sent to the channel. 
2. `Channel.ReceiveAsync` from a different goroutine will not receive the message.

This behavior is problematic as we say that draining all signal messages through `Channel.ReceiveAsync` before completing a workflow is enough to ensure that there is no signal loss.

## Steps to Reproduce the Problem

This problem manifests itself when the goroutine that is blocked on `Channel.Receive` doesn't get a chance to wake up. This happens when a workflow task fails with UNHANDLED_COMMAND due to a new signal received during the workflow task that tried to complete the workflow.

## Notes

I believe that fix to this issue might be backward incompatible as it potentially can change the order of execution of goroutines. The probability of this affecting any workflow is very low, but it should be considered.

**Comment by mfateev** [comment]
I'm able to reproduce the problem when using a Selector to receive the signal. So the Selector has the same issue.

**Comment by mfateev** [comment]
I see two solutions:
1. AsyncReceive always takes precedence
2. A main workflow goroutine has the lowest precedence. This is the path all other SDKs took.

**Comment by Quinn-With-Two-Ns** [comment]
We are adding the ability for internal SDK patches https://github.com/temporalio/api/pull/259 this could be a candidate.

Can you post an example workflow that causes this? I am not able to replicate the signal getting dropped.

**Comment by cretz** [comment]
Not understanding this issue exactly but haven't done a deep read on the reproduction (I may have to make a more simplified reproduction). If a user has `Receive` and `ReceiveAsync` I would think there are no guarantees which will win (even if the winner is deterministic). If a user has a non-primary coroutine that they need to ensure finishes before primary coroutine completion (e.g. one with a `Receive`), they are required to make that assurance in code.

**Comment by mfateev** [comment]
After thinking about this I kind of agree that requiring the clean goroutine exit is the way to go. Closing the issue.
