### ISSUE TITLE
All workflow gorounies should never run after workflow method returns.

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-go#1049]
## Expected Behavior
Workflow goroutines are never scheduled to run after the main workflow function returns.

## Actual Behavior

Other goroutines are given chance to execute after the main workflow function returns.

## Steps to Reproduce the Problem

See https://github.com/temporalio/samples-go/pull/255

**Comment by Quinn-With-Two-Ns** [comment]
I wonder if we should consider it an error to have unfinished workflow goroutines once the main workflow function returns?

**Comment by cretz** [comment]
> I wonder if we should consider it an error to have unfinished workflow goroutines once the main workflow function returns?

Nah, shouldn't even warn IMO. An unawaited promise/task in other languages make sense, but quite often Goroutines are fire-and-forget and/or just run forever waiting on a signal that will never come.

**Comment by cretz** [comment]
> Writing fire and forget goroutines is not safe, you have no guarantee it will run

That may be ok with me as a user

> Also that sounds like a memory leak?

Nah, IIRC we `runtime.Goexit` all goroutines belonging to a workflow.

> Yeah this does seem backwards incompatible. Currently we say our workflow goroutines have similar semantics to normal goroutines. normal goroutines do not stop executing if the parent stops.

If you're looking for an analogy, it's not like a "parent" and more like a "process" IMO. I think workflow completion is like `os.Exit()`. But yes, if today we run coroutines after workflow complete we probably can't change without that SDK version marker thing.

I think other SDKs may have this same "problem" (if we decide this is wrong behavior). In Python I don't think I immediately stop all coroutines on the primary one completing. I just collect commands until all yielded/complete and send them back. I wonder how core reacts to a command coming after workflow completion. Will bring up at standup.

**Comment by Quinn-With-Two-Ns** [comment]
>Nah, IIRC we runtime.Goexit all goroutines belonging to a workflow.

I'll have to look at the code, but if we do that means `defer` will still run.

>If you're looking for an analogy, it's not like a "parent" and more like a "process" IMO. I think workflow completion is like os.Exit(). But yes, if today we run coroutines after workflow complete we probably can't change without that SDK version marker thing.

hhm yeah if those are the semantics then nothing should be run after the workflow exit including `defer` statements.

**Comment by Quinn-With-Two-Ns** [comment]
Going to mark this as closed as with the addition of workflow update the current behaviour is desirable

https://github.com/temporalio/features/issues/481
