### ISSUE TITLE
Fix getVersion search attribute bloat

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/sdk-go#1052]
Java and Go accumulate values in the `TemporalChangeVersion` search attribute every time a `getVersion` call is made.

The search attribute value size is capped, which causes user workflows to get stuck in a WFT failure loop without an easy way of out of this situation. If we hit the size limit we should stop adding new versions to `TemporalChangeVersion` and log a clear error/warning when situation reached.

**Comment by cretz** [comment]
> If we hit the size limit we should stop adding new versions to TemporalChangeVersion

Or remove the oldest from the list. But either way is fine, we just need to log a clear error/warning when situation reached.

**Comment by Quinn-With-Two-Ns** [comment]
Yep good point, I noted the requirement to log as well
