### ISSUE TITLE
workflowcheck is failing non-deterministic checks when code is wrapped with SideEffect

### ISSUE THREAD

**Issue by mindaugasrukas** [temporalio/sdk-go#1063]
## Expected Behavior
`workflowcheck` ignores `SideEffect` block.

## Actual Behavior
`workflowcheck` is failing `non-deterministic` check.

## Steps to Reproduce the Problem

  1. In a Workflow, add any non-deterministic code and wrap it with the SideEffect.
  1. run `workflowcheck -show-pos ./...`

## Specifications

  - Version: `go install go.temporal.io/sdk/contrib/tools/workflowcheck@latest`
  - Platform:
```
% uname -v
Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
```

**Comment by edmondop** [comment]
Could have been fixed?  Using the latest I couldn't trigger the problem

```
package my_stuff

import (
	"go.temporal.io/sdk/workflow"
	"math/rand"
)

func MyWorkflow(context workflow.Context) {
	encodedRandom := workflow.SideEffect(context, func(ctx workflow.Context) interface{} {
		return rand.Intn(100)
	})
	var random int
	encodedRandom.Get(&random)
}

```

**Comment by Quinn-With-Two-Ns** [comment]
Closing as this is resolved by https://github.com/temporalio/sdk-go/pull/1230
