### ISSUE TITLE
Bug with version go.temporal.io/api v1.19

### ISSUE THREAD

**Issue by Tarang** [temporalio/sdk-go#1084]
## Expected Behavior
A replay runs

## Actual Behavior
A replay immediately exits without running code

## Steps to Reproduce the Problem

  1. Create a workflow
  1. Download replay
  1. Replay with replayer.ReplayWorkflowHistoryFromJSONFile

Used to work with version go.temporal.io/api v1.18.1.

## Specifications

  - Version: Ventura 13.1
  - Platform: Mac

**Comment by Quinn-With-Two-Ns** [comment]
`go.temporal.io/api` is not related to workflow replay. Can you please clarify the steps to reproduce the problem you saw and confirm you are running on the latest sdk-go version `1.22.x`?

**Comment by Tarang** [comment]
Hi

I am running `go.temporal.io/sdk v1.21.1`. If I alter my go mod file to use `go.temporal.io/api v1.19` it wont work, if I use `go.temporal.io/api v1.18.1` it works. So it is very clear it's related to that.

**Comment by Quinn-With-Two-Ns** [comment]
Can you please clarify the steps to reproduce the problem you saw? for example a short reproduction and history that fails to replay in the latest SDK release

**Comment by Tarang** [comment]
What is the best way to create a reproduction since it requires a running temporal and the history file

**Comment by Quinn-With-Two-Ns** [comment]
could you please test replay again with the latest version of the SDK  `go get go.temporal.io/sdk@master` we recently fixed a bug that could be related.

**Comment by hlthung** [comment]
Came across this thread, I'd like to apply the fix, but when I do `go get go.temporal.io/sdk@master` or use [v1.22.1](https://github.com/temporalio/sdk-go/releases/tag/v1.22.1), seems like I'm facing a bunch of issues with server/api/persistence:
```
# go.temporal.io/server/api/persistence/v1
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:307:22: undefined: taskqueue.VersionIdNode
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:311:26: undefined: taskqueue.VersionIdNode
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:346:51: undefined: taskqueue.VersionIdNode
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:353:55: undefined: taskqueue.VersionIdNode
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:722:28: invalid operation: this.CurrentDefault != nil (operator != not defined on untyped nil)
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:989:25: invalid operation: m.CurrentDefault != nil (operator != not defined on untyped nil)
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:1149:25: invalid operation: m.CurrentDefault != nil (operator != not defined on untyped nil)
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:1987:27: invalid operation: m.CurrentDefault == nil (operator == not defined on untyped nil)
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:1988:29: undefined: taskqueue.VersionIdNode
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:2023:57: undefined: taskqueue.VersionIdNode
../../../../go/pkg/mod/go.temporal.io/server@v1.20.2/api/persistence/v1/tasks.pb.go:2023:57: too many errors
```
Unable to find a version I can use for go.temporal.io/server as no matter which version I will get the errors. 
v1.19.X, v1.20.X, 1.21.X are fine I believe. May I know how to resolve this? Thank you!

**Comment by Quinn-With-Two-Ns** [comment]
Likely related to https://github.com/temporalio/sdk-go/issues/1091
