### ISSUE TITLE
workflow.UpsertSearchAttributes sdk function doesn't return error but fails the workflow task.

### ISSUE THREAD

**Issue by ObedImmanuel** [temporalio/sdk-go#1103]
**Is your feature request related to a problem? Please describe.**
[workflow.UpsertSearchAttributes](https://legacy-documentation-sdks.temporal.io/go/search-apis?_ga=2.126147917.1174630429.1683809094-671880620.1679381320#upsert-search-attributes-during-workflow-execution) sdk function returns a nil error but fails the workflow.
We would need to just log the error and not break the workflow's execution.
Looking at the implementation, the function generates a command and upserts search attribute in background. And fails the workflow on `BadSearchAttribute` or other failures.

**Describe the solution you'd like**
We would want the sdk to not fail the workflow on failure during upsertion. some configuration or env variable to control this behaviour would help.

**Describe alternatives you've considered**

**Additional context**

**Comment by Quinn-With-Two-Ns** [comment]
Are you seeing the workflow task fail or the workflow fail?

**Comment by ObedImmanuel** [comment]
Workflow task fail.
<img width="1603" alt="Screenshot 2023-05-12 at 1 55 28 PM" src="https://github.com/temporalio/sdk-go/assets/49405785/23e27a0b-3398-4f6d-bfd5-ae8781335d12">

**Comment by Quinn-With-Two-Ns** [comment]
I believe this is the Temporal server failing the workflow task because the search attribute is invalid. There is nothing the SDK can do if the server fails the workflow task.

**Comment by ObedImmanuel** [comment]
Make sense, Thanks.
