### ISSUE TITLE
Proposal for Accessible `taskLimiter` for Worker Rate Modification

### ISSUE THREAD

**Issue by zboralski** [temporalio/sdk-go#1130]
**Is your feature request related to a problem? Please describe.**
In the existing design, the `taskLimiter` of an activity, responsible for the worker's rate limit, remains inaccessible. This restricts our capability to adjust the worker's rate dynamically in line with shifting workloads or requirements.

**Describe the solution you'd like**
I suggest making the `taskLimiter` accessible, thereby enabling developers to modify the worker's rate directly. Upon examining the SDK and `rate.Limiter` code, it seems that using this approach is safe. The `rate.Limiter` uses a mutex to ensure thread safety when adjusting limits.

**Describe alternatives you've considered**
Maintaining rate limits using the external methods or restarting workers is an option. However, these methods lacks flexibility and might not be the best fit for managing varying workloads.

**Additional context**
By granting access to `taskLimiter`, we offer granular control over the worker's rate limit. This is notably beneficial for applications with fluctuating workloads. I recommend trying the function highlighted below and examining `rate.Limiter`'s implementation to verify the safety and efficiency of this proposed change. The internals of `rate.Limiter` are well-guarded by a mutex, ensuring secure adjustments to the rate limit.

Included is a function, GetLimiter(), which can retrieve the taskLimiter from a worker.Worker instance. This function uses reflection to access the internal taskLimiter field of the worker.Worker instance. It's designed to safely navigate various scenarios, including nil workers, non-struct workers, and non-addressable fields. Please note that this function serves as a workaround to demonstrate the importance and potential usage of making taskLimiter accessible, and isn't a recommended long-term solution.

```go
package main

import (
	"fmt"
	"reflect"
	"unsafe"

	"go.temporal.io/sdk/worker"
	"golang.org/x/time/rate"
)

func GetLimiter(w worker.Worker) (*rate.Limiter, error) {
	if w == nil {
		return nil, fmt.Errorf("Worker is nil")
	}

	// Extract the value from the interface
	value := reflect.ValueOf(w)
	if value.Kind() == reflect.Interface && !value.IsNil() {
		value = value.Elem()
	}

	// If the value is a pointer, dereference it
	if value.Kind() == reflect.Ptr && !value.IsNil() {
		value = value.Elem()
	}

	// If the value is now a struct, attempt to get the activityWorker field
	if value.Kind() != reflect.Struct {
		return nil, fmt.Errorf("Expected a struct, but got: %s", value.Kind())
	}

	activityWorkerField := value.FieldByName("activityWorker")
	if !(activityWorkerField.IsValid() && activityWorkerField.CanAddr()) {
		return nil, fmt.Errorf("Field 'activityWorker' is not valid or can't be addressed")
	}

	// Create a new Value that treats activityWorker as if it were exported
	activityWorkerField = reflect.NewAt(activityWorkerField.Type(), unsafe.Pointer(activityWorkerField.UnsafeAddr())).Elem()

	// Check if activityWorker is valid and then access baseWorker
	if activityWorkerField.Kind() == reflect.Ptr && !activityWorkerField.IsNil() {
		activityWorkerField = activityWorkerField.Elem()
	}

	if activityWorkerField.Kind() != reflect.Struct {
		return nil, fmt.Errorf("Expected a struct, but got: %s", activityWorkerField.Kind())
	}

	baseWorkerField := activityWorkerField.FieldByName("worker")
	if !(baseWorkerField.IsValid() && baseWorkerField.CanAddr()) {
		return nil, fmt.Errorf("Field 'worker' in 'activityWorker' is not valid or can't be addressed")
	}

	// Create a new Value that treats worker (baseWorker) as if it were exported
	baseWorkerField = reflect.NewAt(baseWorkerField.Type(), unsafe.Pointer(baseWorkerField.UnsafeAddr())).Elem()

	// Check if baseWorker is valid and then access taskLimiter
	if baseWorkerField.Kind() == reflect.Ptr && !baseWorkerField.IsNil() {
		baseWorkerField = baseWorkerField.Elem()
	}

	if baseWorkerField.Kind() != reflect.Struct {
		return nil, fmt.Errorf("Expected a struct, but got: %s", baseWorkerField.Kind())
	}

	taskLimiterField := baseWorkerField.FieldByName("taskLimiter")
	if !(taskLimiterField.IsValid() && taskLimiterField.CanAddr()) {
		return nil, fmt.Errorf("Field 'taskLimiter' in 'baseWorker' is not valid or can't be addressed")
	}

	// Finally return the taskLimiter as *rate.Limiter
	return (*rate.Limiter)(unsafe.Pointer(taskLimiterField.Pointer())), nil
}
```

**Comment by cretz** [comment]
This limiter doesn't do what you may think. This doesn't dynamically limit available slots, it just affects time processing after slots are used. The poll has already completed and the timeouts will have already started.

What you need is #569 which is admittedly useful, yes, but challenging to implement.

**Comment by Quinn-With-Two-Ns** [comment]
Closing, but feel free to  reopen if the above explanation wasn't enough
