### ISSUE TITLE
Support OpenTelemetry Metrics

### ISSUE THREAD

**Issue by albertteoh** [temporalio/sdk-go#1137]
**Is your feature request related to a problem? Please describe.**

We have adopted OpenTelemetry Go SDK as our primary instrumentation library; however, with Temporal requiring Tally, it means we'll have a combination of different metrics libraries which are both pull and push based, which complicates our deployment configuration.

**Describe the solution you'd like**
For Temporal to support OpenTelemetry for its metrics instrumentation.

**Describe alternatives you've considered**

- Implement the [`metrics.Handler`](https://github.com/temporalio/sdk-go/blob/master/internal/common/metrics/handler.go#L34) interface to wrap OpenTelemetry. However, one of the interface methods returns the `Handler` itself, which is in an `internal` package. So, this alternative doesn't seem to be feasible (but correct me if I'm wrong). Moreover, it's not a particularly nice solution.

**Additional context**
I have read that adopting OpenTelemetry was delayed because of its instability ([reference](https://community.temporal.io/t/opentracing-and-opentelemetry-for-temporal/3986/3)). 

It now seems that the API and protocol are now stable ([link](https://opentelemetry.io/docs/specs/status/#metrics)), and many components of the SDK are also stable ([link](https://opentelemetry.io/docs/specs/otel/metrics/sdk/#meterprovider)).

**Comment by cretz** [comment]
You linked to stability of the spec not stability of the Go SDK. Right now https://opentelemetry.io/docs/instrumentation/go/ shows it as beta.

> However, one of the interface methods returns the Handler itself, which is in an internal package. So, this alternative doesn't seem to be feasible (but correct me if I'm wrong). 

The handler and all types it may need are aliased and exported from the `client` package.

**Comment by albertteoh** [comment]
> You linked to stability of the spec not stability of the Go SDK. Right now https://opentelemetry.io/docs/instrumentation/go/ shows metrics as beta.

Ah yes, you're right! 😄 It's fair that it's not yet supported in Temporal.

> The handler and all types it may need are aliased and exported from the client package.

Gotcha, I might give this another shot, thanks for the help!

**Comment by albertteoh** [comment]
Just thought to mention that metrics are now considered stable in OpenTelemetry.

![Screenshot 2024-01-16 at 1 28 27 pm](https://github.com/temporalio/sdk-go/assets/26584478/b95aa89c-9d8e-428e-9d04-73543169d37e)

**Comment by Quinn-With-Two-Ns** [comment]
@albertteoh Otel metrics are now implemented,  because they  are stable https://github.com/temporalio/sdk-go/blob/master/contrib/opentelemetry/handler.go

Expect them to be in the next release soon

**Comment by Quinn-With-Two-Ns** [comment]
@albertteoh This has been release for a couple weeks now https://github.com/temporalio/sdk-go/releases/tag/contrib%2Fopentelemetry%2Fv0.4.0

Note: the open telemetry contrib package release is not tied with the SDK release

**Comment by albertteoh** [comment]
Ah, thanks so much @Quinn-With-Two-Ns! I didn't realise there was a separate release for the otel contrib package.

**Comment by albertteoh** [comment]
Hi @Quinn-With-Two-Ns, I tried upgrading the otel contrib package and it resulted in the following build error:
```
# go.temporal.io/sdk/internal/protocol
../../../../pkg/mod/go.temporal.io/sdk@v1.25.1/internal/protocol/util.go:39:40: cannot use msg.Body (variable of type *anypb.Any) as *types.Any value in argument to types.AnyMessageName
# go.temporal.io/sdk/internal/common/metrics
../../../../pkg/mod/go.temporal.io/sdk@v1.25.1/internal/common/metrics/grpc.go:120:44: cannot use s (variable of type *"github.com/gogo/status".Status) as *"google.golang.org/grpc/internal/status".Status value in argument to serviceerror.FromStatus
```

I think the problem is because, as part of the otel package upgrade, it also upgraded the `api` package from 1.24.0 -> 1.26.1. 
1.26.1 has a breaking change to switch from the deprecated gogo library to google/protobuf.

Since we're still on the latest SDK release v1.25.1, it still uses `github.com/gogo/protobuf/types.AnyMessageName` which now has an incompatible parameter `google.golang.org/protobuf/types/known/anypb.Any`.

Do you know how we can resolve this?
