### ISSUE TITLE
Auto instrument Activities if enabled

### ISSUE THREAD

**Issue by albertteoh** [temporalio/sdk-go#1138]
**Is your feature request related to a problem? Please describe.**
Generically instrument Activities. That is, avoid the need to manually instrument each activity as illustrated in [this example](https://github.com/temporalio/samples-go/blob/main/metrics/workflow.go#L32), because we have a lot of Activities defined and would be tedious to instrument.

**Describe the solution you'd like**
Have Activities automatically instrumented, if enabled via configuration/options. Propose to wrap instrumentation before and after [`ExecuteActivity`](https://github.com/temporalio/sdk-go/blob/master/internal/workflow.go#L555), following a similar approach to [the existing Go metrics instrumentation example](https://github.com/temporalio/samples-go/blob/main/metrics/workflow.go#L32)

**Describe alternatives you've considered**
- Manually instrument each Activity: works but tedious
- [Cluster metrics setup](https://docs.temporal.io/kb/prometheus-grafana-setup#cluster-metrics-setup): does not contain Activity-specific metrics.

**Additional context**
Happy to put together a PR as an upstream contribution, if the community is happy with this proposal.

**Comment by cretz** [comment]
What metric are you looking for? We already have [`temporal_activity_execution_latency`](https://docs.temporal.io/references/sdk-metrics#activity_execution_latency). That sample in your link is just for demonstrating how to make custom metric with your own name, but a metric for activity execution already exists.

**Comment by albertteoh** [comment]
> What metric are you looking for?

At the very least, success/failure counts from activity executions grouped by activity name; latency is a bonus.

> We already have [temporal_activity_execution_latency](https://docs.temporal.io/references/sdk-metrics#activity_execution_latency).

Is this metric surfaced after enabling cluster level metrics as described [here](https://docs.temporal.io/kb/prometheus-grafana-setup#cluster-metrics-setup)?

If so, I gave that a go, and eyeballed some metrics but couldn't find labels that contained the Activity name. But if that particular metric does have it, then it meets our requirements.

**Comment by albertteoh** [comment]
> This is a worker-side metric not a server-side one. Enable metrics as shown in the previously-linked sample.

Oh yes, I should have checked the title of the page. 😅 

> (also feel free to join us on forums and #go-sdk on Slack)

Thank you, will do! And also thank you for the amazingly fast and helpful responses. 👍🏼
