### ISSUE TITLE
Add slog logger implementation

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#1158]
**Describe the solution you'd like**

Now that https://pkg.go.dev/log/slog is a thing, we would like to add something like:

```go
type slogLogger struct{ underlying *slog.Logger }

var _ log.Logger = (*slogLogger)(nil)
var _ log.WithLogger = (*slogLogger)(nil)

func NewStructuredLogger(underlying *slog.Logger) log.Logger   { return &slogLogger{underlying} }
func (s *slogLogger) Debug(msg string, keyvals ...interface{}) { s.underlying.Debug(msg, keyvals...) }
func (s *slogLogger) Info(msg string, keyvals ...interface{})  { s.underlying.Info(msg, keyvals...) }
func (s *slogLogger) Warn(msg string, keyvals ...interface{})  { s.underlying.Warn(msg, keyvals...) }
func (s *slogLogger) Error(msg string, keyvals ...interface{}) { s.underlying.Error(msg, keyvals...) }
func (s *slogLogger) With(keyvals ...interface{}) log.Logger {
	return &slogLogger{s.underlying.With(keyvals...)}
}
```

But, we can't do it yet because it's not in the oldest Go version we support. So once it is we can add that. In the meantime, a sample can be added or people can just refer to this issue for that simple implementation.

**Comment by cretz** [comment]
Actually, what's interesting is that if you ignore `log.WithLogger`, you can just provide an `*slog.Logger` directly since our interface conforms. How lucky.

**Comment by Quinn-With-Two-Ns** [comment]
>But, we can't do it yet because it's not in the oldest Go version we support

Why do we need to wait? Can't we include the logger conditionally on the go version with build tags?

**Comment by cretz** [comment]
Ah, yes, build tags work. Can impl whenever. May at least want to wait until officially released (because we need to update CI to that Go version to confirm this code works).

**Comment by Quinn-With-Two-Ns** [comment]
Since `slog` already satisfies are logger interface, what is the value of wrapping?

**Comment by cretz** [comment]
None, can document instead. Technically explicitly implementing `With` could help in some performance cases, but :shrug:.

**Comment by Quinn-With-Two-Ns** [comment]
It may still be worth adding a wrapper to support https://github.com/temporalio/sdk-go/issues/960

**Comment by Nikola-Milovic** [comment]
Is this still valid?

```
cannot convert slog.Default() (value of type *slog.Logger) to type "go.temporal.io/sdk/log".WithLogger: 
*slog.Logger does not implement "go.temporal.io/sdk/log".WithLogger (wrong type for method With)		
   have With(...any) *slog.Logger		
   want With(...interface{}) "go.temporal.io/sdk/log".Logger
```

**Comment by Quinn-With-Two-Ns** [comment]
@Nikola-Milovic not sure what you mean by "valid"?  To use `slog` with the Go SDK you can use our wrapper https://pkg.go.dev/go.temporal.io/sdk/log#NewStructuredLogger to convert an `slog` logger to our logger interfaces.

**Comment by emre-aydin** [comment]
@Quinn-With-Two-Ns is this safe to use in an activity? What we normally do is this:

```
log.With(activity.GetLogger(ctx), ..._
```

Is it OK to use it instead of `activity.GetLogger`?
