### ISSUE TITLE
Selector should match closed channel once

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-go#116]
Currently the following code:

```
selector.AddReceive(cancelCtx.Done(), func(c workflow.Channel, more bool) {
   c.Receive(ctx, nil)
   workflow.GetLogger(ctx).Info("1")
})

for {
  selector.Select()
}
```

is going to loop forever without blocking if `context Done()` channel is closed. We should match it only once the same way it is done for a `Future`.

**Comment by samarabbas** [comment]
We will tackle this during stabilization.
