### ISSUE TITLE
Allow ignoring invalid SpanContext in OpenTelemetry TracingInterceptor

### ISSUE THREAD

**Issue by cdavis-joy** [temporalio/sdk-go#1174]
**Is your feature request related to a problem? Please describe.**
We recently moved from OpenTracing to OpenTelemetry. Upon deploying, we found a long running workflow failed because it was trying to start a span from an OpenTracing parent span, so an error was returned here: https://github.com/temporalio/sdk-go/blob/master/contrib/opentelemetry/tracing_interceptor.go#L137

**Describe the solution you'd like**
Failures to trace should have the option to do so silently. Adding an option to the TracingInterceptor to ignore the invalid SpanContext would allow us to keep this long running workflow alive when the new version of the worker deploys. It's acceptable for spans to not connect to their parents for a short time; it is not acceptable for a critical workflow to fail because of a failure to trace. 

**Describe alternatives you've considered**
The DataDog interceptor seems to handle this gracefully already. OpenTelemetry does not return any error when getting a SpanContext. 

**Additional context**
I've added a commit [on my fork](https://github.com/cdavis-joy/sdk-go/commit/9fc81c3847d4b19d126e9dfc040b5859f3970773) that attempts to address this. I feel like this is likely a common thing that people might run into; running workflows that straddle two tracing implementations.

**Comment by cdavis-joy** [comment]
To zoom out a bit, the SDK is enforcing tracing to operate without error, and if it does not, workflows/activities cannot run. (see https://github.com/temporalio/sdk-go/blob/master/interceptor/tracing_interceptor.go#L375)

Maybe I'm totally off base here in thinking that workflows/activities should not function if tracing is not functioning, but I'm happy to hear any other thoughts.

**Comment by Quinn-With-Two-Ns** [comment]
Yeah I think adding an option to ignore errors this case seems very reasonable
