### ISSUE TITLE
v1.24.0 requires Go v1.19+

### ISSUE THREAD

**Issue by AriehSchneier** [temporalio/sdk-go#1196]
This PR https://github.com/temporalio/sdk-go/pull/1164 added the usage of `atomic.Bool` which was only added in [Go v1.19](https://pkg.go.dev/sync/atomic#Bool).

You should update your go.mod to specify the min requirement, or switch it to use `uberatomic.Bool` (like the rest of the code) instead.

**Comment by Quinn-With-Two-Ns** [comment]
When we update CI for Go 1.21 we will update the Go mod file
