### ISSUE TITLE
RespondActivityTaskFailedRequest add result field

### ISSUE THREAD

**Issue by ppanphper** [temporalio/sdk-go#1201]
**Is your feature request related to a problem? Please describe.**

It is hoped that when the execution activity/workflow fails, the result can also be obtained, so that some special errors can obtain some information from the result

**Describe the solution you'd like**

RespondActivityTaskFailedRequest.Result = RespondActivityTaskCompletedRequest.Result

```
var result ActivityRes
err := workflow.ExecuteActivity(ctx, Activity, name).Get(ctx, &result)
// when err != nil, result has value
if err != nil {
logger.Error("Activity failed.", "Error", err, "Result", result)

// use result do some other things

return result, err
}
```

```
func (d *decodeFutureImpl) Get(ctx Context, valuePtr interface{}) error {
....
	//if d.futureImpl.err != nil || d.futureImpl.value == nil || valuePtr == nil {
	if d.futureImpl.value == nil || valuePtr == nil {
		return d.futureImpl.err
	}
...
}
func (f *futureImpl) Get(ctx Context, valuePtr interface{}) error {
...
	//if f.err != nil || f.value == nil || valuePtr == nil {
        if f.value == nil || valuePtr == nil {
		return f.err
	}
...
}
```

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/temporalio/sdk-go/assets/6057923/23a2c0bd-4d75-4520-973d-b66d97de71ff)

![image](https://github.com/temporalio/sdk-go/assets/6057923/19de29b2-9f26-46fb-8939-1c3ad7b286d1)

![image](https://github.com/temporalio/sdk-go/assets/6057923/ce80d141-e7c7-4f6a-9997-949556c6ff87)

![image](https://github.com/temporalio/sdk-go/assets/6057923/295d3eae-8922-42eb-a0dc-57fbd96cf675)

**Comment by ppanphper** [comment]
I found the details of NewApplicationError which solved my needs。But it's a bit complicated to use

**Comment by Quinn-With-Two-Ns** [comment]
In Temporal a workflow or an activity can either return a result or an error. This is for multiple reasons including but not limited to: 
* Temporal supports other languages then Go, including cross calling between them, and they have no way to return a result and failure
* Historically it has been the behavior and changing it would be a breaking changes to existing code 
* Not all errors returned from an activity result in `RespondActivityTaskFailedRequest` such as a cancelled error.
* In an error condition most of the time the result is meaningless/assumed invalid. Returning an error and a value that are both valid is a special case.

If you want to return some data with your error you should use details in NewApplicationError. That deals with all the problems listed above.
