### ISSUE TITLE
Client for test environment [golang]

### ISSUE THREAD

**Issue by orby-will** [temporalio/sdk-go#1211]
**Is your feature request related to a problem? Please describe.**
The testsuite.TestWorkflowEnvironment struct implements all the functions of client.Client interface except for the cancel function.

**Describe the solution you'd like**
Cannot use env (variable of type *"go.temporal.io/sdk/internal".TestWorkflowEnvironment) as client.Client value in assignment: *"go.temporal.io/sdk/internal".TestWorkflowEnvironment does not implement client.Client (wrong type for method CancelWorkflow)
		have CancelWorkflow()
		want CancelWorkflow(ctx "context".Context, workflowID string, runID string) error

**Describe alternatives you've considered**
Alternatively, if the team can provide a separate implementation for the client.

**Comment by cretz** [comment]
> The testsuite.TestWorkflowEnvironment struct implements all the functions of client.Client interface except for the cancel function.

There are actually/now many functions that it doesn't implement. The test environment is not meant to implement the client. That would be confusing for people that expect client behavior. Closing as won't fix, but feel free to continue discussion.
