### ISSUE TITLE
Queryable registry

### ISSUE THREAD

**Issue by edmondop** [temporalio/sdk-go#1212]
**Is your feature request related to a problem? Please describe.**

As discussed in this thread https://temporalio.slack.com/archives/CTDTU3J4T/p1692921277359619 there might be use cases where querying the worker for the registered activities and workflow could be useful

**Describe the solution you'd like**

**Describe alternatives you've considered**
Storing this information into an external data structure or as tsurdilo mentioned : "have seen users in code that creates worker and registers activities write small file to file system with what it registered and then in worker host pod/container expose like simple get api that returns this info"

**Comment by cretz** [comment]
(reposting what I put on PR)

I don't think this is necessary. Users are the ones adding to the registry, so they can keep track of what they add (or they can implement the interface themselves with something that does keep track or put what to register in a collection that is then registered all at once or whatever).

Also, adding methods to an interface is a breaking change (though we still sometimes do it).
