### ISSUE TITLE
Workflowchecker - override the entry point for the linter

### ISSUE THREAD

**Issue by HeatherLemieux** [temporalio/sdk-go#1229]
**Is your feature request related to a problem? Please describe.**
We use a helper function to set up additional logging for our workflows, 
```
func (w *Workflow) Run(ctx workflow.Context, wfInput *Input) error {
	return logger.WorkflowRun(ctx, wfInput, w.Execute)
}
```

which uses generics and looks like this
```
func WorkflowRun[I any](ctx workflow.Context, input I, runner WorkflowRunner[I]) error {
	l, onComplete := workflowRunBefore(ctx)
	defer onComplete()

	err := runner(ctx, l, input)

	workflowRunAfter(l, err)

	return err
}
```

since we're using generics the workflow checker doesn't know that the main body of the workflow is actually the `w.Execute` function. 

**Describe the solution you'd like**
Ideally we could change the entry point to be the `(w *Workflow) Execute` method instead of the `(w *Workflow) Run` method since we don't actually need any of the methods our logging package utilizes checked for determinism.

**Comment by cretz** [comment]
We have made a recent change in #1215 where we now check all functions that accept a `workflow.Context` as their first parameter. Can you check against `master` and see if this helps?

**Comment by HeatherLemieux** [comment]
I reinstalled the latest using `go install go.temporal.io/sdk/contrib/tools/workflowcheck@latest`
the output of `workflowcheck -V=full` is now `workflowcheck version devel comments-go-here buildID=de6a0b6fc69b7e711aee1bdf538832594e1e1993ef17d03bdb6506aa31c4436f` 

and I modified the first line of a workflow to be 
```
func (w *Workflow) Execute(ctx workflow.Context, l logger.Log, wfInput *Input) (*Input, error) {
	fmt.Println(time.Now())
    ...
```

and when I run the workflowcheck it does not return any results. 

Should I try and install workflowcheck in a different way?

**Comment by cretz** [comment]
Try `go install go.temporal.io/sdk/contrib/tools/workflowcheck@master` or build yourself

**Comment by HeatherLemieux** [comment]
Thanks! After trying master, I get the expected output.
