### ISSUE TITLE
Allow RetryPolicyOptions to take a predicate (function) to evaluate whether to retry or not

### ISSUE THREAD

**Issue by Mohsin-Ul-Islam** [temporalio/sdk-go#1257]
It would be great to have retry based on some predicate that the user provides alongside the existing retry options. 

For example:

```go
RetryPolicy{
  InitialInterval: time.Second * 1,
  MaxAttempts: 5,
  Predicate: func () bool { return true },
}
```

Something like this would be very convenient to have custom retry logic. Currently, I handle custom retries manually with Temporal.

**Comment by Quinn-With-Two-Ns** [comment]
Hi @Mohsin-Ul-Islam,  while I do think that would be useful I don't think it is feasible as described. `RetryPolicy`  are retries that are handled by the Temporal  service, and I wouldn't want to change that semantics. Therefore any `RetryPolicy` the worker needs to be able to serialize and send them to Temporal. We can't serialize an arbitrary function.

I  think a feature like is described here https://github.com/temporalio/sdk-java/issues/806 would be a more feasible alternative.
