### ISSUE TITLE
contrib/opentelemetry release that has AllowInvalidParentSpans

### ISSUE THREAD

**Issue by rivaldya** [temporalio/sdk-go#1259]
With the release of 1.25.0 where tracing interceptor accepts `AllowInvalidParentSpans` in tracer options (https://github.com/temporalio/sdk-go/pull/1178), there needs to be a subsequent release for contrib/opentelemetry (the latest one is 0.2.0) to apply the changes in https://github.com/temporalio/sdk-go/pull/1178 in contrib/opentelemetry

**Comment by Quinn-With-Two-Ns** [comment]
A latest release has been tagged https://pkg.go.dev/go.temporal.io/sdk/contrib/opentelemetry@v0.3.0
