### ISSUE TITLE
Simplify/fix worker API

### ISSUE THREAD

**Issue by ash2k** [temporalio/sdk-go#1261]
**Is your feature request related to a problem? Please describe.**

Tried using `Worker.Run()` with a context but the signature wants a `<-chan interface{}` while context's `Done()` returns `<-chan struct{}`.

**Describe the solution you'd like**

I think the API can be simplified to just have `Run(context.Context) error` method instead of the `Start()`/`Stop()` (i.e. remove them as they duplicate functionality).

`worker.InterruptCh()` is not needed because the user can always do it using [`signal.NotifyContext()`](https://pkg.go.dev/os/signal#NotifyContext).

**Describe alternatives you've considered**

If not the above, `Run()` should at least take the `context.Context` rather than a channel.

**Additional context**

N/A

**Comment by Quinn-With-Two-Ns** [comment]
In hindsight making `Run` take a `<-chan struct{}` would have been better then taking a `<-chan interface{}` or `context`, but we have stability requirements that prevent changing any of our public API.
