### ISSUE TITLE
Clean up internal/context

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/sdk-go#1270]
`internal/context.go` has some tech debt that should be cleaned up including

* Commented out code that should either be deleted or enabled https://github.com/temporalio/sdk-go/blob/269b55b8d184849209c6973fe913a427fafc07e3/internal/context.go#L348
* Incorrect use of `go` in a workflow context (this code appears to be dead, but should be removed regardless) https://github.com/temporalio/sdk-go/blob/269b55b8d184849209c6973fe913a427fafc07e3/internal/context.go#L239

**Comment by tharun208** [comment]
@Quinn-With-Two-Ns @Quinn-With-Two-Ns I like to work on this. Before, making a PR I have a question regarding the cleanup of incorrect use of the go routine, what should we do there after the cleanup? I am thinking of adding a `return` and end the function.

**Comment by Quinn-With-Two-Ns** [comment]
@tharun208 that be great! When I last reviewed the code I conclude that the `else` statement was never satisfied since `parentCancelCtx` should always return true. If we can verify that then we can probably just add a panic because that is an undefined state.
