### ISSUE TITLE
[Testsuite] Registering a Workflow and Activity with the same name and mocking  the activity causes issues

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/sdk-go#1273]
## Expected Behavior
Registering an activity and workflow with the same name is fine

## Actual Behavior
Registering an activity and workflow with the same name and trying to mock the activity causes the test suite to error with unexpected calls.

## Steps to Reproduce the Problem
This test will panic
```
s := testsuite.WorkflowTestSuite{}
env := s.NewTestWorkflowEnvironment()

expectedInput := activities.ActivityInput{}
env.OnActivity(activities.CoolTricks, mock.Anything, expectedInput).
	Return(activities.ActivityOutput{}, nil)

workflowInput := WorkflowInput{}

env.ExecuteWorkflow(CoolTricks, workflowInput)
assert.True(t, env.IsWorkflowCompleted())

var result *WorkflowOutput
err := env.GetWorkflowResult(&result)

assert.Error(t, err)
assert.Nil(t, result)
```

https://temporalio.slack.com/archives/CTDTU3J4T/p1697581733270889

**Comment by cretz** [comment]
Likely duplicate of #887

**Comment by Quinn-With-Two-Ns** [comment]
Closing as duplicate of https://github.com/temporalio/sdk-go/issues/887
