### ISSUE TITLE
Requesting a way to expose Opentelemetry trace parent information from worker request response protos

### ISSUE THREAD

**Issue by emmaCullen** [temporalio/sdk-go#1279]
**Is your feature request related to a problem? Please describe.**
We would like a way to link spans generated by our worker GRPC client interceptor, to the underlying temporal workflow spans. This way we can see what the grpc request was that led to a particular workflow execution span.

The plan is currently to add an attribute to our worker GRPC client span, something like `temporal.traceID`, or if it makes sense we can add an array of trace IDs as an attribute on the span.

In order to do this ^, we need a way to get the trace parent information out of the workflow proto request/response payloads. I noticed that this is usually stored in the Header field, although I am not familiar enough to know which types have this header and where the header will be nested for different types.

For example for one of the response type `PollWorkflowTaskQueueResponse`, an example of a trace parents we are interested in is under 

```
WorkflowExecution.History.Events[0].Attributes.HistoryEvent_WorkflowExecutionStartedEventAttributes.Header.Fields[defaultHeaderKey].GetData()
```

**Describe the solution you'd like**
A way for us to access the trace parent data from the GRPC client interceptor on the worker, for requests/responses where the tracer_data header is present.

Suggestion: a function that we can use to pass a request/response interface{} and get the traceparent data returned?

**Describe alternatives you've considered**
Not having it. With this approach we would have no way to link the grpc span to the subsequent workflow spans.

**Additional context**

Example full payload, we are interested in the `tracer_data` in bold:

&PollWorkflowTaskQueueResponse{TaskToken:[10 36 56 54 50 57 54 50 99 50 45 101 99 101 57 45 52 97 54 57 45 56 55 102 57 45 102 100 55 57 50 50 50 97 53 55 101 57 18 37 101 50 101 95 102 97 107 101 114 111 99 107 95 97 117 116 104 95 49 54 57 56 50 56 56 50 57 53 49 57 54 51 48 52 48 48 48 26 36 49 97 98 52 99 97 50 99 45 54 50 50 51 45 52 54 57 53 45 57 99 100 51 45 55 102 102 97 97 53 102 51 50 53 98 48 32 2 40 1 74 11 8 205 11 16 168 165 149 6 24 203 8 80 3 88 203 8 98 11 8 176 165 231 169 6 16 183 241 129 26],WorkflowExecution:&v13.WorkflowExecution{WorkflowId:e2e_fakerock_auth_1698288295196304000,RunId:1ab4ca2c-6223-4695-9cd3-7ffaa5f325b0,},WorkflowType:&v13.WorkflowType{Name:HelloWorkflow,},PreviousStartedEventId:0,StartedEventId:3,Attempt:1,BacklogCountHint:0,History:&v16.History{Events:[]*HistoryEvent{&HistoryEvent{EventId:1,EventTime:2023-10-26 02:45:04.043561034 +0000 UTC,EventType:WorkflowExecutionStarted,Version:1099,TaskId:12931743,Attributes:&HistoryEvent_WorkflowExecutionStartedEventAttributes{WorkflowExecutionStartedEventAttributes:&WorkflowExecutionStartedEventAttributes{WorkflowType:&v1.WorkflowType{Name:HelloWorkflow,},ParentWorkflowNamespace:,ParentWorkflowExecution:nil,ParentInitiatedEventId:0,TaskQueue:&v11.TaskQueue{Name:default-queue,Kind:Normal,NormalName:,},Input:&v1.Payloads{Payloads:[]*Payload{&Payload{Metadata:map[string][]byte{encoding: [106 115 111 110 47 112 108 97 105 110],},Data:[34 70 111 111 98 97 114 34],},},},WorkflowExecutionTimeout:0s,WorkflowRunTimeout:0s,WorkflowTaskTimeout:10s,ContinuedExecutionRunId:,Initiator:Unspecified,ContinuedFailure:nil,LastCompletionResult:nil,OriginalExecutionRunId:1ab4ca2c-6223-4695-9cd3-7ffaa5f325b0,Identity:e2e-starter,FirstExecutionRunId:1ab4ca2c-6223-4695-9cd3-7ffaa5f325b0,RetryPolicy:nil,Attempt:1,WorkflowExecutionExpirationTime:<nil>,CronSchedule:,FirstWorkflowTaskBackoff:0s,Memo:nil,SearchAttributes:nil,PrevAutoResetPoints:nil,Header:&v1.Header{Fields:map[string]*Payload{**_tracer-data: &Payload{Metadata:map[string][]byte{encoding: [106 115 111 110 47 112 108 97 105 110],},Data:[123 34 116 114 97 99 101 112 97 114 101 110 116 34 58 34 48 48 45 97 55 57 102 56 49 53 55 101 52 53 102 54 102 54 48 56 53 53 99 55 54 50 97 102 56 102 99 52 99 50 48 45 52 48 55 51 55 50 50 51 50 54 57 48 49 53 100 50 45 48 49 34 125]**,},},},ParentInitiatedEventVersion:0,ParentWorkflowNamespaceId:,WorkflowId:e2e_fakerock_auth_1698288295196304000,SourceVersionStamp:nil,},},WorkerMayIgnore:false,},&HistoryEvent{EventId:2,EventTime:2023-10-26 02:45:04.043607004 +0000 UTC,EventType:WorkflowTaskScheduled,Version:1099,TaskId:12931744,Attributes:&HistoryEvent_WorkflowTaskScheduledEventAttributes{WorkflowTaskScheduledEventAttributes:&WorkflowTaskScheduledEventAttributes{TaskQueue:&v11.TaskQueue{Name:default-queue,Kind:Normal,NormalName:,},StartToCloseTimeout:10s,Attempt:1,},},WorkerMayIgnore:false,},&HistoryEvent{EventId:3,EventTime:2023-10-26 02:45:04.054556855 +0000 UTC,EventType:WorkflowTaskStarted,Version:1099,TaskId:12931749,Attributes:&HistoryEvent_WorkflowTaskStartedEventAttributes{WorkflowTaskStartedEventAttributes:&WorkflowTaskStartedEventAttributes{ScheduledEventId:2,Identity:e2e-fakerock-worker,RequestId:75b36cc7-b33f-4248-b757-dcb2007ce316,SuggestContinueAsNew:false,HistorySizeBytes:972,},},WorkerMayIgnore:false,},},},NextPageToken:[],Query:nil,WorkflowExecutionTaskQueue:&v14.TaskQueue{Name:default-queue,Kind:Normal,NormalName:,},ScheduledTime:2023-10-26 02:45:04.043607004 +0000 UTC,StartedTime:2023-10-26 02:45:04.054556855 +0000 UTC,Queries:map[string]*v17.WorkflowQuery{},Messages:[]*Message{},}

**Comment by cretz** [comment]
The OpenTelemetry interceptor doesn't add spans on every call, only some workflow calls. Assuming you're talking about grabbing the span on outbound client calls, you can add your own `ClientInterceptor` after the OpenTelemetry interceptor in the client-configured list and use regular span context extraction. We just call https://pkg.go.dev/go.opentelemetry.io/otel/trace#ContextWithSpan in the interceptor, so you can call https://pkg.go.dev/go.opentelemetry.io/otel/trace#SpanFromContext in your later interceptor to get it out.

Does this help? Or might you need the span at another time instead of outbound client calls?

**Comment by emmaCullen** [comment]
Hi @cretz , thanks for your response. I will give that a try, the thing we want is to add the workflow traceID to the grpc client span, we need to start that span in our grpc interceptor as we need access to various grpc-specific values for other opentelemetry attributes. 

I will try and see  what happens if I use a `ClientInterceptor` to add an attribute to that parent span 🤞

**Comment by cretz** [comment]
:+1: Note the spans we start in interceptors are not the same as spans that a gRPC client may start. The spans in the interceptors are deserialized and used by other worker processes to re-parent their spans. That's why we only create spans specifically on things like start workflow.

Feel free to reopen (or join us on Slack or forums) if you need help with your use case here.
