### ISSUE TITLE
Requesting a way to expose workflow IDs from relevant worker request response protos

### ISSUE THREAD

**Issue by emmaCullen** [temporalio/sdk-go#1280]
**Is your feature request related to a problem? Please describe.**
We would like a way to add the workflow ID as an attribute to spans generated by our GRPC client interceptor. The ID is present in the proto, but we do not always know where it will be and what all of the types are.

At the moment we are doing this using a switch as follows. This is brittle as we dont have internal knowledge and if the API changes.

```
	switch v := req.(type) {
	case *proto.GetSystemInfoRequest:
	case *proto.RegisterNamespaceRequest:
	case *proto.ListNamespacesRequest:
	case *proto.UpdateNamespaceRequest:
	case *proto.DeprecateNamespaceRequest:
	case *proto.PollWorkflowTaskQueueRequest:
	case *proto.RespondWorkflowTaskCompletedRequest:
	case *proto.RespondWorkflowTaskFailedRequest:
	case *proto.PollActivityTaskQueueRequest:
	case *proto.DescribeNamespaceRequest:
	case *proto.RespondActivityTaskCompletedRequest:
	case *proto.RequestCancelWorkflowExecutionRequest:
		if v.GetWorkflowExecution() != nil {
			id = v.GetWorkflowExecution().WorkflowId
		}
	case *proto.SignalWorkflowExecutionRequest:
		if v.GetWorkflowExecution() != nil {
			id = v.GetWorkflowExecution().WorkflowId
		}
	case *proto.ResetWorkflowExecutionRequest:
		if v.GetWorkflowExecution() != nil {
			id = v.GetWorkflowExecution().WorkflowId
		}
	case *proto.UpdateWorkflowExecutionRequest:
		if v.GetWorkflowExecution() != nil {
			id = v.GetWorkflowExecution().WorkflowId
		}
	case *proto.TerminateWorkflowExecutionRequest:
		if v.GetWorkflowExecution() != nil {
			id = v.GetWorkflowExecution().WorkflowId
		}
	case *proto.DeleteWorkflowExecutionRequest:
		if v.GetWorkflowExecution() != nil {
			id = v.GetWorkflowExecution().WorkflowId
		}
	case *proto.QueryWorkflowRequest:
		if v.GetExecution() != nil {
			id = v.GetExecution().WorkflowId
		}
	case *proto.ResetStickyTaskQueueRequest:
		if v.GetExecution() != nil {
			id = v.GetExecution().WorkflowId
		}
	case *proto.DescribeWorkflowExecutionRequest:
		if v.GetExecution() != nil {
			id = v.GetExecution().WorkflowId
		}
	case *proto.GetWorkflowExecutionHistoryReverseRequest:
		if v.GetExecution() != nil {
			id = v.GetExecution().WorkflowId
		}
	case *proto.GetWorkflowExecutionHistoryRequest:
		if v.GetExecution() != nil {
			id = v.GetExecution().WorkflowId
		}
	case *proto.StartBatchOperationRequest:
		if v.GetExecutions() != nil {
			execution := v.GetExecutions()
			id = execution[0].WorkflowId
		}
	case *proto.StartWorkflowExecutionRequest:
		id = v.GetWorkflowId()
	case *proto.RecordActivityTaskHeartbeatByIdRequest:
		id = v.GetWorkflowId()
	case *proto.RespondActivityTaskCanceledByIdRequest:
		id = v.GetWorkflowId()
	case *proto.RespondActivityTaskFailedByIdRequest:
		id = v.GetWorkflowId()
	case *proto.RespondActivityTaskCompletedByIdRequest:
		id = v.GetWorkflowId()
	case *proto.SignalWithStartWorkflowExecutionRequest:
		id = v.GetWorkflowId()
	default:
		log.Debug(ctx, fmt.Sprintf("Temporal Workflow Service Unknown request. %v\n", req))
	}
```

**Describe the solution you'd like**
A function that we can use to pass a request/response and get the workflow ID

**Describe alternatives you've considered**
The alternative is not to be able to attach workflow ID to these grpc client spans. Or we can continue to use the above switch statement.

**Additional context**

**Comment by cretz** [comment]
> This is brittle as we dont have internal knowledge and if the API changes.

The API is public, not internal, and doesn't upgrade unless you upgrade the SDK. The SDK, like anyone, consumes https://github.com/temporalio/api/tree/master/temporal/api/workflowservice/v1 (via https://github.com/temporalio/api-go) and may be upgraded when you upgrade the SDK. I am not sure us taking this same switch statement and putting it in the SDK for this specific use case has enough general-purpose value.

I think the approach you are taking here makes sense, and we don't really change existing API (or even add workflow ID somewhere it wasn't before), though we may add some entirely new API with workflow ID upon creation.

What many users do in situations where they need to future proof themselves on new API additions is just have a unit test which reflectively goes over the workflow service interface calling their function with an instantiated version of every request type and asserting none fail (i.e. have your method return false that you can ignore in prod but assert against during test).

**Comment by emmaCullen** [comment]
Hi @cretz, yes true you make a good point. If you think our current approach is fine, then we will continue to do that switch ourselves and add that unit test.  

Thanks again for the suggestions.

**Comment by cretz** [comment]
:+1: I do think it is best as opposed to us exposing an extract-workflow-id-from-grpc-request in our public lirary API
