### ISSUE TITLE
Error "getState: illegal access from outside of workflow context" after sdk update  1.22.1 -> 1.25.1

### ISSUE THREAD

**Issue by vmalyavin** [temporalio/sdk-go#1287]
[You can view full workflow code of reproduction in repo](https://github.com/vmalyavin/temporalissue)

We have a simple workflow cycle with select
- pereodic polling(payment status from activity every 2-3min)
- workflow-cancel signal receive
- timeout
```go
package testflow

import (
	"time"

	"go.temporal.io/sdk/workflow"

	"temporalissue/models"
	"temporalissue/workflows/testflow/signals"
)

func PollPaymentStatus20MinOrReceiveCancel(
	ctx workflow.Context, order *models.Order,
) models.PaymentStatus {
	var status models.PaymentStatus

	// cycle over timer - 20min
	itsOver := false
	overTimer := workflow.NewTimer(ctx, 20*time.Minute)
	overCallback := func(_ workflow.Future) { itsOver = true }

	for !itsOver {
		pollTimer, pollCallback := pollPaymentStatus(
			ctx, 3*time.Minute, &status, order,
		)
		selector := workflow.NewSelector(ctx).
			AddFuture(pollTimer, pollCallback).
			AddFuture(overTimer, overCallback).
			AddReceive(signals.CancellationReceive(ctx, order))
		selector.Select(ctx)

		// end cycle if paymentstatus is changed from new; or order is cancelled
		if status == models.PaymentStatusNew || order.Status == models.OrderStatusCancel {
			break
		}
	}

	return status
}
```

then after end of the cycle we 
- complete workflow

or  
- cancel it(by signal) and poll payment status for 10min after cancel:
```go
func PollPaymentStatus10Min(
	ctx workflow.Context, order *models.Order,
) models.PaymentStatus {
	var status models.PaymentStatus

	// cycle over timer - 10min
	itsOver := false
	overTimer := workflow.NewTimer(ctx, 10*time.Minute)
	overCallback := func(_ workflow.Future) { itsOver = true }

	for !itsOver {
		pollTimer, pollCallback := pollPaymentStatus(
			ctx, 2*time.Minute, &status, order,
		)
		selector := workflow.NewSelector(ctx).
			AddFuture(pollTimer, pollCallback).
			AddFuture(overTimer, overCallback)
		// no cancel receive
		selector.Select(ctx)

		// end cycle if paymentstatus is changed from new
		if status != models.PaymentStatusNew {
			break
		}
	}

	return status
}
```
## Expected Behavior
Workflow is gracefully cancelled and all timers is cancelled by workflow context

## Actual Behavior
panic with events outside workflow context:
_"test panicked: getState: illegal access from outside of workflow context"_

## Steps to Reproduce the Problem
Example of workflow with error reproduction available
[in repo](https://github.com/vmalyavin/temporalissue)
you can pull it and try

## Specifications
  - Version: 1.25.1

**Comment by Quinn-With-Two-Ns** [comment]
The issue appears to be that return a cancelled error from a workflow in the test suite causes the test suite to call the [cancel callback ](https://github.com/temporalio/sdk-go/blob/master/internal/internal_workflow_testsuite.go#L876). This is not allowed as at this point the workflow execution is finished.

**Comment by vmalyavin** [comment]
It means - this is testsuite-only problem?
