### ISSUE TITLE
Add GetName() func to Signal Chanel to return human readable name

### ISSUE THREAD

**Issue by ilewin** [temporalio/sdk-go#1304]
**Is your feature request related to a problem? Please describe.**
While dynamically creating signal channels and assigning callback functions to it, it is not possible to identify the channel name in the callback funciton

**Describe the solution you'd like**
adding a GetName() string func to the Chanel interface

**Comment by Quinn-With-Two-Ns** [comment]
Why can't you add the name when creating the callback? Normal Go channels don't support a name so I am not sure Temporal channels would need such a functionality

**Comment by Quinn-With-Two-Ns** [comment]
If we did want to include name, probably makes sense to group with other signal info https://github.com/temporalio/sdk-go/issues/1143
