### ISSUE TITLE
go get fails because sourcegraph.com/sourcegraph/appdash-data is no longer available

### ISSUE THREAD

**Issue by noqcks** [temporalio/sdk-go#1326]
## Actual Behavior

contrib go.mod imports `gopkg.in/DataDog/dd-trace-go.v1 v1.42.0` which has a transitive dep on `sourcegraph.com/sourcegraph/appdash-data`, but appdash-data is no longer reachable.

https://github.com/temporalio/sdk-go/blob/master/contrib/datadog/go.mod#L8

```
#25 4.314 go: go.temporal.io/sdk/contrib/datadog@v0.1.0 requires
#25 4.314 	gopkg.in/DataDog/dd-trace-go.v1@v1.42.0 requires
#25 4.314 	github.com/99designs/gqlgen@v0.14.0 requires
#25 4.314 	sourcegraph.com/sourcegraph/appdash-data@v0.0.0-20151005[221](https://github.com/myorg/myrepo/actions/runs/2257091395/job/19770439394#step:6:223)446-73f23eafcf67: unrecognized import path "sourcegraph.com/sourcegraph/appdash-data": reading https://sourcegraph.com/sourcegraph/appdash-data?go-get=1: 404 Not Found
```

upgrading `gopkg.in/DataDog/dd-trace-go.v1` to the most recent version will remove sourcegraph as a dep.

See related issues in other repos:
- https://github.com/99designs/gqlgen-contrib/issues/34

## Steps to Reproduce the Problem

go.mod
```
module mymodule

require (
	gopkg.in/DataDog/dd-trace-go.v1 v1.58.0
)
```
$ go mod tidy

**Comment by Quinn-With-Two-Ns** [comment]
Looks like we need to upgrade our version of `gopkg.in/DataDog/dd-trace-go.v1`. In the mean time you can try explicitly upgrading `gopkg.in/DataDog/dd-trace-go.v1` to work around this issue.

**Comment by TCashion** [comment]
This worked as a temporary workaround: 

`go mod edit -replace=gopkg.in/DataDog/dd-trace-go.v1@v1.42.0=gopkg.in/DataDog/dd-trace-go.v1@v1.58.1`

Is there any update on whether there will be an official upgrade in the next release of the Go SDK?

**Comment by Quinn-With-Two-Ns** [comment]
@TCashion a simple `go get gopkg.in/DataDog/dd-trace-go.v1` should upgrade you to the latest.

>Is there any update on whether there will be an official upgrade in the next release of the Go SDK?

The datadog module is versioned and released separately from the Go SDK, but it will be updated.
