### ISSUE TITLE
Temporal Go SDK can not be used with bazel_gazelle 0.32+

### ISSUE THREAD

**Issue by saumitrabhave** [temporalio/sdk-go#1331]
## Expected Behavior
The prject should build fine

## Actual Behavior
Error is produced is bazel build like

/external/com_github_grpc_ecosystem_grpc_gateway/runtime/BUILD.bazel:5:11: no such package '@go_googleapis//google/api': The repository '@go_googleapis' could not be resolved: Repository '@go_googleapis' is not defined and referenced by '@com_github_grpc_ecosystem_grpc_gateway//runtime:go_default_library'

## Steps to Reproduce the Problem

  1. go get go.temporal.io/sdk  [ this gets v1.25.1  which also adds github.com/grpc-ecosystem/grpc-gateway v1.16.0  as dependency]
  2. bazel run //:gazelle-update-repos
  3. bazel build the project

## Specifications

Errors:
  - io_bazel_rules_go: 0.42
  - bazel_gazelle: 0.33

Works Fine with 
  - io_bazel_rules_go: 0.40
  - bazel_gazelle: 0.31.1

## Additional Details

I am a noob in bazel and go build tool chains in general but with whatever I could see there might be multiple issues at play. even to build with older versions(as mentioned above) I had to add `build_naming_convention = "go_default_library",  #keep` to the `com_github_grpc_ecosystem_grpc_gateway` dependency.

Even after adding this, if I increase the bazelle_gazelle version, it still errors out with error above. I think it has something to do with the fact that bazelle_gazelle stopped resolving go and proto imports to @go_googleapis since 0.32 as per https://github.com/bazelbuild/bazel-gazelle/releases. and that is where the injection point is for the error I am facing.

**Comment by Quinn-With-Two-Ns** [comment]
I am not super familiar with bazel, but is the problem really with `github.com/grpc-ecosystem/grpc-gateway`  does the same issue exist with `github.com/grpc-ecosystem/grpc-gateway/v2`? Since that is what the head of the repo uses.

**Comment by Quinn-With-Two-Ns** [comment]
@SpencerC I am not sure how your PR is related to this issue.

Note: `grpc-gateway` is already updated to v2 on the head of the repo

**Comment by SpencerC** [comment]
@Quinn-With-Two-Ns oops, got my gRPC packages mixed up! It works on HEAD. @saumitrabhave try `go get go.temporal.io/sdk@94a5f5f81f98b9351a0df0dd6833582e83052a0e`.

**Comment by saumitrabhave** [comment]
Thanks @Quinn-With-Two-Ns and @SpencerC ... let me check and get back

**Comment by Quinn-With-Two-Ns** [comment]
Closing since the Go SDK no uses `grpc-gateway v2`
