### ISSUE TITLE
workflow.CreateSession create more sessions than MaxConcurrentSessionExecutionSize

### ISSUE THREAD

**Issue by avarabyeu** [temporalio/sdk-go#1339]
## Expected Behavior
Worker does not create more sessions than defined in MaxConcurrentSessionExecutionSize. Workflow tasks are queued until worker is ready to accept new one. 

## Actual Behavior
More sessions than defined in MaxConcurrentSessionExecutionSize are created

## Steps to Reproduce the Problem
I've got quite unusual use case when i need a worker to handle only one session. Workflow itself is quite basic - when session is started, workflow waits for external signal for a while (some sort of approval), than executes single activity. The activity uses serial port, so running two activities / sessions in parallel is prohibited. Normally, there are 2-3 workers are running in parallel. 
 
From time to time i see some workers starting 2 sessions in parallel which seems to be a bug since MaxConcurrentSessionExecutionSize=1 is set to all workers.  

## Specifications
Temporal CLI server
  - Version: 1.22.2 server, 1.25.1 go SDK
  - Platform: Linux

**Comment by Quinn-With-Two-Ns** [comment]
Can you share some more details around this scenario? Ideally some minimal example that reproduces this issue

**Comment by avarabyeu** [comment]
Unfortunately, i won't be able to share the complete example, but here are some pieces. Hope it makes sense:
So, the workflow is basically executor of 3D-printer. That's why i can't have two workflows/sessions running in parallel for the same worker instance. 
There is root workflow that handles pre-processing and other stuff. When the image is ready for print, root workflow creates child workflow that runs on the worker physically connected to the printer. 
This is how printer worker is created:
```go
                        w := worker.New(c, "printers-queue", worker.Options{
				Identity:                           fmt.Sprintf("printer-queue-%s", cfg.PrinterName),
				MaxConcurrentSessionExecutionSize:  1,
				EnableSessionWorker:                true,
			})
			pq := printerqueue.NewPrinterWorkflow(cfg.PrinterName)
			w.RegisterWorkflow(pq.PrinterQueue)
                         w.RegisterActivityWithOptions(printActivity.Run, activity.RegisterOptions{
				Name: "PrinterActivity",
			})			
```
I've got at least two workers, running as docker containers. 

This is how workflow looks like:

```go
func (wfl *PrinterWorkflow) PrinterQueue(ctx workflow.Context, input string) error {
	sessionOptions := &workflow.SessionOptions{
		CreationTimeout:  1 * time.Hour,
		ExecutionTimeout: 1 * time.Hour,
	}
	// Create a Session with the Worker so that all Activities execute with the same Worker.
	sessionCtx, err := workflow.CreateSession(ctx, sessionOptions)
	if err != nil {
		return err
	}
	defer workflow.CompleteSession(sessionCtx)

        // let parent workflow that printer is assigned and ready to print
	parent := workflow.GetInfo(ctx).ParentWorkflowExecution
	if err := workflow.SignalExternalWorkflow(ctx,
		parent.ID,
		parent.RunID, SignalNameAssigned, wfl.printer).Get(ctx, nil); err != nil {
		return err
	}

	approved, err := wfl.waitForApproval(ctx)
	if err != nil {
		return err
	}
	if !approved {
		return errors.New("printing isn't approved")
	}
        // once approved, start printing
	ctx = workflow.WithActivityOptions(ctx, workflow.ActivityOptions{
		StartToCloseTimeout: 1 * time.Hour,
		TaskQueue:           workflow.GetInfo(ctx).TaskQueueName,
	})
	err = workflow.ExecuteActivity(ctx, "PrinterActivity", activities.PrintActivityInput{
		Filename: input,
	}).Get(ctx, nil)
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by avarabyeu** [comment]
That makes perfect sense and explains the problem i have. 
Thanks a lot for prompt replies @Quinn-With-Two-Ns 
Closing this one since it's not a bug
