### ISSUE TITLE
support generic functions for activites

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [temporalio/sdk-go#1355]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to use a (specific instance of a) generic
function for an activity, and I have to register it using a specific name I
pass in `activity.RegisterOptions` when calling `RegisterActivityWithOptions`.

For when I just use the function name, as in
```
    my_worker = worker.New(my_client, myQueue, worker.Options{})
    my_worker.RegisterActivity(publishEvent[OrderEvent])
    my_worker.RegisterActivity(publishEvent[ArchiveEvent])
```

I get an error on the second invaction:

```
panic: activity type "]" is already registered
```

I've traced the source to the `get_function_name` function in
`internal/internal_worker.go` - the string returned by
`runtime.FuncForPC(reflect.ValueOf(i).Pointer()).Name()` replaces the concrete
type in the generic function by `...`, resulting e.g. in `publishEvent[...]` -
the subsequent splitting on `.` and picking the last element results in a
function name of `"]"`, which is of course non-sensical.

**Describe the solution you'd like**
Improve the parsing of function names to support generics, so generic functions
can be registered directly.

**Describe alternatives you've considered**
A functioning workaround is, as alluded above, to just use the following:
```
    my_worker.RegisterActivityWithOptions(
      publishEvent[OrderEvent],
      activity.RegisterOptions{Name: "publishOrderEvent"},
    )
    my_worker.RegisterActivityWithOptions(
      publishEvent[ArchiveEvent],
      activity.RegisterOptions{Name: "publishArchiveEvent"},
    )
```
So if you say this is a no-fix, and a note in the docs about this, I'll be
happy, too : )

If that's an option, I am also willing to try and contribute an MR.

**Comment by Quinn-With-Two-Ns** [comment]
We should definitely do better then registering the activity as "]"

What would be the new proposed way to get the name of a function be? Since the current method `runtime.FuncForPC(reflect.ValueOf(i).Pointer()).Name()`   lacks the generic parameters in the output no amount of improved parsing of that result would let you register `publishEvent[OrderEvent]`  and `publishEvent[OrderEvent]` since they both output `publishEvent[...]` if I understand the issue.

**Comment by valentin-krasontovitsch** [comment]
hey, and thanks for the response : )

yaa you're right on spot - that function is not good enough.
i've never tried to look into behind the scenes of go, i.e. use runtime or reflect package, so this is all very new territory for me.

i tried experimenting around a bit, and i got as far as looking at the type of the function pointer - that contains the types of the input arguments.

i have a [little script for experimenting](https://gist.github.com/valentin-krasontovitsch/dc3786551cd2c85fb64ab845d76f05fb) that i uploaded as a gist. it produces for a function with one concrete and two generic inputs the following output consisting of
- type
- full name
- return values of get function name func

```
type of i: func(int, main.OrderEvent, string)
fullName: main.Echo[...]
] false
```

so this could be used to create a hereustic for making a function name that reflects the concrete types for generic functions.
but i see that the get function name for concrete functions doesn't take into account input types in general, which makes sense, as you cannot have two functions with same name but different input types.

so maybe we just need to fix the get function name function to return what we would expect for a generic function, namely the function name, instead of `]`, and think about how to attack the issue of registering generic functions in general. and for that I have some vague ideas based on heuristics, but not enough experience with generics or typing in general (not a computer science major) to be confident to come up with a working strategy.

what do SDKs for other languages do, in particular languages that perhaps allow overloading? maybe we can find some inspiration there?

**Comment by cretz** [comment]
> what do SDKs for other languages do, in particular languages that perhaps allow overloading?

No SDKs allow generics in functions that they must reflectively call (e.g. workflows and activities) from what I'm aware of. As for overloading, depending on the SDK, actual functions are marked for use so concerns about overloading don't apply (though if you mark two things of the same name as activities, you'll surely get a duplicate-activity error upon registration).

I would strongly suggest making a concrete non-generic function as your activity. If it needs to be a one-liner to a generic form, so be it.

**Comment by Quinn-With-Two-Ns** [comment]
Yeah as fair as I am aware there isn't a good way for the SDK to create a unique name at runtime for each instance of a generic function.

**Comment by valentin-krasontovitsch** [comment]
alright, so i'm gonna close this as won't fix as there is a work-around (or even two! hadn't thought of making a one-liner concrete function that wraps an instance of the generic one)) with reasonably small overhead for developers. thanks for the discussion!

**Comment by valentin-krasontovitsch** [comment]
argh i was too fast - how do you feel about adding a note about (one of the) workarounds in the docs?

**Comment by cretz** [comment]
I will bring up to the docs team internally
