### ISSUE TITLE
 Move SDK Errors Out of Internal Package for Enhanced Usability

### ISSUE THREAD

**Issue by pantafive** [temporalio/sdk-go#1364]
Hi Temporal Team,

I've been looking at the Temporal Go SDK and I noticed that the errors for the SDK are kept in the internal package (see [internal/error.go, lines 261-283](https://github.com/temporalio/sdk-go/blob/171504d947f447e5981b794b79abbb5fe0e9374b/internal/error.go#L261-L283)). Keeping these errors inside internal makes it hard for developers to use them directly. This can lead to clunky ways of dealing with errors, like having to match error messages as strings.

In Go, we usually put stuff in internal when we don't want others to use it directly. But errors from an SDK are something developers often need to work with. If these errors were in a package that's easier to access, it would make more sense and help developers handle errors more easily.

I suggest moving these SDK errors to a package that's not internal. This would make things easier for developers using the SDK and fit better with how we usually organize packages in Go.

Thanks for considering this. Looking forward to hearing what you think.

**Comment by Quinn-With-Two-Ns** [comment]
Errors a users is expected to need are aliased in other packages for example  `ErrActivityResultPending` is aliased here https://github.com/temporalio/sdk-go/blob/master/activity/activity.go#L51. If there is any specific error you encountered that is not aliased we can add an alias for it specifically .

**Comment by Quinn-With-Two-Ns** [comment]
`ErrScheduleAlreadyRunning` is already exposed https://github.com/temporalio/sdk-go/blob/171504d947f447e5981b794b79abbb5fe0e9374b/temporal/error.go#L163

**Comment by pantafive** [comment]
Thank you very much!
