### ISSUE TITLE
Document `Client.GetSearchAttributes` doesn't work in cloud

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#1372]
**Describe the solution you'd like**

Document that `Client.GetSearchAttributes` doesn't work in cloud and is self-hosted only

**Comment by Quinn-With-Two-Ns** [comment]
IMO this does't belong in the SDK docs, we don't explicitly document what APIs do and don't work in cloud and more importantly it isn't a property of an SDK version if something is supported in cloud or not. Cloud can add support and make the SDK comment wrong. I think any docs like this belong in https://docs.temporal.io/

**Comment by cretz** [comment]
Agree usually, but I think this is the only high level workflow client call in any of our SDKs that doesn't work in cloud and self-hosted (haven't checked some of those other list calls).
