### ISSUE TITLE
The timeout is triggered twice earlier than ScheduleToCloseTimeout is set

### ISSUE THREAD

**Issue by sosnovski** [temporalio/sdk-go#1380]
## Expected Behavior
I expect the workflow to fail after 1 minute
<img width="758" alt="Снимок экрана 2024-02-07 в 22 38 37" src="https://github.com/temporalio/sdk-go/assets/6298668/e26242fe-c8ea-4b80-9dfc-31e291c143a5">

## Actual Behavior
Workflow completes exactly twice as fast, in about 30 seconds.
<img width="1866" alt="Снимок экрана 2024-02-07 в 22 39 37" src="https://github.com/temporalio/sdk-go/assets/6298668/2312cb65-f409-4e31-a3f8-9674c4c82056">

I noticed that the timeout is triggered twice as early as set in the ScheduleToCloseTimeout timeout. 
I tried to specify 10 minutes and the timeout worked after 5.

## Steps to Reproduce the Problem

Run this workflow without any timeouts:
```golang
func SampleWorkflow(ctx workflow.Context) error {
	ao := workflow.ActivityOptions{
		ScheduleToCloseTimeout: time.Minute,
	}
	ctx = workflow.WithActivityOptions(ctx, ao)

	err := workflow.ExecuteActivity(ctx, SampleActivity).Get(ctx, nil)
	if err != nil {
		return err
	}

	return nil
}

func SampleActivity() error {
	return errors.New("some error")
}
```

## Specifications

  - Version: v1.25.1
  - Platform: Mac OS 14.2 ARM

**Comment by Quinn-With-Two-Ns** [comment]
Could you share the history of this workflow?

**Comment by Quinn-With-Two-Ns** [comment]
@sosnovski On further research this is expected, Since your activity always fails the backoff time will grow exponentially from 1s doubling every retry until the next attempt time is after the activity timeout. If the next schedule time is after the `schedule_to_close` time, we skip the attempt and fail the activity.
