### ISSUE TITLE
Activity spans not nested under parent workflow

### ISSUE THREAD

**Issue by albertteoh** [temporalio/sdk-go#1386]
## Expected Behavior

Workflow activities to be child spans of the workflow that's executing them.

## Actual Behavior

From this screenshot, the "FulfillmentWorkflow" is the workflow that executes the list of activities that you see as "root" spans below it (prefixed with `StartActivity` and `RunActivity`).

Maybe this is expected behaviour given it's executed asynchronously?

<img width="1337" alt="temporal-trace" src="https://github.com/temporalio/sdk-go/assets/26584478/a6dd1b83-69a3-45bb-b5dd-20ad18246b22">

## Steps to Reproduce the Problem

Use the opentelemetry interceptor:

```go
import (
        // ...
        "go.temporal.io/sdk/contrib/opentelemetry"
)

func New(...) {
	intceptor, err := opentelemetry.NewTracingInterceptor(opentelemetry.TracerOptions{
		TextMapPropagator: otel.GetTextMapPropagator(),
	})
	if err != nil {
		return nil, fmt.Errorf("creating tracing interceptor: %w", err)
	}

	tlogger := zapAdapter{logger}
	c, err := client.Dial(client.Options{
                 // ...
		Interceptors:      []interceptor.ClientInterceptor{intceptor},
	})
	if err != nil {
		logger.Fatalf("unable to create client: %s", err)
	}
// ...
}
```

Then the workflow is executed like so:
```go
	workflowOptions := temporal.StartWorkflowOptions{
		ID:        id,
		TaskQueue: taskQueue,
	}
	if _, err := m.client.ExecuteWorkflow(
		ctx,
		workflowOptions,
		FulfillmentWorkflow,
		// input args
	); err != nil {
		return fmt.Errorf("unable to execute workflow, error: %w", err)
	}
```

## Specifications

  - Version:
```
	go.opentelemetry.io/otel/sdk v1.16.0
	go.temporal.io/api v1.23.0
	go.temporal.io/sdk v1.23.1
	go.temporal.io/sdk/contrib/opentelemetry v0.2.0
```

**Comment by cretz** [comment]
Hrmm, while there can be span breakage across replays, it shouldn't affect the fact that the overall parent is still the same `StartWorkflow` from the client. Can you confirm that the client is created the same way for all execute-workflow calls and workers in use? Can you alter https://github.com/temporalio/samples-go/tree/main/opentelemetry to replicate your error.

**Comment by albertteoh** [comment]
Thanks for the speedy response, @cretz! After a lot of debugging, it turns out this is not a bug, but rather that the "StartWorkflow:FulfillmentWorkflow" had a pending child span "RunWorkflow:FulfillmentWorkflow" which all the activities depended on.

The reason why the activity spans were orphaned was because the "RunWorkflow:FulfillmentWorkflow" span is only emitted upon completion. I've attached a screenshot of the trace after completing the workflow, showing the child spans happily reunited with their parent 😄 

<img width="743" alt="Screenshot 2024-02-13 at 7 00 31 pm" src="https://github.com/temporalio/sdk-go/assets/26584478/66b4959a-4e33-4a0e-b3fa-3c89a7ef6b8f">
