### ISSUE TITLE
Reset `WorkflowPanicPolicy` option

### ISSUE THREAD

**Issue by elb3k** [temporalio/sdk-go#1399]
**Is your feature request related to a problem? Please describe.**
All workflows we use are restartable, workflow versioning is not possible, since there are a lot of changes being deployed.

**Describe the solution you'd like**
When `WorkflowPanicPolicy` is set to `ResetWorkflow`, the workflow will restart when a panic occurs.
An additional option called `ResetReapplyType` same as in the `ResetWorkflowExecutionRequest` (option is used when resetting a workflow)

**Describe alternatives you've considered**
Setting `WorkflowPanicPolicy` as `FailWorkflow` and set workflow `RetryPolicy` seems to be working. But there are a few caveats with it:
- Any real errors returning from the workflow to terminate the workflow must be wrapped with `temporal.NewNonRetyableError`
- Reset does not replay the signals (which we want).

**Additional context**
Discussion related to this feature request: https://community.temporal.io/t/catching-nondeterministicexception/5020/5

**Comment by Quinn-With-Two-Ns** [comment]
@elb3k there is already a SDK feature issue for this https://github.com/temporalio/features/issues/417.
