### ISSUE TITLE
PR 1404 breaks workflowcheck

### ISSUE THREAD

**Issue by aaomidi** [temporalio/sdk-go#1405]
This PR breaks workflow check.

```
workflowcheck ./...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104880200]

goroutine 1015 [running]:
go/types.(*Checker).handleBailout(0x140022fa200, 0x14002407b98)
        /nix/store/2022s0jnrn2iyxjaikfy51w5fvifp38b-go-1.22.0/share/go/src/go/types/check.go:367 +0x9c
panic({0x104a82be0?, 0x104c9fde0?})
        /nix/store/2022s0jnrn2iyxjaikfy51w5fvifp38b-go-1.22.0/share/go/src/runtime/panic.go:770 +0x124
 ```

_Originally posted by @aaomidi in https://github.com/temporalio/sdk-go/issues/1403#issuecomment-1971924339_
            
            
 Made a new issue for visibility since I know closed PRs sometimes don't send notifications

**Comment by cretz** [comment]
This looks like #1382, can you confirm it is because of that PR? Can you try `workflowcheck` from `master` and see if it still occurs?

**Comment by Quinn-With-Two-Ns** [comment]
Pulling the latest workflow check
```
samples-go git:(async-update-sample) ✗ go install go.temporal.io/sdk/contrib/tools/workflowcheck@master           
go: downloading go.temporal.io/sdk/contrib/tools/workflowcheck v0.1.1-0.20240229191239-d9a574d4ffa4
go: downloading go.temporal.io/sdk v1.26.0-rc.3.0.20240229191239-d9a574d4ffa4
```

and running in samples gave no error so I suspect it is https://github.com/temporalio/sdk-go/issues/1382

**Comment by aaomidi** [comment]
Ooops, looks like initially go pulled the wrong versions for me. Sorry `master` works fine!
