### ISSUE TITLE
Calls to worfklowService.GetSystemInfo are not included in the distrubuted trace.

### ISSUE THREAD

**Issue by burnaevk** [temporalio/sdk-go#1406]
## Expected Behavior

We run distributed tracing with OTel and `go.temporal.io/sdk/contrib/opentelemetry` trace / span propagator. We expect to see calls to `worfklowService.GetSystemInfo` made by `loadCapabilities` (https://github.com/temporalio/sdk-go/blob/d9a574d4ffa4f43e4a9ea4e133feeb5fedb0392c/internal/internal_workflow_client.go#L1151) in our distributed trace, as sometimes intermittent network failures may result in this call failing. If this call is not included in the trace, the reason of the failure is not obvious. 

## Actual Behavior

`worfklowService.GetSystemInfo` call is not visible in the parent trace; instead, a new trace is created for this individual call. 

## Cause

https://github.com/temporalio/sdk-go/blob/d9a574d4ffa4f43e4a9ea4e133feeb5fedb0392c/internal/internal_workflow_client.go#L1165 creates a new background context; parent context is not passed to `loadCapabilities` or `ensureInitialized. 

All callers of ensureInitialized have parent context available, except worker (which might've used context.Background() explicitly) 

## Steps to Reproduce the Problem

  1. Set up Temporal SDK client with tracing interceptor

```
	opts := opentelemetry.TracerOptions{}
	tracingInterceptor, err := opentelemetry.NewTracingInterceptor(opts)
	if err != nil {
		return nil, ErrTracing
	}
	c, err := client.NewLazyClient(client.Options{
...
		Interceptors:       []interceptor.ClientInterceptor{tracingInterceptor}
,...
	})
```

  1. Start a new trace in your business logic code and execute an arbitrary SDK call
  1. Check logs / traces for presence of the `worfklowService.GetSystemInfo` call

## Specifications

  - Version: v1.25.1
  - Platform: go sdk

**Comment by cretz** [comment]
This tracer is for high-level Temporal operations, not specific gRPC calls. Many calls on a client may not show up in traces, only high-level interceptable calls (i.e. those at https://pkg.go.dev/go.temporal.io/sdk/internal#ClientOutboundInterceptor). You can use `ConnectionOptions.DialOptions` to add a gRPC tracing interceptor from https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc if you want tracing of actual gRPC calls.

**Comment by cretz** [comment]
:+1: Yes, we should plumb the context through the capabilities loader (it also will allow it to be subject to proper cancellation and such). It probably wasn't originally set because it is a lazy/memoized call so only the first context matters, but we still should I believe.

**Comment by Quinn-With-Two-Ns** [comment]
@cretz I believe this is resolved now since [loadCapabilities](https://github.com/temporalio/sdk-go/blob/master/internal/internal_workflow_client.go#L1216) now takes the context and it is wired up in all possible locations we could.

**Comment by cretz** [comment]
Concur. Closing. @burnaevk - let us know if you still get issues (of course `go.temporal.io/sdk/contrib/opentelemetry` does not instrument the client, but `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc` does).
