### ISSUE TITLE
Support the new versioning API

### ISSUE THREAD

**Issue by antlai-temporal** [temporalio/sdk-go#1420]
**Is your feature request related to a problem? Please describe.**
The versioning API is changing with new abstractions that need to be supported by the Go SDK.

**Comment by cretz** [comment]
@antlai-temporal - does this apply to all SDKs? Maybe an overarching features issue that links to the other SDK issues could be helpful. Or if you're just doing Go first, having that issue so that you can link to the other issues when you create them later would be helpful.
