### ISSUE TITLE
contrib/datadog/v0.3.0 release

### ISSUE THREAD

**Issue by mallsk23** [temporalio/sdk-go#1423]
Hi,

Thank you for the release https://github.com/temporalio/sdk-go/releases/tag/contrib%2Fdatadog%2Fv0.2.0 which does away with the broken dependency:

```
#25 4.314 go: go.temporal.io/sdk/contrib/datadog@v0.1.0 requires
#25 4.314 	gopkg.in/DataDog/dd-trace-go.v1@v1.42.0 requires
#25 4.314 	github.com/99designs/gqlgen@v0.14.0 requires
#25 4.314 	sourcegraph.com/sourcegraph/appdash-data@v0.0.0-20151005[221](https://github.com/myorg/myrepo/actions/runs/2257091395/job/19770439394#step:6:223)446-73f23eafcf67: unrecognized import path "sourcegraph.com/sourcegraph/appdash-data": reading https://sourcegraph.com/sourcegraph/appdash-data?go-get=1: 404 Not Found
```

The `contrib/datadog/v0.2.0` release itself does contain a reference to the retracted `go.temporal.io/api v1.26.1`:
* https://github.com/temporalio/sdk-go/blob/cb1d35e7223a608d1e083b5faf1b2e704802544e/contrib/datadog/go.mod#L40
* https://github.com/temporalio/api-go/blob/5777bb90676c125ee6e634236f86c0a14391a606/go.mod#L29

Would it be possible to release a `contrib/datadog/v0.3.0` version which no longer depends on the retracted `go.temporal.io/api v1.26.1`?

**Comment by mallsk23** [comment]
cc @Quinn-With-Two-Ns is this something you could take a look at? 🙏

**Comment by mallsk23** [comment]
Or @lminaudier is this something you could help with?

(tagging folks that have tagged a release recently or contributed to `contrib/datadog`)

**Comment by Quinn-With-Two-Ns** [comment]
Hi @mallsk23, yes we can tag another release, but i'll note you can just use a later version of the `api` or use  the latest `sdk` which will do that automatically.

**Comment by mallsk23** [comment]
Thank you @Quinn-With-Two-Ns - will keep an eye out for the `contrib/datadog/v0.3.0` tag

**Comment by mallsk23** [comment]
Apologies for the repeat tag @Quinn-With-Two-Ns as I meant to ask previously, would you have a sense as to when the `contrib/datadog/v0.3.0` tag will be available?

**Comment by Quinn-With-Two-Ns** [comment]
I would expect Monday

**Comment by mallsk23** [comment]
Thank you @Quinn-With-Two-Ns - do you think `contrib/datadog/v0.3.0` will be released today?

**Comment by Quinn-With-Two-Ns** [comment]
Published a new release https://pkg.go.dev/go.temporal.io/sdk/contrib/datadog@v0.3.0/tracing

**Comment by mallsk23** [comment]
Appreciate the release!
