### ISSUE TITLE
temporal_workflow_task_execution_failed not emitted on replay

### ISSUE THREAD

**Issue by codemonkeycxy** [temporalio/sdk-go#1441]
## Expected Behavior
We rely on `temporal_workflow_task_execution_failed` metric to alert us on potential workflow non-determinism errors. We expect this metric to be emitted when closed workflow is replayed

## Actual Behavior
The metric is not emitted when the closed workflow is replayed

## Steps to Reproduce the Problem

  1. Run a workflow and wait for completion
  1. Update worker with a non-deterministic change
  1. Query the completed workflow and `temporal_workflow_task_execution_failed` is not emitted

## Specifications

  - Version: v1.26.0
  - Platform:

**Comment by yuandrew** [comment]
@codemonkeycxy I've confirmed this hits on 1.26.0. Going off of tip of tree, this seems to be resolved and the metric emits correctly. Is this still an issue for you, or were you able to upgrade your SDK version to ingest the fix?
