### ISSUE TITLE
temporal_worker_task_slots_available only reports workflow slots when using opentelemetry metrics handler

### ISSUE THREAD

**Issue by antmendoza** [temporalio/sdk-go#1477]
## Expected Behavior
SDK should report the [slots available](https://docs.temporal.io/references/sdk-metrics#worker_task_slots_available) for workflow, activity and local activity worker 

it works as expected when the metrics handler is tally https://github.com/temporalio/samples-go/blob/main/metrics/worker/main.go#L18-L24 

## Actual Behavior
Using the opentelemetry metrics handler 

```
	exp, err := otlpmetrichttp.New(ctx, otlpmetrichttp.WithEndpointURL("http://localhost:4318"))
	if err != nil {
		panic(err)
	}
	meterProvider := metric.NewMeterProvider(metric.WithReader(
		metric.NewPeriodicReader(exp, metric.WithInterval(1*time.Second)),
	))
	handler := opentelemetry.NewMetricsHandler(
		opentelemetry.MetricsHandlerOptions{
			Meter: meterProvider.Meter("temporal-sdk-go"),
		},
	)

```
the SDK only reports slots available for `worker_type="WorkflowWorker"`

![Screenshot 2024-05-17 at 17 22 44](https://github.com/temporalio/sdk-go/assets/514932/e636bea2-5478-45b1-8c8f-48fc67887537)

Other metrics that have different values for workflow_type seem ok. 

![Screenshot 2024-05-17 at 17 22 27](https://github.com/temporalio/sdk-go/assets/514932/9e0825d1-ad8b-4f85-a9c8-7970c9875783)

You can find a repro here 

https://github.com/antmendoza/my-temporal-pocs/tree/main/go/_5888

```
go.temporal.io/api v1.33.0
go.temporal.io/sdk v1.26.1
go.temporal.io/sdk/contrib/opentelemetry v0.5.0

```

**Comment by Quinn-With-Two-Ns** [comment]
This appears to be a regression or at least change in behaviour of the [OTEL Go SDK](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric) testing with version `1.21.0` then `temporal_worker_task_slots_available` is reported correctly, but testing with `1.26.0` it is not. I have a work around for our integration and will need to open up and issue with the OTEL Go SDK if this is intentional or not.
