### ISSUE TITLE
Race in Register...WithOptions due to un-protected map read

### ISSUE THREAD

**Issue by Groxx** [temporalio/sdk-go#149]
https://github.com/temporalio/temporal-go-sdk/blob/09ced59198a7e5a402ba463a8d11f2952c34dd5e/internal/internal_worker.go#L607

Same core issue as the parent-project: https://github.com/uber-go/cadence-client/issues/979

**Comment by Sushisource** [comment]
Issue is stale - map access is properly protected by a map now.
