### ISSUE TITLE
Temporal Opentelemetry interceptor to use (and export) new temporal header Carrier interface

### ISSUE THREAD

**Issue by mcbadger88** [temporalio/sdk-go#1535]
**Is your feature request related to a problem? Please describe.**
When writing our own custom interceptor, we would like to be able to load/extract Opentelemetry data into the temporal headers using a common function that the temporal interceptor uses. This way we are guaranteed to get trace context propagation even if some components are using temporal's own interceptor vs some are using our custom interceptor.

**Describe the solution you'd like**
- Add a "Carrier" implementation that parses/loads into the temporal headers (e.g. [PR](https://github.com/temporalio/sdk-go/pull/1534))
- Export it for other libraries to use
- Use it in the temporal interceptors ([here](https://github.com/temporalio/sdk-go/blob/master/contrib/opentelemetry/tracing_interceptor.go#L146.)) From what I can tell this will require some small refactoring of the parent function too ([relevant comment](https://github.com/temporalio/sdk-go/pull/1534#discussion_r1663437892))

**Describe alternatives you've considered**
- Define the carrier locally to our private enterprise product. (we currently do this)
- Add to the opentelemetry contrib repo (they advise against this as the code has temporal dependency and is more reliably maintained close to its relevant repository)
- Make my own opensource library (do not have resources to maintain, also my company are not allowed to use personal or untrusted libraries)

**Additional context**
Tagging some of the authors who may have context or pointers, if I have the wrong people please let me know how best to tag the temporal opentelemetry experts. Appreciate your thoughts! @cretz @jvonfricken 

This is an issue raised off the back of some discussions in this PR https://github.com/temporalio/sdk-go/pull/1534, apologies that I did not see the comment to raise an issue first until I had already raised it.

**Comment by cretz** [comment]
I see @Quinn-With-Two-Ns is already looking at the PR, will defer to him. In general while Temporal has an interceptor that injects exact span carrier information, we encourage users to write their own interceptors to do what they need if they need something beyond that. We can discuss options on the OTel interceptor if it needs to have something configured.

**Comment by Quinn-With-Two-Ns** [comment]
Marking as closed based on the discussion in the PR
