### ISSUE TITLE
Customize buckets per metric

### ISSUE THREAD

**Issue by Shubhamurkade** [temporalio/sdk-go#1549]
**Is your feature request related to a problem? Please describe.**
I would like to customize the buckets per metric. The only way supported right now is with Tally, which will customize the buckets for all the metrics.

Please refer to the discussion on [this](https://community.temporal.io/t/increase-bucket-size-of-metrics-in-golang/12758) thread for more context. 

**Describe the solution you'd like**
Say, I'm using a metric `temporal_activity_execution_latency_bucket` and would like more buckets than the default number of buckets. Right now, it's not possible to increase the number of buckets only for this metric. The solution linked in the thread referenced in the previous section will increase the number of buckets for all the metrics. I would like to change the buckets only for the particular metric.

**Describe alternatives you've considered**
The only alternative will change the buckets for all metrics which isn't preferable.

**Additional context**
NA

**Comment by Quinn-With-Two-Ns** [comment]
`temporal_activity_execution_latency_bucket ` is a Timer,  in Tally I believe the only way to configure Timer histogram is to use `Reporter.RegisterTimer`

**Comment by Quinn-With-Two-Ns** [comment]
Closing as this configuration is part of the scope
