### ISSUE TITLE
Typed search attributes issue with SignalWithStartWorkflow

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-go#1551]
Typed search attributes defined in workflow options, for example:

        workflowOptions := client.StartWorkflowOptions{
		ID:                    "typed-search_attributes_test",
		TaskQueue:             "typed-search-attributes",
		TypedSearchAttributes: temporal.NewSearchAttributes(typedsearchattributes.CustomIntKey.ValueSet(1)),
	}

are propagated fine via ExecuteWorkflow but are missed to be propagated to new execution via SignalWithStartWorkflow
(when no workflow with workflow id exists, so new execution is created)

**Comment by cretz** [comment]
Thanks, I think this is a bug. https://github.com/temporalio/sdk-go/blob/81a76b1623de784f909a8e4c9fae647b92f5621f/internal/internal_workflow_client.go#L1713 is supposed to look like https://github.com/temporalio/sdk-go/blob/81a76b1623de784f909a8e4c9fae647b92f5621f/internal/internal_workflow_client.go#L1572
