### ISSUE TITLE
Suppor Temporal Cloud API Keys in Go SDK client

### ISSUE THREAD

**Issue by tomahawk28** [temporalio/sdk-go#1570]
Is it possible to use API keys in Temporal Cloud to use in Go SDK client? https://docs.temporal.io/cloud/api-keys

Currently, you are only supporting mTLS connection from Go SDK client. 

> When you connect to [Temporal Cloud](https://docs.temporal.io/cloud), you need to provide additional connection and client options that include the following:
> - The [Temporal Cloud Namespace Id](https://docs.temporal.io/cloud/namespaces#temporal-cloud-namespace-id).
> - The [Namespace's gRPC endpoint](https://docs.temporal.io/cloud/namespaces#temporal-cloud-grpc-endpoint). An endpoint listing is available at the [Temporal Cloud Website](https://cloud.temporal.io/namespaces) on each Namespace detail page. The endpoint contains the Namespace Id and port.
> - mTLS CA certificate.
> - mTLS private key.

https://docs.temporal.io/develop/go/temporal-clients#connect-to-temporal-cloud

**Comment by Quinn-With-Two-Ns** [comment]
API keys are supported by the Go SDK [NewAPIKeyStaticCredentials](https://pkg.go.dev/go.temporal.io/sdk@v1.28.1/internal#NewAPIKeyStaticCredentials) can be passed to `Credentials` in [ClientOptions](https://pkg.go.dev/go.temporal.io/sdk@v1.28.1/internal#ClientOptions)

**Comment by Quinn-With-Two-Ns** [comment]
For cloud API keys your connection options would be something like this.
```
clientOptions := client.Options{
		HostPort:  <endpoint>,
		Namespace: <namespace.accountid>,
		Credentials: client.NewAPIKeyStaticCredentials(<APIKey>),
		ConnectionOptions: client.ConnectionOptions{
			DialOptions: []grpc.DialOption{
				grpc.WithUnaryInterceptor(
					func(ctx context.Context, method string, req any, reply any, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
						return invoker(
							metadata.AppendToOutgoingContext(ctx, "temporal-namespace", <namespace.accountid>),
							method,
							req,
							reply,
							cc,
							opts...,
						)
					},
				),
			},
		},
	}

	c, err := client.Dial(clientOptions)
```

**Comment by tomahawk28** [comment]
Thanks, I tried your suggestion with the temporal namespace `https://cloud.temporal.io/namespaces/molen-dev.l2c4n/workflows`. 
However, I still get this message. 
```
2024/07/29 17:35:55 Unable to create client failed reaching server: last connection error: connection error: desc = "error reading server preface: read tcp 172.20.10.2:62658->52.14.206.101:7233: read: connection reset by peer"
```

Perhaps I need to change the auth type for this namespace? 

```
 tcld n am get -n molen-dev.l2c4n                                                                                                                                [17:36:54]
mtls
```

If I need to ask temporal cloud directly, please let me know!

**Comment by cretz** [comment]
API keys are still experimental for cloud and most cloud namespaces still use mTLS based authentication. If you want to enable API key support for your cloud account, please open a cloud ticket.
