### ISSUE TITLE
gRPC code "Unavailable" is being reported as "Unknown" by temporal SDK Client

### ISSUE THREAD

**Issue by guritinvda** [temporalio/sdk-go#1573]
## Expected Behavior
Correct gRPC code should be recorded & returned.

## Actual Behavior
gRPC code "Unavailable" is being reported as "Unknown"

## Steps to Reproduce the Problem

  1. Run a temporal server that returns Http 503 Unavailable gRPC code
  2. Verify that the correct code is being received via another client. In my case, I verified in python, a generic gRPC client & with postman. They all confirmed the "Unavailable" code.
 Sample code:
```
func testRawGrpc() {
	var grpcClient *grpc.ClientConn
	var err error
	creds := credentials.NewTLS(&tls.Config{})
	grpcClient, err = grpc.Dial("<host:port>", grpc.WithTransportCredentials(creds), grpc.WithMaxMsgSize(1*1024*1024), grpc.WithTimeout(10*time.Second))
	
	defer grpcClient.Close()

	if err != nil {
		log.Printf("unable to create client: %#v\n", err)
		return
	}

	req := workflowservice.ListNamespacesRequest{
		PageSize:        100,
		NamespaceFilter: &namespace.NamespaceFilter{IncludeDeleted: true},
	}

	resp := workflowservice.ListNamespacesResponse{}

	err = grpcClient.Invoke(context.Background(), "/temporal.api.workflowservice.v1.WorkflowService/ListNamespaces", &req, &resp)
	if err != nil {
		log.Printf("unable to ListNamespaces: %#v\n", err)
		grpcErr, _ := status.FromError(err)
		log.Printf("grpcMessage=%v, grpcCode=%v\n", grpcErr.Message(), grpcErr.Code())
		return
	}
	log.Println("ListNamespaces result:", &resp)
}
```
Notice in the logs:
```
...
grpcMessage=no healthy upstream, grpcCode=Unavailable
...
```
  3. Now, try the same with the sdk client
  
```
func testTemporalClient() {
	temporalConnectionOpts := client.ConnectionOptions{
		TLS: &tls.Config{},
	}
	temporalClientOpts := client.Options{
		HostPort:          "<host:port>",
		Namespace:         "default",
		ConnectionOptions: temporalConnectionOpts,
	}
	c, err := client.Dial(temporalClientOpts)
	if err != nil {
		grpcErr, _ := status.FromError(err)
		fmt.Printf("grpcMessage=%v, grpcCode=%v\n", grpcErr.Message(), grpcErr.Code())
		log.Println("Failed to create temporal client:", err)
		return
	}
	defer c.Close()

	req := workflowservice.ListNamespacesRequest{
		PageSize:        100,
		NamespaceFilter: &namespace.NamespaceFilter{IncludeDeleted: true},
	}

	resp, err := c.WorkflowService().ListNamespaces(context.Background(), &req)
	if err != nil {
		log.Println("Unable to ListNamespaces", err)
		grpcErr, _ := status.FromError(err)
		log.Printf("grpcMessage=%v, grpcCode=%v\n", grpcErr.Message(), grpcErr.Code())
		return
	}
	log.Println("ListNamespaces result:", resp)
}
```
Notice in the logs:
```
...
grpcMessage=failed reaching server: no healthy upstream, grpcCode=Unknown
...
```

## Specifications

  - Version: Observed in go-SDK versions v1.24.0, v1.25.0 & v1.28.1
  - Platform: Linux

**Comment by Quinn-With-Two-Ns** [comment]
In your second example is the error coming from `c, err := client.Dial(temporalClientOpts)`?

**Comment by guritinvda** [comment]
> In your second example is the error coming from `c, err := client.Dial(temporalClientOpts)`?

Yes. That is when the System Health Check is getting triggered & hence the error.

**Comment by Quinn-With-Two-Ns** [comment]
The Go SDK is not changing the status code of any errors. `status.FromError(err)` is returning `UNKNOWN` because it encounters an incompatible error type. If you checked the second parameter you would see OK is false indicating the error is not compatible with `status`. The Go SDK does not return raw grpc errors, it returns [serviceerrors](https://pkg.go.dev/go.temporal.io/api@v1.36.0/serviceerror) if you want to get the underlying status you can use `ToStatus`

**Comment by guritinvda** [comment]
Good point. My bad for missing that. 

```
func testTemporalClient() {
	temporalConnectionOpts := client.ConnectionOptions{
		TLS: &tls.Config{},
	}
	temporalClientOpts := client.Options{
		HostPort:          "<host:port>",
		Namespace:         "default",
		ConnectionOptions: temporalConnectionOpts,
	}
	c, err := client.Dial(temporalClientOpts)
	if err != nil {
		grpcErr := serviceerror.ToStatus(err)
		fmt.Printf("grpcMessage=%s, grpcCode=%s\n", grpcErr.Message(), grpcErr.Code())
		fmt.Println("Failed to create temporal client:", err)
		return
	}
	defer c.Close()
}
```
This still prints:
```
...
grpcMessage=failed reaching server: no healthy upstream, grpcCode=Unknown
Failed to create temporal client: failed reaching server: no healthy upstream
...
```
What am I missing? Am I wrong to expect "Unavailable" is the logs above?

**Comment by guritinvda** [comment]
@Quinn-With-Two-Ns can you please reopen this?

**Comment by cretz** [comment]
> Am I wrong to expect "Unavailable" is the logs above?

Maybe so. I think not even be able to establish connection is not a gRPC RPC error, it's a network error, so I wouldn't expect it to have a gRPC status code.

**Comment by cretz** [comment]
An HTTP status code of 503 unavailable is not the same as a gRPC status code of unavailable (gRPC status coeds do not have HTTP numeric status codes). Can you show what type `err` is in your snippet? Also, can you confirm what https://pkg.go.dev/google.golang.org/grpc/status#FromError returns for this error?

**Comment by guritinvda** [comment]
> An HTTP status code of 503 unavailable is not the same as a gRPC status code of unavailable (gRPC status codes do not have HTTP numeric status codes). Granted some clients in some languages may reuse the gRPC errors pre-gRPC connectivity.

I don't quite follow what you mean here. Here are the codes: https://pkg.go.dev/google.golang.org/grpc/codes#Code .

> Can you show what type err is in your snippet? 

```
c, err := client.Dial(temporalClientOpts)
vs
grpcErr := serviceerror.ToStatus(err)
```
Does that answer your question?

> https://pkg.go.dev/google.golang.org/grpc/status#FromError returns for this error? 

@cretz please see the function: `testRawGrpc` in the description of this issue.  
I can confirm that `FromError` returns the "Unavailable" code as expected.

> We want to make sure we match what Go gRPC does here, so maybe we're wrapping incorrectly compared to pure gRPC use.

Agreed. Exactly what this issue is about.

**Comment by Quinn-With-Two-Ns** [comment]
I can confirm the Go SDK is correctly wrapping the error. I can confirm if a grpc server returns `Unavailable` for `GetSystemInfo` the SDK client will return the correct status.

```
func TestUnavailable(t *testing.T) {
	// Start a server that always returns an error on get system info
	srv, err := startTestGRPCServer()
	require.NoError(t, err)
	defer srv.Stop()
	srv.getSystemInfoResponseError = status.New(codes.Unavailable, "some server failure").Err()

	// Confirm DialClient returns unavailable
	_, err = DialClient(context.Background(), ClientOptions{HostPort: srv.addr})
	status := serviceerror.ToStatus(err)
	require.Equal(t, codes.Unavailable, status.Code())
}

func TestBadHostUnavailable(t *testing.T) {
	// Confirm DialClient returns unavailable
	_, err := DialClient(context.Background(), ClientOptions{HostPort: "localhost:12345"})
	status := serviceerror.ToStatus(err)
	require.Equal(t, codes.Unavailable, status.Code())
}
```

**Comment by guritinvda** [comment]
@Quinn-With-Two-Ns your tests fail in v1.24.0 (please see screenshot). I did not test against other released versions but they succeed against the `master` branch of this repo. 

![image](https://github.com/user-attachments/assets/884f7674-c601-446b-bea8-a0e91e74d04c)

Since it worked against the latest code and that nothing in the diff stood out to me as what may have "fixed" the issue. , I am happy to leave this issue closed & wait for the next release. 
As always, appreciate the quick responses & your time!
