### ISSUE TITLE
Workflow-init support docs

### ISSUE THREAD

**Issue by drewhoskins-temporal** [temporalio/sdk-go#1576]
We should have a method that's guaranteed to initialize before signals and updates come in so handlers can use initialized values.

**Comment by Quinn-With-Two-Ns** [comment]
@cretz Can we close this issue? I don't think Go SDK needs any changes here if we want to support struct based workflows or improve docs I think those should be tracked separately

**Comment by cretz** [comment]
I do think we can, let's confirm with team first though (same for TypeScript).
