### ISSUE TITLE
Activity failure is not encrypted with the key set to the context propagator, used to encrypt workflow and activity payload

### ISSUE THREAD

**Issue by antmendoza** [temporalio/sdk-go#1587]
Using [this code](https://github.com/temporalio/samples-go/tree/main/encryption) as example, I have set the Failure converter with EncodeCommonAttributes to encrypt failures 

```
c, err := client.Dial(client.Options{
...
...
FailureConverter: temporal.NewDefaultFailureConverter(temporal.DefaultFailureConverterOptions{
	EncodeCommonAttributes: true,
	DataConverter:          dataConverter,
}),
```

workflow and activity payload are encrypted with the [key set to the context propagator](https://github.com/temporalio/samples-go/blob/main/encryption/starter/main.go#L55-L57) but not failures. 

## Expected Behavior

Failure attributes should be encrypted

## Actual Behavior

Failure attributes are not encrypted (or are encrypted with a different key) 

## Steps to Reproduce the Problem

There is a repro [here](https://github.com/antmendoza/my-temporal-pocs/tree/main/go/_6715/src) and 
the workflow history that it produces where [encryption-key-id is empty](https://github.com/antmendoza/my-temporal-pocs/blob/main/go/_6715/src/6a8e27d0-2d12-4c24-b960-de993137c587_events.json#L175-L177)

**Comment by Quinn-With-Two-Ns** [comment]
Ad discussed offline this is not excepted to work because failure converters cannot be context aware. I opened up an issue to add support to failure converters https://github.com/temporalio/sdk-go/issues/1609
