### ISSUE TITLE
GetSystemInfo - panic

### ISSUE THREAD

**Issue by longshanxu** [temporalio/sdk-go#1611]
## Expected Behavior
temporal go sdk 1.28.1 

## Actual Behavior
GetSystemInfo - panic

## Steps to Reproduce the Problem

  1. temporalClient, err := client.Dial(client.Options{})

## Specifications

  - Version: temporal go sdk 1.28.1 
  - Platform: windows

ps:
`	// grpcCtx, cancel := newGRPCContext(ctx, grpcTimeout(getSystemInfoTimeout))
	// defer cancel()
	resp, err := wc.workflowService.GetSystemInfo(ctx, &workflowservice.GetSystemInfoRequest{})`
	
**If I annotate these two lines of code and pass in ctx, it works. If I use timeout on ctx, I panic. What is the reason for this?**

**Comment by cretz** [comment]
> Steps to Reproduce the Problem
> temporalClient, err := client.Dial(client.Options{})

Our most basic samples use `client.Dial(client.Options{})` e.g. https://github.com/temporalio/samples-go/tree/main/helloworld. Can you confirm that sample works for you?

**Comment by longshanxu** [comment]
> > Steps to Reproduce the Problem
> > temporalClient, err := client.Dial(client.Options{})
> 
> Our most basic samples use `client.Dial(client.Options{})` e.g. https://github.com/temporalio/samples-go/tree/main/helloworld. Can you confirm that sample works for you?

I found the problem, using client.Dial(client.Options{}) to set localhost:7233 by default, timed out under windows. The timeout must be greater than 10 seconds, or use 127.0.0.1:7233

thanks for your reply!
