### ISSUE TITLE
Workflow Update in Test Environment should dedup updates by ID

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/sdk-go#1638]
## Expected Behavior
Workflow Updates in Test Environment behave like Updates against a real server and either dupes for fails if an update with a duplicate ID is sent

## Actual Behavior
Test Environment accepts update with duplicate ID

**Comment by yuandrew** [comment]
Is the ID here referring to `UpdateID` from the `UpdateClientWorkflow` options? I'm working through some other failures in setting up this workflow, want to double check I'm going down the right path.

**Comment by Quinn-With-Two-Ns** [comment]
>Is the ID here referring to UpdateID from the UpdateClientWorkflow options

Conceptually yes, but the test environment does not use a client since it is all in memory in the same process

Here is an example of sending an update with the test environment https://github.com/temporalio/samples-go/blob/main/reqrespupdate/workflow_test.go#L41

**Comment by yuandrew** [comment]
I'm playing around with the [update go sample](https://github.com/temporalio/samples-go/tree/main/update), and when I add `UpdateID: we.GetID()` to the `UpdateWorkflowOptions`, I'm not seeing the real server throw any error. Shouldn't this update fail?

**Comment by Quinn-With-Two-Ns** [comment]
> Shouldn't this update fail?

No, the real server will dedup the update request by the update ID
