### ISSUE TITLE
Update Godoc for `internal` structs/funcs to clarify the package they are exposed under

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#1681]
**Describe the solution you'd like**

At least for all non-obvious `internal` structs/funcs, mention in their Godoc the package they are exposed/aliased at.

**Comment by yuandrew** [comment]
@cretz what's considered "non-obvious"? i.e. GetActivityInfo -> GetInfo obvious enough?

**Comment by Quinn-With-Two-Ns** [comment]
We should probably just document where every exported `internal` structs/funcs is exposed.

**Comment by cretz** [comment]
Yeah, if that's not too much work, that would be ideal. This can probably be done in an automated way via a cmd to the build tooling (e.g. parsing the whole project for aliases that point to internal and confirming the Godoc of internal), but if it is automated, need a check in CI to confirm it was since rerun if something is added.
