### ISSUE TITLE
TestWorkflowEnvironment has non-standard RunID "default-test-run-id"

### ISSUE THREAD

**Issue by askreet** [temporalio/sdk-go#1689]
The below is based on an assumption I have that Run IDs are expected to always be UUIDs provided by the Temporal engine. We've recently been storing records in our database using the Run ID of workflows and our RDBMS's native UUID column type.

Note that I poked around and couldn't find an easy way to override this value in my test case, but if I've missed it please let me know!

## Expected Behavior

The Workflow object obtainable from within an Activity via `activity.GetInfo(ctx)` should return values that reasonably simulate a production Temporal system.

## Actual Behavior

The `info.WorkflowExecution.RunID` field is set to `default-test-run-id`, a non-UUID string.

## Steps to Reproduce the Problem

  1. Create a workflow with one activity, importing the `github.com/google/uuid` package, defined as:

```go
func (a *Activities) MyActivity(ctx context.Context) error {
	info := activity.GetInfo(ctx)

	_, err := uuid.Parse(info.WorkflowExecution.RunID)
	if err != nil {
		return err
	}

	return nil
}
```

  2. Execute the workflow in a TestWorkflowEnvironment.
  3. Observe that the workflow times out as the activity above retries forever with an error about not being able to parse a UUID.

## Specifications

  - Version: SDK v1.25.1
  - Platform: Go v1.22.6 darwin/arm64

**Comment by askreet** [comment]
If I can get some validation of this bug, I'd be willing to contribute one or both of the following fixes:

1. Set this default value to a valid UUID, such as `00000000-0000-0000-0000-000000000000`.
2. Expose a function `SetExecutionRunID` that mutates the workflowInfo similar to [SetContinuedExecutionRunID](https://github.com/temporalio/sdk-go/blob/master/internal/workflow_testsuite.go#L337-L339) ([impl](https://github.com/temporalio/sdk-go/blob/master/internal/internal_workflow_testsuite.go#L384-L386)).

**Comment by askreet** [comment]
I'm more than happy to consider this a bug in my application that I'm storing this as a UUID at all, if that's the consensus.

**Comment by cretz** [comment]
Yes, we do not guarantee the format of a run ID
