### ISSUE TITLE
testsuite context propagation is broken

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-go#190]
## Expected Behavior
Context propagation works during unit tests

## Actual Behavior
The code path that extracts headers from context passed to testWorkflowEnvironment.Execute is not present in the testsuite code.

## Steps to Reproduce the Problem

  1. Run contextpropagator unit test: https://github.com/temporalio/go-samples/blob/c0e2921476b95ad959cb20cc2933ad59784af5ab/ctxpropagation/workflow_test.go#L22

## Specifications

  - Version: 0.26.0 of SDK/Service

**Comment by alexshtin** [comment]
Looks like duplicate of #29.

**Comment by vitarb** [comment]
Closing as dupelicate
