### ISSUE TITLE
Go SDK does not handle two different workflows registered with same function name properly

### ISSUE THREAD

**Issue by mastermanu** [temporalio/sdk-go#197]
Scenario: I had two Workflows in separate packages with the same Workflow entry method called "Run()". I called continueasnew with the function pointer to Workflow1's execution method, and the continueasnew operation resulted in Workflow2 kicking off (!) as a part of Workflow1's execution, which confused the heck out of me. 

I fixed this locally by referencing the friendly workflow name I registered with instead of the function pointer, but: 

1) If two separate workflows in different packages cannot have the same function name, we should ideally be crashing the worker on startup.

2) If this is supposed to be supported behavior, then there is a bug here.

Tested locally against latest Temporal and SDK bits as of 7/16/2020 and reproduces quite easily.

![image](https://user-images.githubusercontent.com/5552381/87704513-5cb70c80-c751-11ea-969d-12dd7d5d4bc4.png)

(Note lines 107 and 115 register two different workflows with same entry method name, which causes the issue)

**Comment by cretz** [comment]
This is the expected behavior of the registration, though it is possible at the time of this issue it may have been broken or otherwise not implemented right. Today it is accepted that the simple function name is used as the name and you have to use the options to override it with a different name. This code should panic if a name is reused unless `DisableAlreadyRegisteredCheck` is explicitly set to true in the options.

**Comment by mastermanu** [comment]
Got it. I was actually registering the workflows with custom names, but then in continue as new, I was referencing the method instead of the custom name, which is why this issue was only caught at run-time vs. panicking on startup.

We may want to document this behavior in the continue-as-new documentation

**Comment by cretz** [comment]
I have also opened #672 to allow disabling of the function name as an alias.

**Comment by Quinn-With-Two-Ns** [comment]
closing as this looks resolved
