### ISSUE TITLE
Unable to get WorkflowExecutionAlreadyStartedError

### ISSUE THREAD

**Issue by olegmedvedev** [temporalio/sdk-go#220]
After migration from Uber Cadence to Temporal.io my internal logics are broken. As I see `StartWorkflow` was removed from interface and `ExecuteWorkflow` consumes error `WorkflowExecutionAlreadyStartedError` and returns existing `WorkflowRun`.

## Expected Behavior

Being able to receive `WorkflowExecutionAlreadyStartedError` on `ExecuteWorkflow` if `ReusePolicy` is `WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY`

## Actual Behavior

Unable to receive `WorkflowExecutionAlreadyStartedError` on `ExecuteWorkflow` if `ReusePolicy` is `WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY`

## Steps to Reproduce the Problem

  1. Execute workflow with `WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY`
  2. Execute workflow with `WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY` with the same workflow id again.
  

## Specifications

  - Version: v0.26.0
  - Platform: linux x86_64

**Comment by arxeiss** [comment]
I just faced a similar issue, but I used the `ReusePolicy` with `WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE`.

When I started the workflow with ID, which was already finished or failed, I got a successful message with the last RunID. But nothing was added to the queue and nothing was run.
