### ISSUE TITLE
Tracer property in WorkerOptions is missing

### ISSUE THREAD

**Issue by jasonsoft** [temporalio/sdk-go#239]
## Expected Behavior
According to document (https://docs.temporal.io/docs/go-tracing), I am looking for `Tracer` property in WorkerOptions.  However, I can't find it.  Is that correct behavior?

 

=== from document ===
The Go client provides distributed tracing support through OpenTracing. Tracing can be configured by providing an opentracing.Tracer implementation in ClientOptions and **WorkerOptions** during client and worker instantiation, respectively. 

## Actual Behavior
No `Tracer` property in `WorkOptions`

https://pkg.go.dev/go.temporal.io/sdk/internal?tab=doc#WorkerOptions

## Specifications

  - Version: 0.29.0
  - Platform:

I am trying to use tracer feature with opentelemetry now.  It seems to me that every span is independent.  I expected all spans should have relationship in one trace.  I was wondering if there was a trace example.  thank you

**Comment by alexshtin** [comment]
Thanks for reporting this, @jasonsoft. Doc is outdated and @cullywakelin will fix it soon. I removed all duplicate options from `WorkerOptions` and move few of them to `ClientOptions`. Now `WorkerOptions` contain only worker specific options and all the rest goes to `ClientOptions`.
It seems we don't have example for tracing in our [samples repo](https://github.com/temporalio/go-samples) and there are no integration tests neither (it would be great if you contribute). For now, I can only suggest you to check [implementation](https://github.com/temporalio/go-sdk/blob/master/internal/tracer.go) and unit tests (https://github.com/temporalio/go-sdk/blob/master/internal/tracer_test.go).

**Comment by nicolasgere** [comment]
> 
> I am trying to use tracer feature with opentelemetry now. It seems to me that every span is independent. I expected all spans should have relationship in one trace. I was wondering if there was a trace example. thank you

I think I'm getting the same issue and if there is a bug, is still there

**Comment by sw-yx** [comment]
@flossypurse should we move this to docs repo?

**Comment by alexshtin** [comment]
Doc at https://docs.temporal.io/docs/go-tracing/ is updated and correct.
There is integration test for context propagators at https://github.com/temporalio/sdk-go/blob/1c882f768532af62cb44e7aad66d156fd46d0724/test/integration_test.go#L777

And I also added end to end sample at https://github.com/temporalio/samples-go/blob/master/ctxpropagation/ with instructions on how to test it locally.

Don't forget to set tracer on all workers and starters (`tctl` doesn't support it).
