### ISSUE TITLE
Add a Registry/WorkerRegistry interface to the worker package

### ISSUE THREAD

**Issue by sagikazarmark** [temporalio/sdk-go#280]
**Is your feature request related to a problem? Please describe.**
When registering workflows/activities in a worker, consumers often don't need the Start and Stop methods of the worker interface.

**Describe the solution you'd like**
Define a `Registry` or a `WorkerRegistry` interface in the worker package with the registration methods and embed it in the worker interface. Consumers can use this interface instead of the `Worker` interface. Although in Go consumers usually own interfaces, in this case the interface and the use case is well-defined by the provider, so it makes sense to define it in the worker package.

**Comment by sagikazarmark** [comment]
Further thinking about this, I'd also consider splitting the methods up to `WorkflowRegistry` and `ActivityRegistry`.

**Comment by mfateev** [comment]
PR is welcome
