### ISSUE TITLE
Add the ability to register local activities only

### ISSUE THREAD

**Issue by wolfy-j** [temporalio/sdk-go#284]
**Is your feature request related to a problem? Please describe.**
Sometimes it makes sense to isolate workflow workers from the rest of business logic. However, local activites do not fit this mix. It will be useful to be able to register local activities only without enabling task queue activity consumption.

**Describe the solution you'd like**
It will be useful to be able to register local activities only without enabling task queue activity consumption.

**Describe alternatives you've considered**
none

**Comment by vitarb** [comment]
From what I understand your concern is that in order to invoke a local activity you have to register activity with the worker and that would result in worker polling on activity task queue? What problems do you see with the current approach? Can you provide a use case when current behavior would be problematic?

**Comment by mfateev** [comment]
@vitarb It is needed for PHP SDK worker.

**Comment by vitarb** [comment]
Makes sense, we can add an option, something like `worker.Options.DisableActivityPoller` which, if set, would override our default logic and disable activity poller.

**Comment by wolfy-j** [comment]
That will work!

**Comment by vitarb** [comment]
We should be able to do this in the next few weeks, stay tuned.

**Comment by vitarb** [comment]
Change is merged in, it should go out in the next 1.0.4 release soon.

**Comment by vitarb** [comment]
Addressed in both go and java SDKs, new `LocalActivityWorkerOnly` worker option is available, which if set to true would turn off regular activity polling.
