### ISSUE TITLE
[doc] Should remove all activity.Register in document

### ISSUE THREAD

**Issue by giautm** [temporalio/sdk-go#292]
I found three places mention about activity.Register. https://github.com/temporalio/sdk-go/pull/41

https://github.com/temporalio/sdk-go/blob/88b35b585712dcbeb3e493036b32f8a5baecd91c/activity/doc.go#L45-L47

https://github.com/temporalio/sdk-go/blob/88b35b585712dcbeb3e493036b32f8a5baecd91c/activity/doc.go#L184-L188

https://github.com/temporalio/sdk-go/blob/88b35b585712dcbeb3e493036b32f8a5baecd91c/worker/worker.go#L121

**Comment by flossypurse** [comment]
Addressing these issues here: https://github.com/temporalio/sdk-go/pull/306

**Comment by Sushisource** [comment]
Was fixed in #306
