### ISSUE TITLE
Registering workflows by struct

### ISSUE THREAD

**Issue by shaunco** [temporalio/sdk-go#328]
**Is your feature request related to a problem? Please describe.**
For projects that have a large number of workflows, especially for CRUD-like functions across multiple topics, name collisions start to happen quickly. To work around this, we scope functions in go packages, such as `mypackage1.Create` and `mypackage2.Create`, but when we call `RegisterWorkflow`, the [internal code](https://github.com/temporalio/sdk-go/blob/ca9a4c12b25cc23546b9876b4a86acaf024df81c/internal/internal_worker.go#L495) only uses the function name with none of the package name pieces included, and those the two are both stored as `Create` and the SDK panics with `workflow name "Create" is already registered`.

**Describe the solution you'd like**
It would be really nice if we could register structs that contain exported workflow functions, in the same manner that we can currently register a collection of activities via a struct pointer.

**Describe alternatives you've considered**
While I know we can use aliases, doing so complicates executing workflows.

**Comment by shaunco** [comment]
I went down the alias path. Would still be nice to have workflow registration by struct, but no rush.

**Comment by mfateev** [comment]
The recommended solution is to use `worker.RegisterWorkflowWithOptions` the name specified through `RegisterWorkflowOptions.Name` is used as a prefix to the name.

**Comment by mfateev** [comment]
Registering workflows by struct is not something we plan to support as it can be very confusing to the new users. The reason is that workflows are expected to be stateless.

**Comment by shaunco** [comment]
Fair enough.
