### ISSUE TITLE
Add deterministic range over map helper

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-go#359]
**Is your feature request related to a problem? Please describe.**
Go built in range over map is not deterministic. The workaround has to be implemented by each user.

**Describe the solution you'd like**
Some helper to support deterministic iteration over map.

**Comment by Quinn-With-Two-Ns** [comment]
Was deferring this until [range over func](https://github.com/golang/go/wiki/RangefuncExperiment) support was added in Go 1.22, but looks like that didn't make that release.
