### ISSUE TITLE
[Bug] Local Activities fail to deserialize at gRPC if return type is error

### ISSUE THREAD

**Issue by vavsab** [temporalio/sdk-go#365]
**Describe the bug**
I'm getting error in temporal-web while trying to view workflow that contains local activities without return parameters.

**To Reproduce**
1. I took an example from the [Go getting started guide](https://docs.temporal.io/docs/go-run-your-first-app?_ga=2.131416204.2088473206.1612883624-657308480.1606319036) and changed it to use Local Activities.
![image](https://user-images.githubusercontent.com/10233442/107386506-96d86900-6afc-11eb-954c-9a0b54d58b83.png)
2. After I run this sample, I get “13 INTERNAL: Failed to parse server response” while viewing the workflow inside of temporal-web
![image](https://user-images.githubusercontent.com/10233442/107386586-a9eb3900-6afc-11eb-8c7d-ca1f04d4b549.png)
3. I also get this error inside of temporal-web docker container
![image](https://user-images.githubusercontent.com/10233442/107386633-b66f9180-6afc-11eb-8ec0-188f95082004.png)

**Expected behavior**
I can view such workflows without getting an error

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Temporal Web Version: 1.5.2 (Docker) 
 - Temporal Version: 1.6.0 (Docker)
 
 **Additional details**
1. I also noticed that as soon as I add at least an empty return result to the activities, it starts to open without any error
 
![image](https://user-images.githubusercontent.com/10233442/107386949-077f8580-6afd-11eb-99a3-76a0ec3cb4fa.png)
2. I have started a [discussion in community](https://community.temporal.io/t/error-while-viewing-workflow-that-contains-local-activities-13-internal-failed-to-parse-server-response/1378)

**Comment by feedmeapples** [comment]
- for quick fix: Addressing this in sdk-go
- additional fix to prevent similar cases in future: Filing a bug to @grpc/grpc-js
