### ISSUE TITLE
Remove path prefix from activity and workflow type names

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-go#38]
This is current name of a workflow:

`go.temporal.io/temporal/internal.splitJoinActivityWorkflow`

This make moving workflows between directories hard and forces specifying string name for every workflow.

The proposal is to change it to `splitJoinActivityWorkflow`

**Comment by samarabbas** [comment]
Add capitalization of first letter.  Already fixed.  Verify and close.
