### ISSUE TITLE
Add validation of input addr during client creation

### ISSUE THREAD

**Issue by wxing1292** [temporalio/sdk-go#389]
## Expected Behavior
https://github.com/temporalio/sdk-go/blob/555111c79989bec4448edb018ce8a3f48cb98b09/internal/client.go#L329
host port should be validated during client creation.

## Actual Behavior
no validation, the error will only be returned when creating a connection
```
last connection error: connection error: desc = "transport: Error while dialing dial tcp: address 172.22.199.91: missing port in address
```

## Specifications

  - Version: 1.5.1
  - Platform:

**Comment by Quinn-With-Two-Ns** [comment]
closing as the original PR was closed because resolution is configurable
