### ISSUE TITLE
Setting deadlock detection timeouts?

### ISSUE THREAD

**Issue by shaunco** [temporalio/sdk-go#404]
**Is your feature request related to a problem? Please describe.**
We had code that was calling `rsa.GenerateKey(rand.Reader, 4096)` in a `workflow.SideEffect` call. Generating a 4096 RSA key sometimes takes >1 second, so the deadlock detection kills the workflow and starts it over.

**Describe the solution you'd like**
It would be great to have a few functions to give hints to the deadlock detection so that I could do something like this before calling an API that takes a bit longer than a second:
```go
  ctx.SetDeadlockTimeout(seconds)
  defer ctx.ResetDeadlockTimeout()
  rsa.GenerateKey(rand.Reader, 4096)
```

Similarly, something like `ctx.Alive()` might be helpful in loops.

**Describe alternatives you've considered**
Currently we just use TEMPORAL_DEBUG for the service that makes this `rsa.GenerateKey` call... obviously this is not ideal.

**Comment by mfateev** [comment]
I would recommend using local activities for such expensive operations.

**Comment by shaunco** [comment]
> I would recommend using local activities for such expensive operations.

Even in a local activity, the `GenerateKey` function takes long enough to trigger the deadlock detection. We still need a way to give Temporal a hint to extend the deadlock timeout in some scenarios.
