### ISSUE TITLE
Activity Retry Policy is ignored in workflow tests

### ISSUE THREAD

**Issue by ingyamilmolinar** [temporalio/sdk-go#406]
## Expected Behavior
Workflow testing environment should respect the activity retry policy set in the workflow.Context.

## Actual Behavior
Workflow testing environment is not retrying activities when it should based on the retry policy.

## Steps to Reproduce the Problem
1. Register the following workflow and activity:
```
func Workflow(ctx workflow.Context) error {
ao := workflow.ActivityOptions{
StartToCloseTimeout: 1 * time.Second,
// NOTE: using default retry policy which is unlimited retries
}
ctx = workflow.WithActivityOptions(ctx, ao)

future := workflow.ExecuteActivity(ctx, Activity)
if err := future.Get(ctx, nil); err != nil {
return err
}
return nil
}

func Activity(ctx context.Context) error {
return nil
}
```
2. Write a test for your workflow and mock the activity to return an error once:
```
env.OnActivity(Activity, mock.Anything).Return(errors.New("Error occurred")).Once()
```
3. Verify that the workflow error is nil in your test (because the activity should be retried once after failing):
```
var wts testsuite.WorkflowTestSuite
env = wts.NewTestWorkflowEnvironment()
env.OnActivity(Activity, mock.Anything).Return(errors.New("Error occurred")).Once()

env.ExecuteWorkflow(Workflow)

Expect(env.IsWorkflowCompleted()).To(BeTrue())
Expect(env.GetWorkflowError()).To(BeNil()) // THIS WILL FAIL!
```

## Specifications

  - Version: SDK v1.4.1
  - Platform: Linux 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux

**Comment by yiminc** [comment]
Looks like the default retry policy is not set for local unit test environment. If you explicitly set the retry policy, the test should work. 

Here is a working example (for hello world workflow at https://github.com/temporalio/samples-go/tree/master/helloworld):
1) set retry policy in workflow:
	ao := workflow.ActivityOptions{
		StartToCloseTimeout: 10 * time.Second,
		RetryPolicy: &temporal.RetryPolicy{
			InitialInterval: time.Second,
			BackoffCoefficient: 2,
			MaximumAttempts: 3,
		},
	}
2) set mock to fail for first attempt:
	env.OnActivity(Activity, mock.Anything, "Temporal").Return(func(ctx context.Context, msg string) (string, error) {
		info := activity.GetInfo(ctx)
		if info.Attempt == 1 {
			return "", errors.New("retry me")
		}

		return Activity(ctx, msg)
	  })

The default policy is set by server, we need to set the default one for test as well. Created a separate issue to track that: https://github.com/temporalio/sdk-go/issues/461
