### ISSUE TITLE
BackoffCoefficient must be defined and not defaulting to default value of 2.0

### ISSUE THREAD

**Issue by cowell21** [temporalio/sdk-go#413]
## Expected Behavior
When `BackoffCoefficient` is not defined in `RetryPolicy` struct it should be the default value of `2.0` per documentation in go SDK.  Cited here: https://github.com/temporalio/sdk-go/blob/4b99c26e67e253c718add87dcec54bb0e7fa29a2/internal/client.go#L530-L533

## Actual Behavior
When not defined it throws a error saying `BackoffCoefficient cannot be less than 1 on retry policy` suggesting it is defaulting to something other than `2.0`

## Possible Solutions
Fix code documentation to denote this is a required field and it doesn't have a default value.
OR
When `BackoffCoefficient` is not defined, have it backfill with default value `2.0`.

## Steps to Reproduce the Problem
  1. Create an activity / workflow without `BackoffCoefficient` defined in `RetryPolicy`
  2. Run activity and see err `BackoffCoefficient cannot be less than 1 on retry policy` surface

## Specifications

  - Version: SDK v1.4.1

**Comment by laniehei** [comment]
I believe this issue was resolved by #462. Please reopen if this issue persists.
