### ISSUE TITLE
Get history size information in workflow

### ISSUE THREAD

**Issue by daigx** [temporalio/sdk-go#420]
**Is your feature request related to a problem? Please describe.**
I'm seeing **history size exceeds error limit** error. We have DSL on top of Temporal, so I'm not able to decided when to continue workflow as new. If user define DSL with some big for loop, it will cause **history size exceeds error limit** error. 

**example error message**
```
"msg": "history size exceeds error limit.",
"wf-history-size": 14013736,
"wf-event-count": 51201,
```

**Describe the solution you'd like**
Is it possible to return history size information trough workflow.GetInfo(ctx)? In this way, I'm able to check **wf-history-size** and **wf-event-count** in workflow to decide continue as new or not.

**Comment by vitarb** [comment]
I think this is a valid feature request, I'll discuss with the team if we have good way to expose this information.
