### ISSUE TITLE
[Bug] 13 INTERNAL: Failed to parse server response when local activity has only error return parameter and returns nil

### ISSUE THREAD

**Issue by nirshirion** [temporalio/sdk-go#421]
**Describe the bug**
When running a workflow with a local activity that has only an error return parameter, and the local activity returns nil, the web UI can't show the workflow and shows this error:
13 INTERNAL: Failed to parse server response

When using the cli to show to show the workflow history, it shows it properly.

**To Reproduce**
1. Run a workflow with the above conditions:

```
func Workflow(ctx workflow.Context, name string) (string, error) {
	ao := workflow.LocalActivityOptions{
		ScheduleToCloseTimeout: time.Minute,
		StartToCloseTimeout:    time.Minute,
	}
	ctx = workflow.WithLocalActivityOptions(ctx, ao)

	err := workflow.ExecuteLocalActivity(ctx, Activity).Get(ctx, nil)
	if err != nil {
		return "", err
	}

	return "", nil
}

func Activity(ctx context.Context) error {
	return nil
}
```

2. Go to web UI, open workflow and see the error.

**Expected behavior**
The workflow history should be presented in the UI

**Screenshots**
<img width="1422" alt="Screen Shot 2021-03-11 at 12 58 49" src="https://user-images.githubusercontent.com/10175874/110777501-da440580-8269-11eb-83d8-d76d0edacdcb.png">

 - Browser: Chrome
 - Temporal Web Version: 1.7.0
 - Tctl Version: 1.7.0

**Comment by samarabbas** [comment]
We need to revisit the fix we made in https://github.com/temporalio/sdk-go/pull/367/files

**Comment by feedmeapples** [comment]
for ref, here is the original same issue #365
