### ISSUE TITLE
Workflow and activity with same name seems to confuse SDK

### ISSUE THREAD

**Issue by laniehei** [temporalio/sdk-go#425]
## Expected Behavior
If the workflow and activity are named the same thing, say `RegisterUser`, I would expect that the SDK would still choose the `RegisterUser` activity method to run.

## Actual Behavior
The test ran revealed that it was finding the Workflow `RegisterUser` function and attempting to use that signature as the activity, giving us `RegisterUserWorkflowOuput` instead of `RegisterUserActivityOutput`

## Steps to Reproduce the Problem

  1. Create a dependency and a workflow both with the same name. 
  1. Create a test expecting the unique activity output
  1. Run the test, and see that it gives you the workflow output

**Comment by vitarb** [comment]
I'm unable to repro this:
Workflow and activity code:
```
func FooBar(ctx workflow.Context, name string) error {
	ao := workflow.ActivityOptions{
		ScheduleToStartTimeout: time.Minute,
		StartToCloseTimeout:    time.Minute,
		HeartbeatTimeout:       time.Second * 20,
	}
	ctx = workflow.WithActivityOptions(ctx, ao)

	logger := workflow.GetLogger(ctx)
	logger.Info("helloworld workflow started")
	var result string
	err := workflow.ExecuteActivity(ctx, "FooBar", name).Get(ctx, &result)
	if err != nil {
		logger.Error("Activity failed.", "Error", err)
		return err
	}

	logger.Info("Workflow completed.", "Result", result)

	return nil
}

func HelloWorld(ctx context.Context, name string) (string, error) {
	logger := activity.GetLogger(ctx)
	logger.Info("hello world activity started")
	return "Hello " + name + "!", nil
}
```

Registration and worker code:
```
...
	w.RegisterWorkflowWithOptions(versioning.FooBar, workflow.RegisterOptions{Name: "FooBar"})
	w.RegisterActivityWithOptions(versioning.HelloWorld, activity.RegisterOptions{Name: "FooBar"})
...
```
As you can see I have a workflow and activity named "FooBar" and I'm able to start a workflow that runs activity using a name alias. Is there a repro that you can share?

**Comment by laniehei** [comment]
Closing for now until I can repro
