### ISSUE TITLE
Activity RetryPolicy MaximumAttempts behaves differently in workflow unit test compared to executing same workflow against real temporal server

### ISSUE THREAD

**Issue by anz-rfc** [temporalio/sdk-go#429]
## Expected Behavior

If a workflow sets Activity RetryPolicy with MaximumAttempts=1 then corresponding activity execution will not be attempted more than 1 time.

This expectation is based on interpretation of MaximumAttempts parameter as documented in [temporal-v0.28.0-changelog](https://docs.temporal.io/blog/temporal-v0.28.0-changelog/#what-has-changed):

> Activity retry refactors 🔁 :
> To disable Activity retries, configure Activities with RetryOptions that set maximumAttempts to 1.

The number of retry attempts when running against real temporal server (temporalio/auto-setup:1.7.0 ) and running the workflow using the temporal go SDK workflow unit test framework will be the same.

## Actual Behavior

When running the workflow using the temporal go sdk workflow unit test framework, if a workflow sets a Activity RetryPolicy with MaximumAttempts=1 then corresponding activity execution is attempted _twice_ (one more time than expected).

Similiar pattern observed if MaximumAttempts is set to some value n > 1  During unit tests the activity is executed n+1 times, one more time than expected.

The same behaviour is not observed when the workflow is run against a real temporal server outside of the temporal go sdk unit test framework

### unit test `retry_test.go` reproduces this behaviour

```
package main

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/suite"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/testsuite"
	"go.temporal.io/sdk/workflow"
)

const MaximumActivityExecutionAttempts = 1

var NoRetryPolicy = temporal.RetryPolicy{
	InitialInterval:        time.Second * 1,
	BackoffCoefficient:     2.0,
	MaximumInterval:        time.Second * 60,
	MaximumAttempts:        MaximumActivityExecutionAttempts,
	NonRetryableErrorTypes: []string{},
}

var StandardActivityOptions = workflow.ActivityOptions{
	TaskQueue:              "test",
	ScheduleToCloseTimeout: time.Hour * 24 * 3,
	ScheduleToStartTimeout: time.Hour * 24 * 3,
	StartToCloseTimeout:    time.Hour * 24 * 3,
	WaitForCancellation:    false,
	RetryPolicy:            &NoRetryPolicy,
}

func Foo(ctx workflow.Context) error {
	ctx = workflow.WithActivityOptions(ctx, StandardActivityOptions)
	err := workflow.ExecuteActivity(ctx, Bar).Get(ctx, nil)
	return err
}

func Bar(ctx context.Context) error {
	return nil
}

type RetryActivitySuite struct {
	suite.Suite
	testsuite.WorkflowTestSuite

	env *testsuite.TestWorkflowEnvironment
}

func (s *RetryActivitySuite) SetupTest() {
	s.env = s.NewTestWorkflowEnvironment()
	s.env.SetStartWorkflowOptions(client.StartWorkflowOptions{RetryPolicy: nil})
	s.env.RegisterWorkflow(Foo)
}

func (s *RetryActivitySuite) AfterTest(suiteName, testName string) {
	s.env.AssertExpectations(s.T())
}

func (s *RetryActivitySuite) TestActivityRetryPolicyMaximumOneAttempt() {

	var count int = 0

	s.env.OnActivity(Bar, mock.Anything).Return(
		func(ctx context.Context) error {
			count += 1
			err := fmt.Errorf("simulated Bar activity failure (mock has been called %d time(s))", count)
			return err
		},
	)

	s.env.ExecuteWorkflow(Foo)
	s.True(s.env.IsWorkflowCompleted())
	s.Error(s.env.GetWorkflowError())

	// We expect the mock Bar activity to be called
	// the same number of times as the activity retry policy's
	// MaximumAttempts parameter
	s.Equal(MaximumActivityExecutionAttempts, count)
}

func TestRetryActivitySuite(t *testing.T) {
	suite.Run(t, new(RetryActivitySuite))
}
```

```
mkdir -p temporal_retry_in_test_harness && cd temporal_retry_in_test_harness
go mod init example.com/temporal_retry_in_test_harness
# <save copy of above test as retry_test.go in working dir>
go test -v ./...
```

the test will fail and the following output will be visible

```
$ go test -v ./...
=== RUN   TestRetryActivitySuite
=== RUN   TestRetryActivitySuite/TestActivityRetryPolicyMaximumOneAttempt
2021/05/05 16:27:13 ERROR Activity error. WorkflowID default-test-workflow-id RunID default-test-run-id ActivityType Bar Attempt 1 Error simulated Bar activity failure (mock has been called 1 time(s))
2021/05/05 16:27:13 DEBUG Auto fire timer TimerID 2 TimerDuration 2s TimeSkipped 2s
2021/05/05 16:27:13 ERROR Activity error. WorkflowID default-test-workflow-id RunID default-test-run-id ActivityType Bar Attempt 2 Error simulated Bar activity failure (mock has been called 2 time(s))
2021/05/05 16:27:13 DEBUG handleActivityResult: *workflowservice.RespondActivityTaskFailedRequest. ActivityID 1 ActivityType Bar
    retry_test.go:80: 
        	Error Trace:	retry_test.go:80
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestRetryActivitySuite/TestActivityRetryPolicyMaximumOneAttempt
    workflow_testsuite.go:771: PASS:	Bar(string)
--- FAIL: TestRetryActivitySuite (0.00s)
    --- FAIL: TestRetryActivitySuite/TestActivityRetryPolicyMaximumOneAttempt (0.00s)
FAIL
FAIL	example.com/temporal_retry_in_test_harness	1.054s
FAIL
```

## Specifications

  - Version: go.temporal.io/sdk v1.6.0
  - Platform: macOS catalina

`cat go.mod`

```
$ cat go.mod 
module example.com/temporal_retry_in_test_harness

go 1.14

require (
	github.com/stretchr/testify v1.7.0
	go.temporal.io/sdk v1.6.0
)
```

`cat go.sum | grep -i temporal`

```
go.temporal.io/api v1.4.1-0.20210318194442-3f93fcec559f h1:TuHm1nX42+u7/5j9N9Mg3eX4jsri7mrpd0FivOciBH0=
go.temporal.io/api v1.4.1-0.20210318194442-3f93fcec559f/go.mod h1:c2dcPOVyWUq3IH9RIzfmKkKNSfHotYcfNzJOW+demW8=
go.temporal.io/sdk v1.6.0 h1:uVbyCd6Rs77rk5ohhWRYtPnQ7STZD2xLDAkJn8JnbaQ=
go.temporal.io/sdk v1.6.0/go.mod h1:7vODGLBoovAW72JxeMq4jENWmEkzKceNVTiIEOF5xJY=
```

**Comment by anz-rfc** [comment]
From debugging the temporal go SDK during unit testing, the logic that defines how many retry attempts happen during workflow unit testing using go SDK appears to be here: 

https://github.com/temporalio/sdk-go/blob/fc2850edf7102469b569a274a3b6f4d5ac24db50/internal/internal_task_handlers.go#L1019-L1021

it is called from `go.temporal.io/sdk/internal.(*testWorkflowEnvironmentImpl).executeActivityWithRetryForTest`


In contrast, take a look at the handling of maximum attempts inside the actual temporal server:

https://github.com/temporalio/temporal/blob/30c89b9f91dafc13d2d75fda266d81ce8bc72f3e/service/history/retry.go#L50-L68 

related to temporal server PR "Start attempts with 1 instead of 0" here https://github.com/temporalio/temporal/pull/554

related to issue https://github.com/temporalio/temporal/issues/232


Looks perhaps like the temporal go SDK used for unit testing workflow disagrees with temporal server about 1-based vs 0-based activity execution attempt numbering.

**Comment by fauzymk** [comment]
Hi, I also run into the same problem. Any solution or workaround?

**Comment by cretz** [comment]
I will try to investigate this shortly...

**Comment by cretz** [comment]
I have confirmed that this does not occur any longer (it appears to have been fixed a while back). Pasting the exact same replication code does pass the test suite. I am closing, but please update or create a new issue if you have a test case that can replicate.
