### ISSUE TITLE
ActivityEndToEndLatency Incorrectly Recorded

### ISSUE THREAD

**Issue by shannontan-bolt** [temporalio/sdk-go#431]
## Expected Behavior
Activity end to end latency is from when the activity task was scheduled to when the activity task response was completed.

## Actual Behavior
Activity end to end latency is incorrect.

```
activityMetricsScope.Timer(metrics.ActivityEndToEndLatency).Record(time.Since(activityTask.pollStartTime))
```

pollStartTime is defined here: https://github.com/temporalio/sdk-go/blob/master/internal/internal_task_pollers.go#L825, but that's the start time of when the poll was started that received the activity task, not the start time of the actual activity task. 

It should line up with how ScheduleToStart is calculated, which uses the GetStartTime() method on the returned task: https://github.com/temporalio/sdk-go/blob/master/internal/internal_task_pollers.go#L851

## Specifications

  - Version: 1.6.0
  - Platform: N/A

**Comment by shannontan-bolt** [comment]
CC @mastermanu

**Comment by vitarb** [comment]
This issue should be resolved as PR has been merged.
