### ISSUE TITLE
Workflow panic due to potential deadlock detected when many goroutines are running

### ISSUE THREAD

**Issue by bradleymcallister97** [temporalio/sdk-go#435]
**Is your feature request related to a problem? Please describe.**
When we add a large load on our temporal workflows we started to get `Workflow panic` errors with the description:
```
Potential deadlock detected: workflow goroutine "root" didn't yield for over a second
```
After some investigation, we determined that this issue was related to the number of goroutines a service had open. In order to mitigate the issue we set the `MaxConcurrentWorkflowTaskExecutionSize` and `MaxConcurrentActivityExecutionSize` on our temporal workers. The default value for each of these values is `1k`. We had to significantly lower this value to prevent the panic from occurring.

**Describe the solution you'd like**
We would like to be able to increase the `MaxConcurrentWorkflowTaskExecutionSize` and `MaxConcurrentActivityExecutionSize` values so that our service can complete activities and workflows quicker.

Currently, the default value is `1 sec`, it would be great to be able to make the deadlock timeout value configurable so that we can tweak the value on our end. We also see that there is an env var `TEMPORAL_DEBUG` which can be set to make the deadlock timeout value very large, however, this only seems like a workaround as opposed to a more permanent solution.

**Comment by vitarb** [comment]
There was a similar request on the java sdk side, where users want to have ability to redefine this timeout. I think we should add a worker option to allow that. For now if you need a temporary relief, you may set `TEMPORAL_DEBUG` environment variable, which would disable deadlock detection feature. However, do not forget to remove it once proper fix is out.

**Comment by mfateev** [comment]
> We would like to be able to increase the MaxConcurrentWorkflowTaskExecutionSize and MaxConcurrentActivityExecutionSize values so that our service can complete activities and workflows quicker.

Deadlock detector fires when a goroutine cannot get scheduled for execution for one second. It means that that your process is significantly overloaded and making it even more loaded is going to increase latency of processing and not make anything complete quicker.

**Comment by vitarb** [comment]
Looks like question has been resolved. We are considering making `1 sec` timeout configurable in the future.
