### ISSUE TITLE
Reported Metrics around availability include initial retry failures even if final call succeeds

### ISSUE THREAD

**Issue by mastermanu** [temporalio/sdk-go#442]
## Expected Behavior
If, due to some transient issue, the SDK fails on its first attempt to call Temporal, but succeeds on a retry, the metric reports 1 failure and 1 success, which could be misleading. This is because the metric emission happens on an interceptor that is triggered per-request:

```
// NewScopeInterceptor creates new metrics scope interceptor.
func NewScopeInterceptor(defaultScope tally.Scope) grpc.UnaryClientInterceptor {
	return func(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
		scope, ok := ctx.Value(ScopeContextKey).(tally.Scope)
		if !ok || scope == nil {
			scope = defaultScope
		}
		isLongPoll, ok := ctx.Value(LongPollContextKey).(bool)
		if !ok {
			isLongPoll = false
		}
		rs := newRequestScope(scope, method, isLongPoll)
		rs.recordStart()
		err := invoker(ctx, method, req, reply, cc, opts...)
		rs.recordEnd(err)
		return err
	}
}
```

Ideal behavior would be to differentiate "overall" SLA vs SLA including retry failures.

**Comment by vitarb** [comment]
I think existing metrics are good as they are because they give us detailed view of the server behavior. 
Your ask for a higher level metric that would exclude retries makes sense though, and we could add it on top of existing ones.
If I understand you correctly you want something like a replay aware `WorkflowOutboundCallsInterceptor` that would publish success/failure rate for all calls?

**Comment by mastermanu** [comment]
Yes, an additional metric that excludes retries for ultimately successful calls would be useful.  Even though this metric would not include the intermediate retries, the retries should still be in the calculated latency.

Not sure if this applies to any "replay-aware" interceptors though. This is purely about distinguishing between intermediate retries vs final success rate for gRPC calls to temporal server. Maybe I am misunderstanding where replay comes into the picture?
