### ISSUE TITLE
Add support to de-register workflows and activities

### ISSUE THREAD

**Issue by ingyamilmolinar** [temporalio/sdk-go#443]
I'm seeing some errors in the temporal workers regarding unknown activities (which were previously registered but no workflow uses anymore):

```
2021/05/14 15:54:24 util.go:27  Task processing failed with error%!(EXTRA string=Namespace, string=default, string=TaskQueue, string=jobs, string=WorkerID, string=1@temporalworker@, string=WorkerType, string=ActivityWorker, string=Error, *errors.errorString=unable to find activityType=Activity1. Supported types: [Activity2, Activity3])
```

This is happening on our staging environment since we test workflows in development there and we cannot just cleanup the database. If I list all the workflows with `tctl`, there is no workflow that is using Activity1.

There's really no way I can tell to avoid this problem. I don't want to register some previous unused activity just to avoid this error from happening if that activity is not going to be used (and I don't want it to be used).

I tried toying with `tctl admin db scan` and `tctl admin db clean` but I get a Cassandra connection issue. (I'm not using Cassandra or ES, I'm using Posgress). See: https://github.com/temporalio/temporal/issues/598

**Comment by vitarb** [comment]
I think there might be some misunderstanding here.
You don't need to "de-register" activities explicitly, you do that by deploying a worker that doesn't register an activity during startup.
If your question is about what happens to the older workflows that are still using old activity that you've deleted then you have two options here:
1. Identify and terminate or reset all workflows that are using old activity.
2. Use [versioning](https://docs.temporal.io/docs/go/versioning/) to branch your code and differentiate between old and new workflows. This way you would keep "old" activity around as long as workflows that are using it exist in the system and then you could go ahead and delete it fully once you only have new workflows that are no longer using it.
I'm going to resolve this issue as I don't see any work on the SDK that needs to be done for it, if you have more questions, please visit our [community forum](https://community.temporal.io/) and post your questions there.
