### ISSUE TITLE
temporal_activity_execution_failure Metric Doesn't Seem to Work

### ISSUE THREAD

**Issue by shannontan-bolt** [temporalio/sdk-go#457]
## Expected Behavior

When activities return an error - even if it is retryable - they should be logged against this metric.

## Actual Behavior

Activity errors don't result in any change for this metric. (Or perhaps another metric is appropriate instead).

I believe this is caused by: https://github.com/temporalio/sdk-go/blob/master/internal/internal_task_handlers.go#L1838. This returns nil for the error, but that means the code here never logs it. 

```
	// Process the activity task.
	request, err := atp.taskHandler.Execute(atp.taskQueueName, activityTask.task)
	if err != nil {
		activityMetricsScope.Counter(metrics.ActivityExecutionFailedCounter).Inc(1)
		return err
	}
```

## Steps to Reproduce the Problem

  1. Have an activity return a retryable error
  2. See that nothing is logged against this metric

## Specifications

  - Version: 1.6.0

**Comment by vitarb** [comment]
Above PR should address the problem, meanwhile if you need a it urgently, you should be able to see it in the RPC metric (`temporal_request` with `operation=RespondActivityTaskFailed`). It won't have activity/workflow types however, for that you would need to wait until above change is released.
