### ISSUE TITLE
Activity stays in started state when ActivityType is not registered

### ISSUE THREAD

**Issue by samarabbas** [temporalio/sdk-go#465]
## Expected Behavior
Worker should fail the activity immediately with "Activity type not registered" error if it picks up the task from task queue and not able to find registered type.

## Actual Behavior
If activity start_to_close timeout is large than activity stays stuck in the started state.  Basically worker picks up the task and silently fails it without reporting anything back to the service.

## Steps to Reproduce the Problem

  1.  Start workflow which schedules an activity where type is not registered
  1.  Start worker which polls on the task queue
  1.  Worker picks up the activity task and fails silently

## Specifications

  - Version:
  - Platform:

**Comment by vitarb** [comment]
I'm worried about deployment scenario when new activities are added while not all workers are capable of handling it. This might result in unintended workflow failures.
