### ISSUE TITLE
Test to support ParentClosePolicy

### ISSUE THREAD

**Issue by yiminc** [temporalio/sdk-go#470]
**Is your feature request related to a problem? Please describe.**
Test framework does not respect ParentClosePolicy set on child workflow. For example, if set child workflow's ParentClosePolicy to PARENT_CLOSE_POLICY_ABANDON, which means when parent workflow closed, its child workflow should continue executing. 

**Describe the solution you'd like**
The unit test framework should respect ParentClosePolicy. 

**Describe alternatives you've considered**

**Additional context**
Reported by user:
https://community.temporal.io/t/best-way-to-create-an-async-child-workflow/114/6

**Comment by mfateev** [comment]
I think it is [supported](https://github.com/temporalio/sdk-go/blob/d46c109d89fbc2aa3b2b1a4194d63f3ae78603e8/internal/internal_workflow.go#L194).
