### ISSUE TITLE
[Bug?] Incorrect error `Call with too few input arguments` when activity uses the wrong context

### ISSUE THREAD

**Issue by swyxio** [temporalio/sdk-go#500]
## Steps to Reproduce the Problem

i made a repro repo for you! https://github.com/sw-yx/temp-workflow-repro please see this repo to see the issue

![CleanShot 2021-07-28 at 13 44 54@2x](https://user-images.githubusercontent.com/6764957/127393422-05d0020f-59e4-447d-ae6d-f12c46de2188.png)

## Specifications

  - Version: latest
  - Platform: mac

**Comment by Delicious-Bacon** [comment]
I had this too. The error does not provide good information.

Thanks to the OP for spotting this one!

**Comment by Quinn-With-Two-Ns** [comment]
https://github.com/temporalio/sdk-go/pull/1093
