### ISSUE TITLE
sticky cache: fix resource leaks on worker.Stop()

### ISSUE THREAD

**Issue by samarabbas** [temporalio/sdk-go#51]
Currently, entire sticky cache is leaked when worker is stopped. This is because the stickyCache is a global singleton which makes it impossible to clear it on worker.Stop() (because there could be other workers using the cache and there is no way to tell which entries belong to which worker). Leaking sticky cache results in memory & go routine leaks.

The right fix here is to create stickyCache per worker and purge it completely on worker.Stop()

**Comment by samarabbas** [comment]
Ported from: https://github.com/uber-go/cadence-client/issues/739

**Comment by Sushisource** [comment]
Fixed this a while back https://github.com/temporalio/sdk-go/pull/310
