### ISSUE TITLE
Use `WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR` for non-deterministic workflow

### ISSUE THREAD

**Issue by wxing1292** [temporalio/sdk-go#513]
use `WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR` as cause for `RespondWorkflowTaskFailed` if user workflow logic is non-deterministic

Ref: https://github.com/temporalio/temporal/pull/1726

**Comment by Sushisource** [comment]
FYI this requires organizing and categorizing pretty much everywhere errors can be thrown in the SDK, which is potentially quite a lot of work/change.

**Comment by cretz** [comment]
We'll (hopefully) be looking into doing this soon

**Comment by cretz** [comment]
I have integration tests causing non-determinisms like:

> unknown command CommandType: Timer, ID: 9, possible causes are nondeterministic workflow definition code or incompatible change in the workflow definition

But those are actually failing the workflow not the workflow task. Is this a request to start failing workflow tasks instead, or are there specific existing task failures we want to add this enum to?
