### ISSUE TITLE
Provide more customizable history output

### ISSUE THREAD

**Issue by lucperkins** [temporalio/sdk-go#560]
I have a use case for Temporal (and am using the Go SDK) that involves providing event histories for workflows. The output for `GetWorkflowHistory` is quite nice if you want to relay Temporal's raw event data elsewhere, but it's a bit hard to work with if you want to provide a more "massaged" variant of that data. In my case, I'm only interested in a handful of event types and want to extract specific portions of the `Attributes` payload for each `HistoryEvent`. But since `HistoryEvent` is at the moment pretty much directly derived from the underlying Protobuf definitions, it's really tricky to wrangle into a more custom shape. It would be quite useful to me to have more "Go-native" constructs available.

I'm certainly happy to help out with this if desired. But I wanted to check in first and see if there are already efforts underway in this domain.

**Comment by cretz** [comment]
I am closing this issue, but please comment or reopen with details you'd like to see. Unfortunately to remain compatible with server changes, we need to keep the raw history available, but maybe we can provide helpers.
