### ISSUE TITLE
missing default retry policy for local activity

### ISSUE THREAD

**Issue by yiminc** [temporalio/sdk-go#563]
## Expected Behavior
LocalActivity should be retried even when no retry policy is specified.

## Actual Behavior
LocalActivity is not retried if no retry policy is specified. Or if retry policy is specified with only MaxAttempt=3 and all other fields left as unspecified.

## additional
Need to add unit test AND integration test to verify both remote activity and local activity is retried when no retry policy is specified. Also, when retry policy is specified with only MaxAttempt = 3 and all other fields unspecified.

**Comment by vitarb** [comment]
If no retry options are set, they will be nil, and [this code](https://github.com/temporalio/sdk-go/blob/ca2954d991b6a7ed6850641c502af3720d5aba4c/internal/internal_task_handlers.go#L985) is what will preventing LA retries.
In this case LA will not be retried upon failure within the same workflow task but instead will be relying on workflow task retries. Given that we retry workflow tasks until workflow itself times out this provides a natural catch all here.
Let's discuss if we want to change this behavior.

**Comment by yiminc** [comment]
Why would the workflow task fail? The LA will return error without retry and workflow code will move on.
