### ISSUE TITLE
custom data converter is not correctly wired up for local activity

### ISSUE THREAD

**Issue by yiminc** [temporalio/sdk-go#568]
## Expected Behavior
local activity result should be converted by user supplied data converter.

## Actual Behavior
Local activity result is not converted.

## Steps to Reproduce the Problem

  1. Add a simple local activity to this sample https://github.com/temporalio/samples-go/tree/master/encrypted-payloads
  1. Run it and use tctl to show history
  1. The local activity result is show as plain text.

## Specifications

  - Version:
  - Platform:

**Comment by robholland** [comment]
This was actually due to https://github.com/temporalio/samples-go/pull/140, the wiring in the go SDK is correct.
