### ISSUE TITLE
Temporal Client send signal to different namespace

### ISSUE THREAD

**Issue by elb3k** [temporalio/sdk-go#570]
**Is your feature request related to a problem? Please describe.**
I have to send signal to different namespaces, but temporal client only allows to send signal to workflows in same namespace

**Describe the solution you'd like**
[SignalWorkflow](https://github.com/temporalio/sdk-go/blob/6580cbe0aa41a8b515791f95c2c15bb37db1dab1/internal/internal_workflow_client.go#L341-L365) just passes the namespace of client. May be we can encode the namespace to context (WtihWorkflowNamespace, just like workflow version), and use namespace in SignalWorkflow function (if exists).

**Describe alternatives you've considered**
Current solution to send signal to different namespace using custom workflow, where I send the signal to different namespace.

**Additional context**
It is possible to send the signal to different namespaces within workflow, using [WithWorkflowNamespace](https://github.com/temporalio/sdk-go/blob/6580cbe0aa41a8b515791f95c2c15bb37db1dab1/workflow/workflow_options.go#L39-L42). We could have same functionality for client.

**Comment by elb3k** [comment]
One simple function to change namespace property of `Client` would be just fine too.

**Comment by cretz** [comment]
With #641, you will be able to use the gRPC service directly to send signals in any way to any namespace. I will update when implemented.

**Comment by cretz** [comment]
This has been implemented. You can now use the gRPC service directly to make whatever calls you want. Does this solve your need?

**Comment by elb3k** [comment]
Yes @cretz.
