### ISSUE TITLE
Distribute pollers to multiple frontend servers.

### ISSUE THREAD

**Issue by yiminc** [temporalio/sdk-go#577]
**Is your feature request related to a problem? Please describe.**
When worker configured to have multiple pollers, all pollers share one connection and will poll from only one frontend server. This does not work well when worker count is the same or smaller than frontend server count.

**Describe the solution you'd like**
There should have an option to be able to specify how many connections you want for one worker so the load is more evenly distributed among frontend servers. 

**Describe alternatives you've considered**
User has to start more workers to have the load more evenly distributed across all frontend servers.

**Comment by Sushisource** [comment]
We will definitely want parity in all SDKs if we do this. Good news is pollers are in core, so for core/node/other future core SDKs we need only do it once.

I like the idea of leaning on this being built in and just exposing a flag to opt in to round-robin if you pass multiple addresses.

**Comment by cretz** [comment]
The immediate use case for this issue has been solved using the `dns:///` prefix.

For general-purpose use, instead of supporting an explicit option to provide multiple addresses in #582, we have decided to simple document how users can do it in #585.
