### ISSUE TITLE
panic: runtime error: index out of range [1532] with length 1532

### ISSUE THREAD

**Issue by JunaidMkdn** [temporalio/sdk-go#587]
## Expected Behavior

no panics 

## Actual Behavior

panic: runtime error: index out of range [1532] with length 1532

goroutine 106 [running]:
github.com/temporalio/ringpop-go/swim.(*memberlist).MemberAt(0xc000136800, 0x5fc, 0xc000e0f540)
	/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20200708034907-1e016ebb537a/swim/memberlist.go:196 +0x11d
github.com/temporalio/ringpop-go/swim.(*memberlistIter).Next(0xc0007b78a8, 0x40dbdb, 0x7fd423b56f18)
	/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20200708034907-1e016ebb537a/swim/memberlist_iter.go:63 +0x105
github.com/temporalio/ringpop-go/swim.(*Node).pingNextMember(0xc0000a0b60)
	/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20200708034907-1e016ebb537a/swim/node.go:512 +0x5f
github.com/temporalio/ringpop-go/swim.(*gossip).ProtocolPeriod(0xc00080e840)
	/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20200708034907-1e016ebb537a/swim/gossip.go:177 +0x65
github.com/temporalio/ringpop-go/swim.scheduleRepeaditly.func1(0xc0009ba180, 0xc00042d380, 0xc00042d370, 0x269eed0, 0x3556178, 0xc00000e048)
	/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20200708034907-1e016ebb537a/swim/schedule.go:30 +0x82
created by github.com/temporalio/ringpop-go/swim.scheduleRepeaditly
	/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20200708034907-1e016ebb537a/swim/schedule.go:26 +0xdb

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 1.6.0
  - Platform:

**Comment by cretz** [comment]
Please feel free to reopen if this seems to be an issue with the Go SDK.
