### ISSUE TITLE
Metric for determining task pool status

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#594]
**Is your feature request related to a problem? Please describe.**

No way to determine via metrics alone that all internal workers are busy and therefore not accepting new tasks.

**Describe the solution you'd like**

Need at least a metric showing how many workers are busy/running (consider a label per worker type). If possible, include a metric showing that the system is blocked.

**Additional context**

Note, while a deadlock error does exist for workflows at https://github.com/temporalio/sdk-go/blob/6bbdd9eeef901bf5b7782114724d5ad906ba7f2e/internal/internal_workflow.go#L890 with a timeout, there may not be one for activities and we can consider such an option (keeping in mind that activity tasks are known to be potentially long running).

**Comment by jmoseley** [comment]
> a gauge for running tasks and a fixed metric for max tasks

That would let me determine if my fleet of workers is large enough for the workload or not, which would be very useful.
