### ISSUE TITLE
Expose health check on WorkflowClient

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-go#595]
Temporal SDK should expose a method like WorkflowServiceStubs#healthCheck or WorkflowServiceStubs#isHealthy that allows users to check if the WorkflowClient/WorkflowServiceStubs underlying channel / connection to Temporal server is healthy.
There were quite a bit of user requests for such a method from users for all SDKs.
Having this method on Stubs is preferable over WorkflowClient, because it's the lowest level abstraction on top of the channel and WorkflowClient can just fall back on the WorkflowServiceStubs method. But if the language doesn't have a wrapper for stubs (like Java does), this method may be on WorkflowClient.

Issues for other SDKs:
https://github.com/temporalio/sdk-java/issues/828
https://github.com/temporalio/sdk-node/issues/312

**Comment by cretz** [comment]
Waiting on SDK consensus here.

**Comment by guptamridul1809** [comment]
> Waiting on SDK consensus here.

 `// checkHealth checks service health using gRPC health check:
// https://github.com/grpc/grpc/blob/master/doc/health-checking.md
func checkHealth(connection grpc.ClientConnInterface, options ConnectionOptions) error {`

There is **checkHealth** method which is invoked at the time of client creation, but it is private (go.temporal.io/sdk@v1.12.0/internal/client.go)
It would be great if we can expose this method to public interface
will be helpful in observability and auto-recovery use-cases

**Comment by cretz** [comment]
@guptamridul1809 - This is no longer invoked on client creation in the current version (we invoke another call). But yes, this issue is for exposing that call to be called explicitly.
