### ISSUE TITLE
WorkflowRun.Get method should support a flag to disable long poll

### ISSUE THREAD

**Issue by sbansal7** [temporalio/sdk-go#604]
**Is your feature request related to a problem? Please describe.**
Currently, To get the result of a workflow, we can call WorkflowRun.Get(), but this is a blocking call that does a long poll for the workflow to finish. 

**Describe the solution you'd like**
It will be useful to add a flag in this method (or define a new method) that does not do long poll and instead returns immediately if the workflow is still running.

**Describe alternatives you've considered**
An alternative is to use a lower timeout to the Get call, but that might be a problem if network is slower.

**Comment by sbansal7** [comment]
Yes, that is what I am using as a workaround for now.

**Comment by cretz** [comment]
It was decided that, with this workaround, this is not worth adding a call to the `WorkflowRun` interface at this time. Such a call would be the same as this workaround anyways.
