### ISSUE TITLE
Test activities with same name on different queues (run from the same workflow)

### ISSUE THREAD

**Issue by lunne** [temporalio/sdk-go#609]
**Is your feature request related to a problem? Please describe.**
I would like to test activities with the same name (different signature) on different task queues.

**Describe the solution you'd like**
Set what task queue the activity is being triggered on. If we could specify the task queue or something like that on the mock `.On()` we could keep the domain specific names for the acitivites.

**Describe alternatives you've considered**
The other option we have is to rename activities on the different services so they dont have the same name. this would cause us a pattern like this:

car.GetCarById() 

insetad of 
car.GetById() 

**Additional context**
The following is a test that represent how the error is being triggered today. 

```
// main.go
package main

import (
	"context"

	"go.temporal.io/sdk/workflow"
)

type GetCarByIdParams struct{}
type Car struct{}
type activitiesCar struct{}

func (a *activitiesCar) GetById(ctx context.Context, params *GetCarByIdParams) (*Car, error) {
	return &Car{}, nil
}

type GetBussByIdParams struct{}
type Buss struct{}
type activitiesBuss struct{}

func (a *activitiesBuss) GetById(ctx context.Context, params *GetBussByIdParams) (*Buss, error) {
	return &Buss{}, nil
}

var actCar *activitiesCar
var actBuss *activitiesBuss

func TestWorkflow(ctx workflow.Context) error {

	// get a car

	opt := workflow.ActivityOptions{
		TaskQueue: "temporal.Car.worker",
	}
	var car *Car
	if err := workflow.ExecuteActivity(
		workflow.WithActivityOptions(ctx, opt),
		ctx,
		actCar.GetById,
		&GetCarByIdParams{},
	).Get(ctx, car); err != nil {
		return err
	}

	opt = workflow.ActivityOptions{
		TaskQueue: "temporal.Buss.worker",
	}
	var buss *Buss
	if err := workflow.ExecuteActivity(
		workflow.WithActivityOptions(ctx, opt),
		actBuss.GetById,
		&GetBussByIdParams{},
	).Get(ctx, buss); err != nil {
		return err
	}

	return nil
}

```

```
//main_test.go
package main

import (
	"testing"

	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/suite"
	"go.temporal.io/sdk/testsuite"
)

type UnitTestSuite struct {
	suite.Suite
	testsuite.WorkflowTestSuite

	env *testsuite.TestWorkflowEnvironment
}

func (s *UnitTestSuite) SetupTest() {
	s.env = s.NewTestWorkflowEnvironment()

	s.env.RegisterWorkflow(TestWorkflow)

}

func (s *UnitTestSuite) AfterTest(suiteName, testName string) {
	s.env.AssertExpectations(s.T())
}

func Test_NetworkService_Workflow_Tests(t *testing.T) {
	suite.Run(t, new(UnitTestSuite))
}

func (t *UnitTestSuite) Test_TestWorkflow() {

	t.env.OnActivity(actBuss.GetById, mock.Anything, &GetBussByIdParams{}).Return(&Buss{}, nil).Once()
	t.env.OnActivity(actCar.GetById, mock.Anything, &GetCarByIdParams{}).Return(&Car{}, nil).Once()

	t.env.ExecuteWorkflow(TestWorkflow)

	t.True(t.env.IsWorkflowCompleted())
	t.NoError(t.env.GetWorkflowError())
}

```

**Comment by cretz** [comment]
Thanks for the report! I will investigate options on how to mock activities specifically by task queue.

In the meantime, another alternative is to just have a callback that checks the info like:

```go
t.env.OnActivity(actBuss.GetById, mock.Anything, mock.Anything)..Return(func(ctx context.Context, params interface{}) (interface{}, error) {
  if activity.GetInfo(ctx).TaskQueue == "temporal.Car.worker" {
    return &Car{}, nil
  }
  return &Buss{}, nil
})
```

I haven't tested this, just hand-typed here, but the idea is there (will have to confirm whether empty interface param/return there works as expected). Granted this isn't as robust as potentially making a way to filter mocks on contextual information, so I will see if it is feasible to add such filtering.

For UI and other use cases, disambiguating the activity name may also have general value.

**Comment by lunne** [comment]
The proposed solution does not work. The mock needs too done with the correct signature.

Yes, you are correct. In the UI it will be more clear if the resource is included in the name. Were are going in a direction where we rename the activities as we go instead. GetById will become GetCarById  and so on. 

So for our part this ticket could be closed but it might still be good to be able to select which queue tasks are being put on to test that activities is run on the correct queue?

**Comment by cretz** [comment]
Yeah, I'm afraid `TestWorkflowEnvironment.OnActivity` for a single environment is similar to `Worker.RegisterActivity` for a single worker in that you cannot pick which task queue it each one applies to. This actually calls `RegisterActivity` internally which does not take a task queue option.

It would be a significant change I'm afraid to have task-queue specific registration and mocking inside the test suite.
