### ISSUE TITLE
Testing cron child workflow with parent policy abandon runs forever

### ISSUE THREAD

**Issue by tminusplus** [temporalio/sdk-go#614]
## Expected Behavior
Testing a cron child workflow with PARENT_CLOSE_POLICY_ABANDON should either close with the parent workflow for testsuite or have a method to shutdown the child workflow for the test.

## Actual Behavior
The cron child workflow runs forever due to the auto-fire timer and then panics when the test times out.

## Steps to Reproduce the Problem

Originally produced while updating go-sdk in a repo. There is a test below for internal_workflow_testsuite_test.go which can reproduce the issue
```
func (s *WorkflowTestSuiteUnitTest) Test_CronChildWorkflowWithParentPolicyAbandon() {
	failedCount, successCount, lastCompletionResult := 0, 0, 0
	cronWorkflow := func(ctx Context) (int, error) {
		info := GetWorkflowInfo(ctx)
		var result int
		if HasLastCompletionResult(ctx) {
			_ = GetLastCompletionResult(ctx, &result)
		}
		_ = Sleep(ctx, time.Second*3)
		if info.Attempt == 1 {
			failedCount++
			return 0, errors.New("please-retry")
		}

		successCount++
		result++
		lastCompletionResult = result
		return result, nil
	}

	testWorkflow := func(ctx Context) error {
		ctx1 := WithChildWorkflowOptions(ctx, ChildWorkflowOptions{
			WorkflowRunTimeout: time.Minute * 10,
			RetryPolicy: &RetryPolicy{
				MaximumAttempts:        5,
				InitialInterval:        time.Second,
				MaximumInterval:        time.Second * 10,
				BackoffCoefficient:     2,
				NonRetryableErrorTypes: []string{"bad-bug"},
			},
			ParentClosePolicy: enumspb.PARENT_CLOSE_POLICY_ABANDON,
			CronSchedule:      "0 * * * *", // hourly
		})

		cronFuture := ExecuteChildWorkflow(ctx1, cronWorkflow) // cron never stop so this future won't return

		timeoutTimer := NewTimer(ctx, time.Hour*3)
		selector := NewSelector(ctx)
		var err error
		selector.AddFuture(cronFuture, func(f Future) {
			err = errors.New("cron workflow returns, this is not expected")
		}).AddFuture(timeoutTimer, func(f Future) {
			// err will be nil
		}).Select(ctx)

		return err
	}

	env := s.NewTestWorkflowEnvironment()
	env.RegisterWorkflow(cronWorkflow)
	env.RegisterWorkflow(testWorkflow)

	startTime, _ := time.Parse(time.RFC3339, "2018-12-20T16:30:00+08:00")
	env.SetStartTime(startTime)
	env.ExecuteWorkflow(testWorkflow)

	s.True(env.IsWorkflowCompleted())
	err := env.GetWorkflowError()
	s.NoError(err)

	s.Equal(4, failedCount)
	s.Equal(4, successCount)
	s.Equal(4, lastCompletionResult)
}
```

Then you can run it with `go test -run "TestUnitTestSuite/Test_CronChildWorkflowWithParentPolicyAbandon"` in `sdk-go/internal`

## Specifications

  - Version: v1.11.0
  - Platform: Mac v11.6

**Comment by cretz** [comment]
To clarify, you are saying that when using abandon in a non-test it is expected to run forever, but in a test scenario it should close? How would one close the child in a non-test scenario? Maybe there should be some way to terminate all workflows started by the test suite? Sorry if I am misunderstanding.

**Comment by tminusplus** [comment]
For the non-test, yes that is my understanding. But to be clear, the main issue I am reporting is that within testsuite, if you run a child cron-job with PARENT_CLOSE_POLICY_ABANDON the test will run forever until it hits a time-out, in which case it panics.

I'm not sure what the best or intended behavior should be for testsuite, but I am hoping that we can find some method so that child cron-jobs with PARENT_CLOSE_POLICY_ABANDON can be tested without running forever.

**Comment by cretz** [comment]
> but I am hoping that we can find some method so that child cron-jobs with PARENT_CLOSE_POLICY_ABANDON can be tested without running forever.

How about some kind of "close" or "terminate all" that will stop all workflows for the test environment regardless of how they were started?

**Comment by tszucs-stripe** [comment]
That would be great, the only issue is that the blocking happens on `env.ExecuteWorkflow(testWorkflow)`. So maybe it would have to be done in a callback, or even some config to specify how many times a workflow may run.

**Comment by cretz** [comment]
Note, this was introduced by https://github.com/temporalio/sdk-go/pull/471.
