### ISSUE TITLE
Fix worker.New docs

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#618]
`worker.New` has docs that refer to a non-existent `namespace` param (also check other docs for the same bad params).

**Comment by ibeckermayer** [comment]
Specifically [here](https://github.com/temporalio/sdk-go/blob/v1.11.0/worker/worker.go#L209). I was also confused by this, and remain confused as to why `worker.New` requires a `client.Client`. 

Shouldn't it be possible to create a `Worker` without a `Client`? I was studying the hello world example, and was thrown for a loop by the fact that you need to [create a client to create a worker](https://github.com/temporalio/samples-go/blob/main/helloworld/worker/main.go), but then that client is effectively ignored afterwards, and another client is created and used separately [to actually invoke the workflow](https://github.com/temporalio/samples-go/blob/main/helloworld/starter/main.go).

**Comment by cretz** [comment]
@ibeckermayer - There may be a bit of confusion. A worker needs a client _and_ you need one to start a workflow. A worker processes server events and therefore needs a client to communicate with the server. To start a workflow is an API call and therefore needs a client to communicate with the server.

I will clarify the worker.New docs soon.
