### ISSUE TITLE
unhandled panic from workflow code

### ISSUE THREAD

**Issue by yiminc** [temporalio/sdk-go#624]
Panic from workflow code, including any code running in corotine created by any workflow.Go() should be handled by sdk.
User reported this panic stack trace suggest that we might have panic coming from [here](https://github.com/temporalio/sdk-go/blob/384e906eaace5e8914a6c0890419c23eba3b033c/internal/internal_workflow.go#L863)
panic: manual inject panic from go routine [recovered]
	panic: runtime error: slice bounds out of range [9:8]

goroutine 52489 [running]:
go.temporal.io/sdk/internal.getStackTraceRaw({0xc000e7c180, 0x14}, 0x9, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:863 +0x1bd
go.temporal.io/sdk/internal.getStackTrace({0x52ba998, 0x7f069a39aa68}, {0x30317d5, 0x5}, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:853 +0xab
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1.1()
	external/io_temporal_go_sdk/internal/internal_workflow.go:936 +0x73
panic({0x2995340, 0x346e360})
	GOROOT/src/runtime/panic.go:1038 +0x215
xxxxxxx/xxxx/xxxxxxxx.(*Workflow).startBlocks.func1({0xc001857950, 0x1})
	xxxxx/xxxxxxxx/workflow.go:432 +0x27
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1(0xc0008ee120)
	external/io_temporal_go_sdk/internal/internal_workflow.go:941 +0xde
created by go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine
	external/io_temporal_go_sdk/internal/internal_workflow.go:932 +0x365
panic: manual inject panic from go routine [recovered]
	panic: runtime error: slice bounds out of range [9:8]

goroutine 52382 [running]:
go.temporal.io/sdk/internal.getStackTraceRaw({0xc001e65698, 0x14}, 0x9, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:863 +0x1bd
go.temporal.io/sdk/internal.getStackTrace({0x52ba998, 0x34ed810}, {0x30317d5, 0x5}, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:853 +0xab
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1.1()
	external/io_temporal_go_sdk/internal/internal_workflow.go:936 +0x73
panic({0x2995340, 0x346e360})
	GOROOT/src/runtime/panic.go:1038 +0x215
xxxxxxx/xxxxxxx/xxxxxxxxxx.(*Workflow).startBlocks.func1({0xc001c8fe50, 0x1})
	xxxxxxx/xxxxxxxxxx/workflow.go:432 +0x27
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1(0xc0024b1030)
	external/io_temporal_go_sdk/internal/internal_workflow.go:941 +0xde
created by go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine
	external/io_temporal_go_sdk/internal/internal_workflow.go:932 +0x365

**Comment by cretz** [comment]
I am struggling to replicate this. I cannot panic from `workflow.Go` in a way that gets the stack small enough to replicate this. I can of course fix bounds size issue, but I would like a way to test. Can simple code to replicate be provided?

**Comment by cretz** [comment]
Despite being unable to replicate, I am adding bounds checks to the stack trace line filter.
