### ISSUE TITLE
Concurrent ExecuteWorkflow will gen same RunId

### ISSUE THREAD

**Issue by franktz** [temporalio/sdk-go#630]
## Expected Behavior
Concurrent ExecuteWorkflow will gen different RunId

## Actual Behavior
Concurrent ExecuteWorkflow will gen same RunId

## Steps to Reproduce the Problem
  1.git clone https://github.com/temporalio/money-transfer-project-template-go
  2.modify start/main.go, add 'for range' contain "options := client.StartWorkflowOptions{" and "printResults(transferDetails, we.GetID(), we.GetRunID())"
  3.go run start/main.go
  4.see stdout, "we.GetID()" is the same.

## Specifications

  - Version:
  - Platform:

**Comment by cretz** [comment]
`GetID` is the workflow ID, `GetRunID` is the run ID. Regardless, running that way reuses the ID, which is supposed to be unique. The default ID reuse policy (see start workflow options) does not error but intention.

Multiple workflow runs should use unique workflow IDs. Of course reusing an ID on a failed workflow by default creates a new run ID.

**Comment by franktz** [comment]
> `GetID` is the workflow ID, `GetRunID` is the run ID. Regardless, running that way reuses the ID, which is supposed to be unique. The default ID reuse policy (see start workflow options) does not error by intention.
> 
> Multiple workflow runs should use unique workflow IDs. Of course reusing an ID on a failed workflow by default creates a new run ID.

Got it! Thank you very much.

**Comment by cretz** [comment]
The `worker.Options` (aliased to https://pkg.go.dev/go.temporal.io/sdk/internal#WorkerOptions) have options for max concurrent executions. You can probably set `MaxConcurrentWorkflowTaskExecutionSize` for one workflow at a time (but would still need to set the same for activities if you want to limit those).

Limiting workflow execution count may not always be the best way. All real work happens in activities so most of the time it would be there you'd want to limit.

Also if it's easier, feel free to ask questions in our forum at https://community.temporal.io/ or slack at https://temporal.io/slack.

**Comment by franktz** [comment]
> The `worker.Options` (aliased to https://pkg.go.dev/go.temporal.io/sdk/internal#WorkerOptions) have options for max concurrent executions. You can probably set `MaxConcurrentWorkflowTaskExecutionSize` for one workflow at a time (but would still need to set the same for activities if you want to limit those).
> 
> Limiting workflow execution count may not always be the best way. All real work happens in activities so most of the time it would be there you'd want to limit.
> 
> Also if it's easier, feel free to ask questions in our forum at https://community.temporal.io/ or slack at https://temporal.io/slack.

Thank you. I have no question now.
