### ISSUE TITLE
gogo/protobuf is unmaintained

### ISSUE THREAD

**Issue by pquerna** [temporalio/sdk-go#658]
## Expected Behavior
`github.com/gogo/protobuf` is unmaintained: https://github.com/gogo/protobuf/issues/691

At this point it would be nice for the Client SDK to consider using the standard protobuf library.

## Actual Behavior

Seems blocked on https://github.com/temporalio/temporal/issues/38

But `google.golang.org/protobuf` is the defacto dependency at this point, and the client SDK, its unclear if the performance concerns are warranted for general purpose worker clients or other non-temrporal core uses of the APIs?

**Comment by cretz** [comment]
Yes, there are discussions to be had on whether the performance difference is worth it. I am gathering feedback from others.

**Comment by cretz** [comment]
Yes, this issue is blocked on https://github.com/temporalio/temporal/issues/38 or similar since we share https://github.com/temporalio/api-go. I will leave this open pending that issue.

**Comment by ash2k** [comment]
This issue is closed but the gogo dependency is still in the go.mod file. Any chances of getting rid of it completely? Also, would be nice to get a release with the change. Thank you.

**Comment by Quinn-With-Two-Ns** [comment]
gogoproto is still in the mod file because `ProtoJSONPayloadConverter` and `ProtoPayloadConverter` support gogoproto structs and we did not remove support for backwards compatibility

**Comment by cretz** [comment]
Usually quite a while. But this dependency should be harmless if you don't use it, it's only for people that still use gogoproto in _their_ protos. Can you clarify the issues that this dependency is causing?
