### ISSUE TITLE
How to provide an Authorization Token in Golang

### ISSUE THREAD

**Issue by DashAbhishek** [temporalio/sdk-go#671]
the golang sdk doc dose not talk about any possible way how a user can provide authorization token, just like in java sdk theres a separate doc for authorization. can we have a similar doc, and i would like to know how it can be done.

https://docs.temporal.io/docs/content/how-to-provide-an-authorization-token-in-java

**Comment by cretz** [comment]
I have opened https://github.com/temporalio/samples-go/issues/160 to address this.

There are two ways, you can set `client.Options.HeadersProvider` with an instance that returns a map with `Authorization` as the key and `Bearer <mytoken>` as the value.

The other way is only on the newest SDK. You can set gRPC dial options directly on `client.Options.ConnectionOptions.DialOptions` which could have an interceptor where you can set the header via gRPC metadata. This is basically how the first way is implemented.

**Comment by cretz** [comment]
Sample PR merged

**Comment by AbhayP-22** [comment]
Do we have the sample to add token in go lang SDK

**Comment by cretz** [comment]
The sample at https://github.com/temporalio/samples-go/tree/main/serverjwtauth shows how to make a custom header provider at https://github.com/temporalio/samples-go/blob/b49280daa78f354036d7d749157252369bca9b89/serverjwtauth/keyutil.go#L135 to set headers with a token.
