### ISSUE TITLE
CreateSession improperly retrying errors it should not

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#722]
**Is your feature request related to a problem? Please describe.**

At https://github.com/temporalio/sdk-go/commit/a88dec51b1767a1bab6426a602980d25a51d40eb#diff-5db8d6c4288666da4ff606f745645fe946e504370e93bbceb25402e0a520deb0 we inadvertently removed intentional retry-prevention to prevent session activity creation from retrying in all but the "too many sessions" case.

**Describe the solution you'd like**

Do not have session creation activity failure retry anything but "too many sessions".

**Comment by yycptt** [comment]
Some additional context here, one of the purposes of session creation activity is monitoring the health of worker process. If worker restarts while a session is running, the creation activity should fail and all user activities within this session will be cancelled. If the creation activity is retried for errors like timeout, workflow won't know the worker for session tasklist has already gone and continue to schedule more activities to that worker-specific tasklist which now has no poller.

**Comment by cretz** [comment]
It appears you can't really set start-to-close or heartbeat timeouts as non-retryable. Only application failures. How should we implement "only retry a certain application error"? Should we manually loop in the workflow with out own backoff?

**Comment by yycptt** [comment]
@cretz We will add support on server side for specifying timeout errors as non-retryable.

**Comment by yycptt** [comment]
https://github.com/temporalio/sdk-go/blob/master/internal/session.go#L526
`errTooManySessions` is retryable so the third argument should actually `false`

**Comment by cretz** [comment]
@yycptt - Ok, I will make that non-retryable. I will wait on server update so that I can include in the same PR with a retry policy excluding timeouts from being retryable (please link issue here if/when available).

**Comment by cretz** [comment]
After discussion, we think we can solve this by just disallowing all retries on create session. As for the one case where we did want retries - max sessions reached - we think we can solve this by using max concurrent activities. Hopefully implementation on this will begin shortly.

**Comment by cretz** [comment]
I am working to build a reproducer for this bug.

**Comment by cretz** [comment]
Reproducer is complete, I am now implementing the fix and the tests for the fix.

**Comment by cretz** [comment]
#739 was attempted but deemed unsafe for session recreation. Instead we will leverage https://github.com/temporalio/temporal/pull/2524 the way the older set of code once did and disable timeout retries. This means to get full session safety functionality, a server upgrade will be required (I may make a note of this point in the docs).

I will also cherry pick integration tests from #739 (that I didn't already for #741) and we will set max activity size on session creation activity worker (even though we know that is not enough to really solve the max across creation and recreation).
