### ISSUE TITLE
Cannot use SignalWithStartWorkflow in tests

### ISSUE THREAD

**Issue by nicolaferraro** [temporalio/sdk-go#736]
**Is your feature request related to a problem? Please describe.**

Trying to test a scenario that uses "SignalWithStartWorkflow" available in the client, I've found out there's no equivalent method in the testsuite, neither that function is available to workflows for sending signals to other workflows in standby.

**Describe the solution you'd like**
SignalWithStartWorkflow should be included in the testsuite. Ideally I should able to create a standard client for a unit test environment.

**Describe alternatives you've considered**
Doing integration tests instead of unit tests.

**Comment by cretz** [comment]
Sending signals is done with `testsuite.TestWorkflowEnvironment.RegisterDelayedCallback`. From the docs there:

> Use 0 delayDuration to send a signal to simulate SignalWithStart.

This is not clear from our public docs, so I have opened https://github.com/temporalio/documentation/issues/939.

**Comment by nicolaferraro** [comment]
> Sending signals is done with `testsuite.TestWorkflowEnvironment.RegisterDelayedCallback`. From the docs there:
> 
> > Use 0 delayDuration to send a signal to simulate SignalWithStart.
> 
> This is not clear from our public docs, so I have opened [temporalio/documentation#939](https://github.com/temporalio/documentation/issues/939).

Thanks! Yeah, I've seen the comment in the source code. But it seems it cannot pass data to the workflow being started, right?

**Comment by cretz** [comment]
Closing issue. Feel free to respond with additional questions and/or reopen if you feel the issue persists.
