### ISSUE TITLE
Move some data conversion out of the deadlock detection scope

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#769]
**Is your feature request related to a problem? Please describe.**

Some advanced use cases of workflow data converters do not want to be bound to Temporal workflow deadlock rules

**Describe the solution you'd like**

For as much as is reasonable, try to do the data conversion outside of the inline workflow and nearer to the commands/events. Even if I try to take a simple approach (e.g. shipping Go object + data converter around instead of payloads), I fear this is quite a daunting challenge. Also, I will have to confirm we don't expect data conversion errors to be able to be handled inline.

**Comment by mfateev** [comment]
One "hacky" option is to measure time spent in DataConverter and extend the deadlock detector timeout by this value.

**Comment by cretz** [comment]
Yes, I am thinking this is the most likely approach (or as a timer that can be stopped and then started again)
