### ISSUE TITLE
Expose fatal worker error in some way and stop killing process

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#792]
**Is your feature request related to a problem? Please describe.**

Right now, a non-retryable worker error signals itself to kill the process which is not OK.

**Describe the solution you'd like**

We need to just stop the entire worker and relay the error. Right now, someone can `Start` and won't see an error until `Stop` is called. We can relay via the `Run` call, but not everyone uses that. We should either return something that the user can listen for errors on from `Start` or we need to have a `WorkerFailureHandler` option or similar (whether that defaults to signal + process death to keep compat is an open question).

**Comment by alexshtin** [comment]
Code reference: https://github.com/temporalio/sdk-go/blob/cb9c7de44f8774ab6681f4469ecbed8243d082dd/internal/internal_worker_base.go#L320
