### ISSUE TITLE
Access raw error message

### ISSUE THREAD

**Issue by guptamridul1809** [temporalio/sdk-go#797]
The various error types exposed in the temporal workflows do not provide access to the raw error message.
The .Error() method on these error types adds a bunch of details along with the error message.

The .message() method on them is private as well.

Is there a way to access the raw error message from these error structs?

**Comment by cretz** [comment]
Can you give the specific errors you cannot get the underlying errors out of via `errors.Unwrap()`? We try to stick to proper `Unwrap()` convention but we miss some.

**Comment by guptamridul1809** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/97242793/165996687-d55205a9-1e6f-42db-851e-f89221e224ee.png">

We're passing a custom error type from worker which gets wrapped inside a ApplicationError.
When trying to get the error message from the ApplicationError it formats the string with error type and non-retryable bool. I need the raw error message from the Application Error to pass it on to the UI.

**Comment by cretz** [comment]
Ah, the raw message. We have just solved this in #766 and it is in master and will be released with the next release (a week or two).

**Comment by guptamridul1809** [comment]
Awesome! thanks @cretz
