### ISSUE TITLE
testsuite support restarting workflow if returned `NewContinueAsNewError`

### ISSUE THREAD

**Issue by jackielii** [temporalio/sdk-go#805]
**Is your feature request related to a problem? Please describe.**
I have a workflow that relies on child workflow to run many times. And I need to test the behaviour of this behaviour.

E.g. in the [child-workflow-continue-as-new](https://github.com/temporalio/samples-go/tree/main/child-workflow-continue-as-new) example, we want to test the the child workflow is executed exactly _5_ times.

**Describe the solution you'd like**
In order to keep compatibility, I propose adding an method in `TestWorkflowEnvironment` called `EnableRunContinueAsNew`. 

If this option is enabled, the `ContinueAsNewError` won't be returned, but workflow will be executed instead.

**Describe alternatives you've considered**
There is no easy alternatives. The only one I can think of is an integration testing with full temporal + workflow worker setup.

**Comment by jackielii** [comment]
Good point, I tend to agree with you. Also I found that I should probably mock the child workflow using `env.OnWorkflow`.

Closing...

**Comment by cretz** [comment]
By the way, for integration testing, have a look at this package: https://pkg.go.dev/github.com/DataDog/temporalite/temporaltest
