### ISSUE TITLE
Add ReplayWorkflowHistoryFromReader (or similar)

### ISSUE THREAD

**Issue by gsmcwhirter** [temporalio/sdk-go#808]
**Is your feature request related to a problem? Please describe.**

I'd like to use go:embed to access replay history files in the repository for testing. However, the current replay API seems to require me parsing the contents into a history object myself or not using go:embed and using a static file name instead.

**Describe the solution you'd like**

Add `ReplayWorkflowHistoryFromReader(logger log.Logger, jsonFile io.Reader) error` and `ReplayPartialWorkflowHistoryFromReader(logger log.Logger, jsonfile io.Reader, lastEventID int64) error` (or similar) to the `WorkflowReplayer` interface and implementations. 

**Describe alternatives you've considered**

**Additional context**
Adding these APIs could also enable other future uses where replay histories were stored on a remote server, or stored gzipped, etc.

**Comment by cretz** [comment]
Would a helper `func HistoryFromJSON(b []byte) (*history.History, error)` work? I am trying not to alter the interface and were I not concerned with backwards compatibility, I would also remove the file-based functions from the replayer interface.

**Comment by cretz** [comment]
Ok, I will use reader. The amount is expected to fit in memory anyways, so a reader isn't really necessary, but anyone can do `bytes.NewReader` if they want. I will also provide a "partial" form which accepts the last event ID though it's rare for people to use that (anyone can also trim off the events slice in the result themselves).

**Comment by gsmcwhirter** [comment]
I personally haven't had a need to use partial replays yet, so if they're really not common, maybe it is enough for a user to trim down on their own. I do know that looking into the code for how the current versions work, it wasn't super clear to me how to slice history structure appropriately if there wasn't that example hanging around.

**Comment by gsmcwhirter** [comment]
Also if the data is really that small, maybe `[]byte` is fine. From my reading, histories could get to something like 50k events before there's issues, which seems like it might be a decent bit of memory, but perhaps the expansion to actual memory size isn't as large as I imagine
