### ISSUE TITLE
OnUpsertSearchAttributes changes / additions

### ISSUE THREAD

**Issue by gsmcwhirter** [temporalio/sdk-go#810]
**Is your feature request related to a problem? Please describe.**
I am trying to write a workflow test that would call `workflow.UpsertSearchAttributes` possibly many times. The order of the calls is slightly random (randomization inside a side effect for deterministic replay), so I was hoping to use the `OnUpsertSearchAttributes` hook of the `TestWorkflowEnvironment` to record the calls that were made and check myself to ensure they are within the expected randomization bounds.

However, it appears that `OnUpsertSearchAttributes` takes a single argument of type `map[string]interface{}`, unlike `OnActivity` whose arguments are just `interface{}`. As far as I can tell, this prevents me from passing something equivalent to `mock.Anything` and using the `.Run()` function on the mock to record the actual arguments that were passed.

**Describe the solution you'd like**
I would like a way to use `OnUpsertSearchAttributes` or some other similar hook more like `OnActivity`.

**Describe alternatives you've considered**
We tried using the actual key(s) that would be in the upsert payload with `mock.Anything` as the value; we also tried using `mock.Anything` as the key, but neither allowed for arbitrary matching.

**Additional context**

**Comment by cretz** [comment]
Hrmm, I wonder if just changing that param from `map[string]interface{}` to just `interface{}` introduces any big problematic backwards compatibility concerns. I will investigate.
