### ISSUE TITLE
Terminated workflow fails replay

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#815]
## Expected Behavior

Should be able to handle terminated workflow event same as it does continue as new

## Actual Behavior

We don't have a switch case for `EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED` so running in replayer causes failure

Also, make sure we check for any other missing enums

**Comment by alexshtin** [comment]
`switch` is here: https://github.com/temporalio/sdk-go/blob/master/internal/internal_event_handlers.go#L810
