### ISSUE TITLE
attributes.GetNamespace undefined (type *command.ScheduleActivityTaskCommandAttributes has no field or method GetNamespace) (compile)

### ISSUE THREAD

**Issue by Delicious-Bacon** [temporalio/sdk-go#825]
## Expected Behavior
Should compile.

## Actual Behavior
Doesn't compile.

## Steps to Reproduce the Problem

  1. Update the go.temporal.io/api to the latest version (v1.8.0)

## Specifications

  - Version: v1.14.0
  - Platform: N/A

## Notes
A mismatch with api and sdk versions?

![image](https://user-images.githubusercontent.com/78080236/172041261-d11ddfcb-4557-4f6c-820c-c82568a321f6.png)

**Comment by cretz** [comment]
The SDK is building in CI and I have personally confirmed it is building from a fresh clone. Can you give the _exact_ steps to replicate your issue?

**Comment by TohChunKiat** [comment]
I'm encountering this issue too. Using 	go.temporal.io/sdk v1.14.0 . I ran go get + go mod vendor and build failed

**Comment by slaskis** [comment]
Field number 3 (`Namespace`) is missing: https://github.com/temporalio/api-go/blob/master/command/v1/message.pb.go#L62-L63

**Comment by Delicious-Bacon** [comment]
> The SDK is building in CI and I have personally confirmed it is building from a fresh clone. Can you give the _exact_ steps to replicate your issue?

I had `go.temporal.io/api v1.7.1` and `go.temporal.io/sdk v1.14.0`. There was an update for `/api` to `v1.8.0` so I downloaded it. After that, I had an error as shown in the original issue post.

>Ah, I think Go defaults to updating to the latest go.temporal.io/api. I think you may have to, after go-get'ing the SDK, get the exact go.temporal.io/api version as in go.mod in that tag.
>
> I am releasing a new Go SDK version today or tomorrow that works properly with 1.8.0 of that library. I will update soon.

Well, yes, just like I asked in the original post, `A mismatch with api and sdk versions?` 🙃

In any case, you know the dependencies better than me.

Also, thank you for looking into it! ❤️

**Comment by cretz** [comment]
I have released SDK v1.15.0. Please see upgrading to that version solves your issues.

**Comment by Delicious-Bacon** [comment]
> I have released SDK v1.15.0. Please see upgrading to that version solves your issues.

Confirmed, upgrading the api to `v.1.8.0` and sdk to `v.1.15.0` solves the problem.

Thank you @cretz ! 💯
