### ISSUE TITLE
Record Reason Code for RPC Failure

### ISSUE THREAD

**Issue by shannontan-bolt** [temporalio/sdk-go#858]
**Is your feature request related to a problem? Please describe.**
We have a dashboard and metrics on RPC failures for monitoring our connectivity and requests to the Temporal Cloud service. Right now, our RPC failure percentage monitor triggers due to failures to DescribeWorkflowExecution, which we use to check if there's a running workflow.

It would be beneficial to include a reason code/error type for these RPC failures so that we're able to dive into them better.

Logs would also be helpful (or an alternative).

**Describe the solution you'd like**
Reason code to be included alongside relevant operations, such as DescribeWorkflowExecution

**Describe alternatives you've considered**
Logs, but those don't appear to be printed either.

I'm also open to altering my approach to check if a workflow is running if there's a way to do so.

**Additional context**
I use Temporal Cloud.

**Comment by cretz** [comment]
> It would be beneficial to include a reason code/error type for these RPC failures so that we're able to dive into them better.

Can you clarify? Are you talking about gRPC error codes? Or something like adding custom error codes for all errors that come from the server? You can of course write a gRPC interceptor to do anything with any response, increment any metrics, etc.

> Logs would also be helpful (or an alternative).

Can you clarify here? The error is returned to you so you can log whatever you want. Or do you mean server-side logs somehow?

It might help if you could provide a specific error you are receiving and what information is not present that we could make available.

**Comment by shannontan-bolt** [comment]
Thank you for following up! I definitely omitted some additional details haha.

> Can you clarify? Are you talking about gRPC error codes? Or something like adding custom error codes for all errors that come from the server?

We use `temporal_request_failure` as the metric to monitor RPC calls to the server. I was thinking in the context of DescribeWorkflowExecution for example that a tag that could be added is the "NotFound" response. I suppose the "real" reason we have an alarm on this metric is for connectivity/service failures as opposed to business failures like "NotFound" errors.

> You can of course write a gRPC interceptor to do anything with any response, increment any metrics, etc.

I didn't think about this, good point :p 

> Can you clarify here? The error is returned to you so you can log whatever you want. Or do you mean server-side logs somehow?

SDK-side logs I suppose. Right now, the SDK logs like "Activity error" or "Workflow processing..." In the case of failing RPCs, it would be good to have context to debug that. You are probably right though that the returned error should be our responsibility to log.

------------------------------------------

Semi-related context: Since I sit on a Platforms team just managing the overall usage of Temporal as opposed to any single use case, my goals are a bit different than other teams at my company. My goal is to make sure I know when Temporal is up/down, what may have caused that, and what my team needs to do to mitigate the issue. Therefore, I don't explicitly control whether something is logged, but I still would like to determine if the issue is just business logic vs server errors (like 404 vs 500s).

**Comment by cretz** [comment]
> Do you know of any example I can refer to that would intercept it for a specific call and increment metrics?

This is a general gRPC feature. See https://github.com/grpc/grpc-go. Basically you use `grpc.WithUnaryInterceptor` (or `grpc.WithChainUnaryInterceptor` if you want to be called including automatic retries) and set it on `client.Options.ConnectionOptions.DialOptions`.

> it isn't clear what this metric should be used to represent

This metric is very clear/simple: Any gRPC failure. What may be unclear is what the user considers a failure or not. But that doesn't affect a low-level metric.

> I could imagine one using it to determine validity of requests/connectivity to the server, but DescribeWorkflowExecution is going to always make it challenging to use that metric for that. Wouldn't this necessitate that most adopters would have to write their own interceptor for this same use case?

Or they don't use the same metric handlers for clients that they are giving to workers and clients that they are expecting errors from. Or they exclude metrics with the describe `operation` tag. Or, yes, they use their metric system the same way they might with the rest of their application to record their errors that are important to them.

> I would love your guidance too, if possible, on what one should use temporal_request_failure metric for too.

I think many use it to see large changes in error reports and may only use it on clients given to workers instead of ones they are making client calls on. Many may not use it at all, preferring their own metrics for what they consider errors.

**Comment by shannontan-bolt** [comment]
Thanks!
