### ISSUE TITLE
Make possible non-deterministic errors clear that's what they may be

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#864]
**Is your feature request related to a problem? Please describe.**

Of the three errors at https://community.temporal.io/t/go-sdk-troubleshooting/4440#workflow-non-determinism-5, only one mentions non-determinism.

**Describe the solution you'd like**

Prepend `"nondeterministic workflow: "` to the other two.

**Comment by Quinn-With-Two-Ns** [comment]
closing in favor of https://github.com/temporalio/sdk-go/pull/1281
