### ISSUE TITLE
panic if `Run` and `Stop` race

### ISSUE THREAD

**Issue by twmb** [temporalio/sdk-go#868]
`internal_worker.AggregatedWorker#Run` calls `aw.Start`, which asserts that the worker has not yet been stopped.

`Run` is a blocking function, it must be executed in a goroutine if the user wants to stop the worker independently. The user may then wait for an input signal and `Stop` the worker. It is possible that `Run` has not yet started and `Stop` executes before `Run`. In this tight sequence of events, the code will panic: https://github.com/temporalio/sdk-go/blob/dea0cfa509b981c05ea4e9c9ad2f841845997574/internal/internal_worker.go#L955

Since `Run` returns an error, I'd expect this code to just return `ErrClosed` or something similar.

**Comment by cretz** [comment]
For users who cannot be sure that `worker.Stop()` will be called after `worker.Run()`, they may find it better to use `worker.Start()` in the same goroutine they may later call `Stop()`. This is one reason we provide both `Start()` and `Run()`, for those that need to now when started (which `Run()` cannot tell them).

**Comment by twmb** [comment]
Is the point of `Run` to not ever be shutdown? The theoretical race exists in any model of using `Run` in tandem with `Close`.

**Comment by cretz** [comment]
Definitely can shutdown. The point of Run is as a helper for people that want to block until shutdown, but Start is better for those concerned that they need to know when start completed because they may immediately shutdown.

Yes, the race exists between Run and Stop. Users concerned about this race should use Start and Stop.

**Comment by cretz** [comment]
Closing, in favor of using `Start`. Users should not use `Run` if they're concerned they may shutdown before running. Reopen if needed.

**Comment by twmb** [comment]
At a minimum, the panic should be noted in docs on Run. The safest way to
program around the panic right now is to only allow Close to occur in an
activity that is ran at least once. This is the only way for a user to
_know_ that the temporal client has started.

Without this, users have to rely on heuristics and hope. Any proper
shutdown path that triggers a more immediate exit can panic if an interrupt
is received while things are starting up.

**Comment by cretz** [comment]
> At a minimum, the panic should be noted in docs on Run. 

Ok, I will add docs.

> The safest way to program around the panic right now is to only allow Close to occur in an activity that is ran at least once

The safest way is to use `Start`. Users can rely on this instead of heuristics and hope. In retrospect, maybe we should have never had the `Run` helper since its utility seems confusing and is easy to build yourself using `Start`.
