### ISSUE TITLE
Accept <- chan struct{} in Worker.Run

### ISSUE THREAD

**Issue by alfa-alex** [temporalio/sdk-go#874]
**Is your feature request related to a problem? Please describe.**
The `worker.Run()` function accepts a `<- chan interface{}` parameter. This makes it impossible to directly pass, e.g., `ctx.Done()` (which seems to me is the most common use case besides `internal.InterruptCh()`).

**Describe the solution you'd like**
It'd be great if the `worker.Run()` function accepted a `<- chan struct{}` instead. The `internal.InterruptCh` should then also return a `<- chan struct{}`.

**Describe alternatives you've considered**
Since this would be a breaking change, a viable alternative would be to add a `RunCtx(context.Context)` function to the `worker` interface that you directly pass a context. Would also be idiomatic.

**Additional context**
- Since it's irrelevant what you pass to the channel, a `<- chan struct{}` might also more clearly express that this channel is just used for signalling *that* some event happened.
- If you decided to change the signature of `internal.InterruptCh`, that func could then be implemented as a two-liner by utilizing `signal.NotifyCtx(...)`.

**Comment by cretz** [comment]
I am afraid we cannot make a breaking change here.

**Comment by cretz** [comment]
> So the provided alternative is also not an option, I suppose?

Unfortunately adding helpers/shortcuts on the worker interface is probably not the best thing. But they could be added top level. For instance, anyone could do (untested, just typed here in GH):

```go
func RunWorker(ctx context.Context, worker worker.Worker) error {
  doneCh := make(chan interface{})
  errCh := make(chan error, 1)
  go func() { errCh <- worker.Run(doneCh) }()
  select {
    case <-ctx.Done():
      close(doneCh)
    case err := <-errCh:
      return err
  }
  return <-errCh
}
```

> Then maybe something to keep in mind for v2 of the SDK.

For sure
