### ISSUE TITLE
independent lifecycles for cloned clients

### ISSUE THREAD

**Issue by dnr** [temporalio/sdk-go#886]
## Expected Behavior

When using `NewClientFromExisting` from #881, the "parent" and "child" `Client`s have independent lifecycles from the point of view of client code, even though they share some resources. That is, I can call `Close` on only one or both of them, and resources will be cleaned up when appropriate.

This makes it easier to use in large programs since we don't have to essentially ban use of `Close`, we can let anyone who gets a cloned client treat it as if it were a fully-independent one.

## Actual Behavior

Calling `Close()` on either the parent or child will close the connection for both of them immediately.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: unreleased post 1.16
  - Platform:

**Comment by cretz** [comment]
:+1: We need to make it very clear in Godoc on `Close()` that it sometimes doesn't close the connection and that one reused connection left open will forever leave the connection open for everyone.
