### ISSUE TITLE
TestSuite: Workflow names seemingly collide with activity names in mock expectations

### ISSUE THREAD

**Issue by krousey** [temporalio/sdk-go#887]
I have a set of workflows and activities implemented as methods on a struct. I happened to name an activity method with the same name as the workflow method. Everything actually works when running the workflow, but the test framework errors out complaining about different amount of return values. The workflow method only returns an error while the activity method returns a value and an error.

If I change the name of the activity method in all places, the tests start passing.

## Expected Behavior

Passing tests.

## Actual Behavior

```console
go test
--- FAIL: Test_Workflow (0.00s)
    workflows_test.go:20: 
        	Error Trace:	/tmp/example/workflows_test.go:20
        	Error:      	Received unexpected error:
        	            	workflow execution error (type: GenericName, workflowID: default-test-workflow-id, runID: default-test-run-id): mock of GenericName has incorrect number of returns, expected 1, but actual is 2
        	Test:       	Test_Workflow
FAIL
exit status 1
FAIL	example	0.003s
```

## Steps to Reproduce the Problem

workflows.go:
```go
package example

import (
	"context"
	"time"

	"go.temporal.io/sdk/workflow"
)

type Workflows struct{}

func (w *Workflows) GenericName(ctx workflow.Context, input string) error {
	return workflow.ExecuteActivity(
		workflow.WithActivityOptions(ctx, workflow.ActivityOptions{
			StartToCloseTimeout: time.Minute,
		}),
		Activities{}.GenericName,
		input).Get(ctx, nil)

}

type Activities struct{}

func (a Activities) GenericName(ctx context.Context, input string) (string, error) {
	return input, nil
}
```

workflows_test.go:
```go
package example

import (
	"testing"

	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	"go.temporal.io/sdk/testsuite"
)

func Test_Workflow(t *testing.T) {
	testSuite := testsuite.WorkflowTestSuite{}
	env := testSuite.NewTestWorkflowEnvironment()

	env.OnActivity(new(Activities).GenericName, mock.Anything, "input").Return("output", nil)

	env.ExecuteWorkflow(new(Workflows).GenericName, "input")

	require.True(t, env.IsWorkflowCompleted())
	require.NoError(t, env.GetWorkflowError())
}
```
  
## Specifications

 go.mod:
```go
module example

go 1.18

require (
	github.com/stretchr/testify v1.8.0
	go.temporal.io/sdk v1.16.0
)

require (
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/facebookgo/clock v0.0.0-20150410010913-600d898af40a // indirect
	github.com/gogo/googleapis v1.4.1 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/gogo/status v1.1.1 // indirect
	github.com/golang/mock v1.6.0 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/uuid v1.3.0 // indirect
	github.com/grpc-ecosystem/go-grpc-middleware v1.3.0 // indirect
	github.com/pborman/uuid v1.2.1 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/robfig/cron v1.2.0 // indirect
	github.com/stretchr/objx v0.4.0 // indirect
	go.temporal.io/api v1.11.0 // indirect
	go.uber.org/atomic v1.9.0 // indirect
	golang.org/x/net v0.0.0-20220728181054-f92ba40d432d // indirect
	golang.org/x/sys v0.0.0-20220728004956-3c1f35247d10 // indirect
	golang.org/x/text v0.3.7 // indirect
	golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac // indirect
	google.golang.org/genproto v0.0.0-20220725144611-272f38e5d71b // indirect
	google.golang.org/grpc v1.48.0 // indirect
	google.golang.org/protobuf v1.28.1 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)

```

**Comment by cretz** [comment]
I am not sure this is related to naming. It seems you have an activity that returns just a single `error` and a mock that is returning an actual output and a nil error. Hence the message "incorrect number of returns, expected 1, but actual is 2".

**Comment by krousey** [comment]
I do not have an activity that returns a single `error`. I have an activity that returns `(string, error)`. I have a workflow with the same function name that returns just an `error`.  The most important indication that this is a naming issue is what I said in the original report:

## **If I change the name of the activity method in all places, the tests start passing.**

I think there's a general limitation in Temporal that you can't name the activity the same as the workflow.  But Temporal allows you to register workflows with well-known names not derived from the function names like:

```go
w.RegisterWorkflowWithOptions(wf.GenericName, workflow.RegisterOptions{Name: "different-wf-name"})
```

However, in the workflow testsuite, I don't register the workflow. I also don't register activities. I didn't expect this to be an issue since it doesn't appear that I'm registering either activities or workflows.

I think I've traced it down to the workflow testsuite registering workflows and activities under the hood, but not allowing registration options to prevent name collisions.

The activity is registered under the hood during `env.OnActivity` here: https://github.com/temporalio/sdk-go/blob/master/internal/workflow_testsuite.go#L334

The workflow is registered under the hood during `env.ExecuteWorkflow` here: https://github.com/temporalio/sdk-go/blob/master/internal/internal_workflow_testsuite.go#L451


So the crux of this bug is "Perfectly valid workflow code can't be tested using the `TestWorkflowEnvironment`"

**Comment by cretz** [comment]
@krousey - I have replicated this and have confirmed the workflow environment uses a shared mock for its workflow and activities call 😞. Specifically the `OnActivity` registers the mock and the `ExecuteWorkflow` checks for mocks before running the actual method. That's where the error is happening.

I am unsure I can break these out into separate mocks at this time without breaking backwards compatibility and upsetting how things like https://pkg.go.dev/go.temporal.io/sdk/internal#TestWorkflowEnvironment.AssertNotCalled are meant to work for workflow or activity invocations.

I am thinking about just documenting this limitation. Is this acceptable for now or do you think it's worth the effort to separate the mocks?

**Comment by krousey** [comment]
I'm not sure what the appropriate level of effort is here. It's an easy fix on my end, just frustrating to figure out the actual issue.

Other than splitting the mocks, allowing aliasing could work. If fixes aren't possible, documentation is fine. Detecting the situation and emitting an appropriate error message is even better.

**Comment by cretz** [comment]
Unfortunately you can have multiple mocks of the same name I believe with different behaviors based on param matching. I will research some solutions, worst case being just documenting this limitation.

**Comment by ignatk** [comment]
I see. I must admit I'm new to temporal and not familiar with the code base, but it seems a bit weird that a change in the testing framework may break user facing API? Can, for example `TestWorkflowEnvironment` have different behaviour than "real" workflow environment?

**Comment by krousey** [comment]
did https://github.com/temporalio/sdk-go/pull/1371 fix this?
