### ISSUE TITLE
Define an external type for internal.WorflowClient

### ISSUE THREAD

**Issue by LXiao2015** [temporalio/sdk-go#918]
**Is your feature request related to a problem? Please describe.**
I'm writing unit test for my code and need a way to mock ExecuteWorkflow method. But I'm blocked because I'm not able to use *internal.WorkflowClient type inside internal package.

**Describe the solution you'd like**
Like what we already have, internal.WorkflowRun can be accessed with client.WorkflowRun. Can we also define this for internal.WorkflowClient?

**Describe alternatives you've considered**

**Additional context**

**Comment by cretz** [comment]
You should mock the `client.Client` interface with your favorite mocking approach. You shouldn't need access to any particular implementation of `client.Client`. For example (untested, just typed here in chat):

```go
type MyClient struct {
  client.Client
  onExecute func(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) (client.WorkflowRun, error)
}

func (m *MyClient) ExecuteWorkflow(ctx context.Context, options StartWorkflowOptions, workflow interface{}, args ...interface{}) (WorkflowRun, error) {
  return m.onExecute(ctx, options, workflow, args...)
}
```

**Comment by Quinn-With-Two-Ns** [comment]
Closing, feel free to reopen if you have other questions
