### ISSUE TITLE
Multi-history replay support

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-go#938]
Like what's already been done in TS/Python

**Comment by bergundy** [comment]
@Sushisource what's the status of this?

**Comment by Sushisource** [comment]
@cretz and I agree it's easy (and performant) enough to call `ReplayWorkflowHistory` in a loop, so we probably don't need this. Maybe a separate item for list API.

**Comment by bergundy** [comment]
Yeah, let's make sure we have the list API for Go following the same rough API we have in other SDKs (list, into histories + concurrency)

**Comment by bergundy** [comment]
Opened a separate issue #972

**Comment by cretz** [comment]
I think we won't need concurrency and we won't need an explicit into histories there. Go people are used to looping, they are not used to functional APIs.
