### ISSUE TITLE
remove error from return since it always return nil

### ISSUE THREAD

**Issue by ktong** [temporalio/sdk-go#954]
https://github.com/temporalio/sdk-go/blob/34f71ac9d724670c6542faf1fac3e5594479a98a/contrib/opentelemetry/tracing_interceptor.go#L89

**Comment by cretz** [comment]
This is for future proofing. We may return an error from it one day, so we need it to be present now so we don't break people later. Please always check for an error from this call.

**Comment by cretz** [comment]
Closing. Feel free to keep commenting or request re-open.
