### ISSUE TITLE
ScheduleOptions.ID says optional, but runtime requires it

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#957]
ScheduleOptions.ID says optional and will default with UUID, but runtime errors with "no schedule ID in options". Need to decide whether docs are wrong or runtime is wrong.

Also, please document that this may not be the actual workflow ID, it may have the timestamp appended.

**Comment by Quinn-With-Two-Ns** [comment]
>Also, please document that this may not be the actual workflow ID, it may have the timestamp appended.

The schedule ID is not related to the workflow ID?

**Comment by cretz** [comment]
> Typescript requires the ID, I think Go should be the same

Works for me, but it means https://github.com/temporalio/sdk-go/blob/v1.18.1/internal/schedule_client.go#L270 is wrong and needs to be updated.

> The schedule ID is not related to the workflow ID?

The schedule ID is related but not the same. I ran into this writing tests just now. From https://github.com/temporalio/api/blob/v1.12.0/temporal/api/schedule/v1/message.proto#L252-L253:

> The workflow id of the started workflow may not match this exactly, it may have a timestamp appended for uniqueness.

When I was trying to look up a scheduled workflow by the ID I put in the scheduled workflow action, it failed because there was a timestamp appended.

**Comment by Quinn-With-Two-Ns** [comment]
yeah I can update the comment. 

>The schedule ID is related but not the same. I ran into this writing tests just now. From https://github.com/temporalio/api/blob/v1.12.0/temporal/api/schedule/v1/message.proto#L252-L253:

that's the ID of the schedule workflow action, not the schedule, but I agree we should clarify it won't be used verbatim.

**Comment by cretz** [comment]
From the API there is no such thing as a schedule workflow action ID, only a `start_workflow` options for a workflow action. But the comment makes clear that ID may have something appended. We can make the same comment - meaning don't say "it won't be used verbatim", but rather "it may have timestamp appended". My tests at https://github.com/temporalio/sdk-features/pull/158 for instance rely on the prefix to disambiguate across runs.

**Comment by Quinn-With-Two-Ns** [comment]
yeah I agree we should have the same comment 👍

**Comment by Quinn-With-Two-Ns** [comment]
closed in https://github.com/temporalio/sdk-go/pull/959
