### ISSUE TITLE
Loggers use different stack depths when being called from workflow vs activity

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-go#960]
## Expected Behavior

The same log statements in workflow and activity should be at the same stack depth so that a shared caller-skip (e.g. in Zap or Zerolog) can work for both.

## Actual Behavior

We wrap the workflow logger in a replay safe version which properly skips logs during replay. The problem is this adds an extra stack frame for just workflows. We should either: 1) wrap activities in a similar fashion, or 2) stop using a wrapped replayer, or 3) have a `interface WithSkipCallers { AddCallerSkip(int) }` interface that loggers can implement.

Only 3 is backwards compatible. 1 or 2 could break existing user expectations.

## Replication

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/google/uuid"
	"github.com/rs/zerolog"
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/client"
	sdklog "go.temporal.io/sdk/log"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	log.Printf("Creating client")
	logWriter := zerolog.ConsoleWriter{Out: os.Stdout, TimeFormat: zerolog.TimeFormatUnix}
	// We add 3 more to the skip count because we are in our log
	// TODO(cretz): We need 3 for workflows but only 2 for activities because
	// workflows add an extra wrapping which increases the stack depth
	skipLogFrameCount := zerolog.CallerSkipFrameCount + 3
	c, err := client.Dial(client.Options{
		Logger: &ZeroLogLogger{
			zerolog.New(logWriter).With().CallerWithSkipFrameCount(skipLogFrameCount).Timestamp().Logger(),
		},
	})
	if err != nil {
		return fmt.Errorf("failed creating client: %w", err)
	}
	defer c.Close()

	log.Printf("Starting worker")
	taskQueue := uuid.NewString()
	w := worker.New(c, taskQueue, worker.Options{})
	w.RegisterWorkflow(MyWorkflow)
	w.RegisterActivity(MyActivity)
	if err := w.Start(); err != nil {
		return fmt.Errorf("failed starting worker client: %w", err)
	}
	defer w.Stop()

	log.Printf("Starting workflow")
	run, err := c.ExecuteWorkflow(ctx, client.StartWorkflowOptions{TaskQueue: taskQueue}, MyWorkflow)
	if err != nil {
		return fmt.Errorf("failed starting workflow: %w", err)
	}

	// Wait for complete
	return run.Get(ctx, nil)
}

func MyWorkflow(ctx workflow.Context) error {
	workflow.GetLogger(ctx).Info("Workflow started")
	return workflow.ExecuteActivity(
		workflow.WithActivityOptions(ctx, workflow.ActivityOptions{ScheduleToCloseTimeout: 1 * time.Minute}),
		MyActivity,
	).Get(ctx, nil)
}

func MyActivity(ctx context.Context) error {
	activity.GetLogger(ctx).Info("Activity started")
	return nil
}

type ZeroLogLogger struct{ underlying zerolog.Logger }

var _ sdklog.WithLogger = &ZeroLogLogger{}

func (z *ZeroLogLogger) Debug(msg string, keyvals ...interface{}) {
	logEvent(z.underlying.Debug(), msg, keyvals...)
}

func (z *ZeroLogLogger) Info(msg string, keyvals ...interface{}) {
	logEvent(z.underlying.Info(), msg, keyvals...)
}

func (z *ZeroLogLogger) Warn(msg string, keyvals ...interface{}) {
	logEvent(z.underlying.Warn(), msg, keyvals...)
}

func (z *ZeroLogLogger) Error(msg string, keyvals ...interface{}) {
	logEvent(z.underlying.Error(), msg, keyvals...)
}

func (z *ZeroLogLogger) With(keyvals ...interface{}) sdklog.Logger {
	return &ZeroLogLogger{z.underlying.With().Fields(keyvals).Logger()}
}

func logEvent(e *zerolog.Event, msg string, keyvals ...interface{}) {
	if len(keyvals) > 0 {
		e = e.Fields(keyvals)
	}
	// We have previously set caller skip frames to work with this
	e.Caller().Msg(msg)
}
```

**Comment by Multiply** [comment]
We've been trying to work around this with zap since we started out with Temporal as well.

What is the easiest path forward, if we'd like to contribute a workaround or fix?

**Comment by cretz** [comment]
@Quinn-With-Two-Ns - thoughts on a `WithSkipCallers` interface in https://pkg.go.dev/go.temporal.io/sdk/log?

**Comment by Quinn-With-Two-Ns** [comment]
@cretz so the idea is `WithSkipCallers` returns a new logger that skips more frames and we would check for this interface when creating the logger in certain places ?

**Comment by cretz** [comment]
@Quinn-With-Two-Ns - Yes. I can think of only two places: workflow and activity execution start. I think a test can confirm https://pkg.go.dev/runtime#Caller, w/ the set number of skips inside the a log statement in activity and workflow, returns the expected frame/file/whatever.

Can call it `WithCallerSkip` instead, that may be clearer to read.

**Comment by Quinn-With-Two-Ns** [comment]
Why can't users intercept `GetLogger` calls in workflows and activities to set different  amounts in workflows vs activities?

**Comment by cretz** [comment]
My concern is that we don't use `GetLogger` for our _own_ logging internally or that the interceptor isn't ready for all uses. But if you can 1) confirm or make sure we do (at least for the logger stored on these contexts that are used internally once the interceptor is ready), and 2) update the sample showing how to do it, I think that would be good enough. I think workflow not found, task failure, and panic would be good example logs to confirm.

**Comment by Quinn-With-Two-Ns** [comment]
hm testing `GetLogger` since the workflow logger is wrapped it is not possible to set the skip level.

I don't like ``WithSkipCallers` just because it seems arbitrary where the SDK is skipping. I would prefer wrapping activities so the skip depth is the same, but I wouldn't die on that hill.

**Comment by Multiply** [comment]
Maybe split the logger into one for internals, one for workflows and one for activities? If none is defined, fall back to the current logger, so there's no backwards breaking changes.

**Comment by cretz** [comment]
> I would prefer wrapping activities so the skip depth is the same, but I wouldn't die on that hill.

Just realized people already are setting skip-caller for their activity logger with certain expectations, so this wouldn't work.

> Maybe split the logger into one for internals, one for workflows and one for activities? If none is defined, fall back to the current logger, so there's no backwards breaking changes.

I don't think it's worth multiple entirely new options for this skip-caller use case.

I can only think of `type WithCallerSkip interface { Logger WithCallerSkip(int) }` at the moment.

**Comment by debuggerpk** [comment]
> I don't think it's worth multiple entirely new options for this skip-caller use case.

The typescript sdk has multiple entry points for logging.

**Comment by cretz** [comment]
> The typescript sdk has multiple entry points for logging.

Not following exactly what is meant by "entry points". TypeScript has ways to access loggers from activities and workflows same as Go, but has a global runtime set logger as opposed to per client in Go (TS also has to use sinks and other confusing concepts due to its sandbox and how it forwards Rust logs, both of which are not related to Go SDK).

You can of course use custom logging in your activities and workflows (though you should skip logging from a workflow when replaying).
