### ISSUE TITLE
"workflowcheck" fails to detect argument type

### ISSUE THREAD

**Issue by mindaugasrukas** [temporalio/sdk-go#962]
`workflowcheck` fails to detect the argument type when referenced as an empty interface type (I.e., `any`).

## Expected Behavior
It detects the type correctly.

## Actual Behavior
Having this code snippet:
```
for name, workflowFunc := range map[string]any{
    "my-workflow"-1: Workflow1,
    "my-workflow-2": Workflow2,
} {
    w.RegisterWorkflowWithOptions(workflowFunc, workflow.RegisterOptions{Name: name})
}
```

Running a check, it fails with:
```
% workflowcheck -show-pos ./...
/workflows/sandbox/workflow.go:18:33: unrecognized function reference format
```

## Specifications

  - Version:
```
% go version
go version go1.19.2 darwin/arm64
```

**Comment by cretz** [comment]
The Go static analyzer is not going to be able to know the runtime types of your map values. It's the same reason the map's value is `any`. That's the type that is only detectable at runtime.

However, we should probably make a way for you to ignore this error.

**Comment by Quinn-With-Two-Ns** [comment]
@cretz This is basically a feature request not a bug correct?

**Comment by cretz** [comment]
Yes. We should let people ignore the workflowcheck registration-time analysis if the registration code is too dynamic for static analysis to discover.
