### ISSUE TITLE
Export asyncFuture interface 

### ISSUE THREAD

**Issue by nitesh237** [temporalio/sdk-go#964]
**Is your feature request related to a problem? Please describe.**
We have a use-case to add some validation on the request and response getting passed in the activity. The validations can be like the response must be a proto message. The response must have a specific header field, etc.

The preferred way to solve this is using a future wrapper that has validation added before invoking the original methods. Basically, using the composition as shown below:

```
type wfProtoFuture struct {
	workflowFuture workflow.Future
}

var _ workflow.Future = &wfProtoFuture{}

func WrapProtoFuture(future workflow.Future) workflow.Future {
	return &wfProtoFuture{workflowFuture: future}
}

func (p *wfProtoFuture) Get(ctx workflow.Context, valuePtr interface{}) error {
	if res, ok := valuePtr.(proto.Message); !ok {
		return fmt.Errorf("value ptr passed must be a proto.Message")
	} else if !isValidActivityResponse(res) {
		return fmt.Errorf("missing response headers in activity response")
	}

	return p.workflowFuture.Get(ctx, valuePtr)
}

func (p *wfProtoFuture) IsReady() bool {
	return p.workflowFuture.IsReady()
}
```
This way we would be able to fail fast in the workflow code itself while blocking the workflow on the future objects. However, the SDK right now doesn't expose `asyncFuture` interface. This restricts wrapper usage. When we pass the wrapped future to a selector we get an error because of this line [here](https://github.com/temporalio/sdk-go/blob/master/internal/internal_workflow.go#L1192).

```
asyncF, ok := future.(asyncFuture)
if !ok {
panic("cannot chain Future that wasn't created with workflow.NewFuture")
}
```

**Describe the solution you'd like**
* Make `asyncFuture` interface exported.

**Describe alternatives you've considered**
The other alternative is to add the validation workflow and activity interceptor.

**Comment by cretz** [comment]
Futures passed back into helpers like selector are meant to be the unwrapped future that was created by Temporal. This is because some internal aspects of the future are relied on. If you must wrap the future, you should unwrap it when calling select instead of trying to reuse the Temporal future interface. Since you're already wrapping, there's no reason to reuse the Temporal interface, use your own type (you can be even stricter on your `Get` type, use generics, etc).

**Comment by cretz** [comment]
Closing, but if there is more to add here, feel free to comment.

**Comment by nitesh-epifi** [comment]
> Futures passed back into helpers like selector are meant to be the unwrapped future that was created by Temporal. This is because some internal aspects of the future are relied on. If you must wrap the future, you should unwrap it when calling select instead of trying to reuse the Temporal future interface. Since you're already wrapping, there's no reason to reuse the Temporal interface, use your own type (you can be even stricter on your `Get` type, use generics, etc).
> 
> Why not have just your `wfProtoFuture` just have the future in it and unwrap at selector time? There's no reason to match the Temporal interface. Can make your own helper, e.g.
> 
> ```go
> func (p *wfProtoFuture) AddToSelector(sel workflow.Selector, fn func(*wfProtoFuture)) workflow.Selector {
>   return sel.AddFuture(p.future, func(workflow.Future) { fn(p) })
> }
> ```

@cretz sorry for the delayed response. Thanks for your suggestion. We went ahead with your suggestion here.
