### ISSUE TITLE
Programatic list API with intoHistories iterator

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-go#972]

**Comment by bergundy** [comment]
See https://github.com/temporalio/sdk-java/issues/1552 for reference

**Comment by cretz** [comment]
To follow Java, you need to:

* Add `client.WorkflowExecution` that wraps a raw execution info proto
* Add a `client.WorkflowExecutionDescription` that embeds the workflow execution and wraps raw description response
* Deprecate `Client.DescribeWorkflowExecution`
* Add `Client.DescribeWorkflow`
* Deprecate `Client.List*Workflow`
* Add `Client.ListWorkflows`
  * Accepts a `ListWorkflowsOptions` which right now only contains a `Query string`
  * Returns a `WorkflowExecutionIterator`
* Add a `client.WorkflowHistory` that wraps raw workflow history
  * Have marshal/unmarshal JSON that is just protojson
  * Consider a JSON marshal form/option that puts our enums back as they should be
* Add `WorkflowExecutionIterator`
  * Easiest way to turn this into histories for replaying? Let them just do it themselves?
* Add `HistoryEventIterator` method to just return a `client.WorkflowHistory`
  * Or add a workflow history constructor that accepts it
* Support `client.WorkflowHistory` in the `worker.WorkflowReplayer`

All of these client changes make me nervous. Do we need to stop and think about this? There are a lot of things wrong with the client interface, and just bolting more things on it may not be the solution. Maybe we only want the list part and not the describe part?

**Comment by bergundy** [comment]
Closing this.
We'll need to have discussion of the future of the Go client API and whether we want to deprecate the APIs @cretz listed above.
