### ISSUE TITLE
Replay results inconsistent between Go versions

### ISSUE THREAD

**Issue by mattpercy-anz** [temporalio/sdk-go#978]
## Expected Behavior
Running a workflow replay should succeed if there have been no workflow/activity code changes, but are run on different Go versions

## Actual Behavior
Replays can fail once the Go version changes

## Steps to Reproduce the Problem

This occurs due to the protojson serialisation of the workflow results in the payload struct:
  https://github.com/temporalio/sdk-go/blob/master/internal/internal_worker.go#L1290
The proto equal in the replayer is comparing the byte array of the marshalled workflow result. But due to a "feature" in the protojson encoder, a random space is sometimes prepended before fields when marshalling (see [here](https://github.com/protocolbuffers/protobuf-go/commit/582ab3de426ef0758666e018b422dd20390f7f26), [here](https://github.com/protocolbuffers/protobuf-go/blob/master/internal/encoding/json/encode.go#L239) and [here](https://github.com/protocolbuffers/protobuf-go/blob/master/internal/encoding/json/encode.go#L272)). This is dependant on your Go version (see [here](https://github.com/protocolbuffers/protobuf-go/blob/master/internal/detrand/rand.go#L40)), and only occurs when the protojson output is multiline.

A workaround would be to create a custom data converter in order to ensure we had payloads encoded in a way that was consistent regardless of Go version. However, I raise this issue because this is an obscure problem that isn't made clear to the users of temporal, and we had hoped to use the replay function to help regression test our workflows and ensure backwards compatibility.

My request is that the replay code allow us to perform the final workflow result equality ourselves, that way we could pull the results out and compare the decoded data, rather than proto comparing the two payloads and potentially flagging a "failed" replay, though the results are actually the same.

For testing this, I made a small change to the helloworld sample code (I can provide my changes if need be) to return a proto struct instead of a string, and recorded the results, one replay file from a workflow ran on Go 1.18.9:
```
"result": {
          "payloads": [
            {
              "metadata": {
                "encoding": "anNvbi9wcm90b2J1Zg==",
                "messageType": "VGVzdEhvbGRlcg=="
              },
              "data": "eyJ0ZXN0cyI6W3sidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0sIHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn1dfQ=="
            }
          ]
        },
```
And the other on Go 1.19.4:
```
"result": {
          "payloads": [
            {
              "metadata": {
                "encoding": "anNvbi9wcm90b2J1Zg==",
                "messageType": "VGVzdEhvbGRlcg=="
              },
              "data": "eyJ0ZXN0cyI6W3sidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0seyJ0ZXN0SWQiOiJIZWxsbyBUZW1wb3JhbCEifSx7InRlc3RJZCI6IkhlbGxvIFRlbXBvcmFsISJ9LHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0seyJ0ZXN0SWQiOiJIZWxsbyBUZW1wb3JhbCEifSx7InRlc3RJZCI6IkhlbGxvIFRlbXBvcmFsISJ9LHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn0seyJ0ZXN0SWQiOiJIZWxsbyBUZW1wb3JhbCEifSx7InRlc3RJZCI6IkhlbGxvIFRlbXBvcmFsISJ9LHsidGVzdElkIjoiSGVsbG8gVGVtcG9yYWwhIn1dfQ=="
            }
          ]
        },
```
If you base64 decode the data, you'll see that the only difference is whitespace.

Very happy to provide any extra information for this. Thanks!

## Specifications

  - Version: go.temporal.io/sdk v1.18.1, https://hub.docker.com/r/temporalio/auto-setup 1.17.4
  - Platform: Mac OS 12.6.1

**Comment by Quinn-With-Two-Ns** [comment]
@cretz I think we should also remove [this](https://github.com/temporalio/sdk-go/blob/66eb848f196bef644809a86903732762524be6e6/internal/internal_event_handlers.go#L802) use of `proto.equal` used while processing events. It shouldn't cause any non determinism as it is used today but someone could easily misuse it in the future.

**Comment by cretz** [comment]
Note, that's only for checking against encoded `nil` which by default is encoded as `"null"`, so it's probably safe.

Concur in general, we should never compare `json/*` payloads by bytes again. We should have a helper that does a JSON equality for JSON encoding and byte comparison otherwise.

Note, technically proto binary marshalling is non-deterministic too I believe. But you have to opt-in to using proto binary conversion in our SDKs. But you can't do a structural comparison without the actual types to deserialize to like you can in JSON. So we may just need to add this as a note/caveat.

And really, we need to stop using payload comparison anyways. I don't believe we need to check input/output _data_ (replayer or during replay). And for mutable side effect, it's just for `nil` that we're using proto equality, otherwise we do use their equals checker.

**Comment by Quinn-With-Two-Ns** [comment]
>And really, we need to stop using payload comparison anyways. I don't believe we need to check input/output data (replayer or during replay). 

Agreed. Other than the one posted and tests we do a lot in [isCommandMatchEvent](https://github.com/temporalio/sdk-go/blob/v1.19.0/internal/internal_task_handlers.go#L1276) they are mostly protected by `strictMode ` always being `false` (and looking back on the git history can't find when it was ever used). We should probably remove this option and any checks controlled by it OR expose it and only enable wen run from the replayer (we'd also need to fix how we compare payloads as well in this case)

**Comment by cretz** [comment]
Concur on removing the strict option. Not sure why it's there either.

**Comment by mattpercy-anz** [comment]
> I don't believe we need to check input/output data (replayer or during replay)

If you were to stop verifying input/output, will that also mean that the replayer won't flag a difference between a workflow returning a valid response vs one returning an error? If so, that will make using the replayer even less desirable.

We need to ensure workflow changes are deterministic, and work correctly when we use workflow versioning. Ideally we would have unit tests to cover version variations, but the test suite doesn't allow setting the workflow version.

Please correct me if i'm misunderstanding, or there's an alternate way to cover this type of workflow testing.

Thanks

**Comment by cretz** [comment]
> If you were to stop verifying input/output, will that also mean that the replayer won't flag a difference between a workflow returning a valid response vs one returning an error?

It's just not verifying the contents of the return. Fail and success are different commands and would mismatch properly.

**Comment by Quinn-With-Two-Ns** [comment]
Resolved as part of https://github.com/temporalio/sdk-go/pull/990
