### ISSUE TITLE
Replaying non deterministic workflows that use local activities can give false negatives

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/sdk-go#983]
## Expected Behavior

Removing/adding a local activity should fail with a nondeterminism error

## Actual Behavior

Workflow succeeds 

## Steps to Reproduce the Problem

If you save a history for the following workflow, add or remove calls to `helloworldActivity`, and replay the replay does not error
```
func LocalActivityWorkflow(ctx workflow.Context, name string) error {
	ao := workflow.LocalActivityOptions{
		ScheduleToCloseTimeout: time.Minute,
	}
	ctx = workflow.WithLocalActivityOptions(ctx, ao)
	var helloworldResult string
         workflow.ExecuteLocalActivity(ctx, helloworldActivity, name).Get(ctx, &helloworldResult)
         workflow.ExecuteLocalActivity(ctx, helloworldActivity, name).Get(ctx, &helloworldResult)
	return workflow.ExecuteLocalActivity(ctx, helloworldActivity, name).Get(ctx, &helloworldResult)
}
```

Note: assuming https://github.com/temporalio/sdk-go/issues/876 is already resolved

This seems to be due to https://github.com/temporalio/sdk-go/blob/38b2b69f18bdc3bcaf1b4e48f940d1c60b5f9253/internal/internal_task_handlers.go#L919 when the workflow returns we skip adding to the replay commands https://github.com/temporalio/sdk-go/blob/38b2b69f18bdc3bcaf1b4e48f940d1c60b5f9253/internal/internal_task_handlers.go#L928

This issue probably effects more commands than just local activities.

**Comment by Quinn-With-Two-Ns** [comment]
I tried just removing these breaks and it seems to cause false positives with other commands like `UpsertMemo`

**Comment by cretz** [comment]
Ug, was introduced at the same as the other workflow completed ignoring stuff. Does it seem like too much of a burden to change `w.isWorkflowCompleted && !w.isInReplayer {` on these and get the matcher working? We can discuss half-impl alternatives that at least solves matching completed workflows if not very well.

**Comment by Quinn-With-Two-Ns** [comment]
Looking at the error more closely the actual issue is the workflow execution commands are not in the replay history, but are in the real history causing a mismatch. hmm

```
--- FAIL: TestReplayTestSuite (0.00s)
    --- FAIL: TestReplayTestSuite/TestContinueAsNewWorkflow (0.00s)
        /Users/quinnklassen/Documents/Code/sdk-go/test/replaytests/replay_test.go:172: 
            	Error Trace:	/Users/quinnklassen/Documents/Code/sdk-go/test/replaytests/replay_test.go:172
            	Error:      	Received unexpected error:
            	            	nondeterministic workflow: missing replay command for WorkflowExecutionContinuedAsNew: (EventId:5, EventTime:(), EventType:WorkflowExecutionContinuedAsNew, Version:0, TaskId:7343443, WorkerMayIgnore:false, Attributes:&HistoryEvent_WorkflowExecutionContinuedAsNewEventAttributes{WorkflowExecutionContinuedAsNewEventAttributes:&WorkflowExecutionContinuedAsNewEventAttributes{NewExecutionRunId:74f38af0-7c7d-4aae-bc10-6c34ba946693,WorkflowType:&v1.WorkflowType{Name:ContinueAsNewWorkflow,},TaskQueue:&v11.TaskQueue{Name:replay-test,Kind:Normal,},Input:&v1.Payloads{Payloads:[]*Payload{&Payload{Metadata:map[string][]byte{encoding: [106 115 111 110 47 112 108 97 105 110],},Data:[102 97 108 115 101],},},},WorkflowRunTimeout:0s,WorkflowTaskTimeout:10s,WorkflowTaskCompletedEventId:4,BackoffStartInterval:<nil>,Initiator:Unspecified,Failure:nil,LastCompletionResult:nil,Header:&v1.Header{Fields:map[string]*Payload{},},Memo:nil,SearchAttributes:nil,},})
            	Test:       	TestReplayTestSuite/TestContinueAsNewWorkflow
```

**Comment by Quinn-With-Two-Ns** [comment]
possibly we could add all the the workflow execution commands to `skipDeterministicCheckForEvent` as the execution result mismatch would get caught by the replayer at a higher level, thoughts @cretz ?

**Comment by cretz** [comment]
Not following exactly as the original description was saying "the replay does not error" was the issue but this is showing an error.

Regardless, can you replicate this error in replay today? Even without the replayer (i.e. unfinished workflow on another worker or a zero-cache setup)? What _exactly_ is the problem here? (sorry for not understanding) I want to be _very_ cautious about doing anything but fixing something that may already be broken and even then be very cautious there.

The goal was to get replayer working with no effect to existing workflows, but if existing workflow replay checks are broken giving false mismatches, we should probably fix that. I'd be hesitant to add more mismatch check possibilities to non-replayer workflow checks today.

**Comment by Quinn-With-Two-Ns** [comment]
The error I posted is the error we get if we remove the breaks in other words making the change you suggested `w.isWorkflowCompleted && !w.isInReplayer {` .

>Regardless, can you replicate this error in replay today? Even without the replayer (i.e. unfinished workflow on another worker or a zero-cache setup)? 

No it requires making the above code changes.

>I want to be very cautious about doing anything but fixing something that may already be broken and even then be very cautious there.

completely agree, the original issue is as I described in this issue. That issue could be solved by removing the `break` statements on workflow complete. Removing those breaks causes the `WorkflowExecution...` events to end up in the his `respondEvents` but not the `replayEvents`

**Comment by cretz** [comment]
Now I definitely admin ignorance wrt respond vs replay, etc. I'm on board w/ any solution that lets most non-determinisms get caught by the replayer for a complete workflow _and_, most importantly, has no impact on non-replayer code today from a user POV. If that means fixing this or ignoring it, your call.
