### ISSUE TITLE
No error will be thrown if WorkflowRunTimeout is reached

### ISSUE THREAD

**Issue by chunming-c** [temporalio/sdk-go#984]
## Expected Behavior

Hi forks, thank you for the great work. I faced a difficulty which might not be a bug but I couldn't find relative solution anywhere. In our case I would like to know how should we detect workflow has timeout or how should we catch the timeout error when `WorkflowRunTimeout` is reached. For example, the following set the `WorkflowRunTimeout` to 1 second which should enter workflow `defer` function once timeout is reached. 

**main.go**
```go
func main() {
	...
	workflowOptions := client.StartWorkflowOptions{
		ID:        workflowID,
		TaskQueue: "",
                 // Set workflow timeout to one second.
		WorkflowRunTimeout: 1 * time.Second,
	}

	we, err := c.ExecuteWorkflow(context.Background(), workflowOptions, YourWorkflow)
}
```

**workflow.go**
```go
func YourWorkflow(ctx workflow.Context) error {
	defer func() {
                 // Ideally the defer function should be called once one second passed. The fact is the temporal will terminate 
                 // the workflow without entering the the defer function.
		if !errors.Is(ctx.Err(), workflow.ErrCanceled) {
			return
		}
	}()

        time.Sleep(5 * time.Second)

	return nil
}

```

## Actual Behavior

The fact is the temporal will terminate the workflow without entering the the `defer` function.

## Specifications

  - Version: `v1.18.4`
  - Platform: OSX

**Comment by Quinn-With-Two-Ns** [comment]
Hi @chunming-c , I believe this is the intended behaviour. Per our documentation on [WorkflowRunTimeout](https://docs.temporal.io/concepts/what-is-a-workflow-run-timeout) it will terminate the workflow execution so no other workflow tasks should be run. 

We don't recommend putting any business logic on workflow timeouts. Why exactly are you setting `WorkflowRunTimeout `

**Comment by chunming-c** [comment]
`WorkflowRunTimeout` is the minimum hard deadline because we don't want workflow would run forever

Our workflow is long-running process which contains couples of activities might last one or two hours. It's a big deal for us if one of them is delayed and make the entire workflow not able to finish on time, especially the last few activities. Therefore, once the workflow exceed the timeout, an alert will be sent. It would be ideal if we could get a either event or error when the workflow timeouts

**Comment by Quinn-With-Two-Ns** [comment]
As I said we don't recommend using workflow timeout for any business logic. If you did really want to go with that approach then you could have a parent workflow that's job is to supervise the child workflow and wait for the child workflow to complete/fail and react accordingly. Another approach would be to create a timer at the start of your workflow and if that timer expires cancel the workflow and do any cleanup

 [Child workflow example](https://github.com/temporalio/samples-go/tree/main/child-workflow)
 
 [timer example](https://github.com/temporalio/samples-go/blob/main/timer/workflow.go)

**Comment by chunming-c** [comment]
okay, thank you for your advices. Will figure out an alternative to fit our own logic. Thanks!
