### ISSUE TITLE
Cannot set workflow ID for replayer

### ISSUE THREAD

**Issue by Drahflow** [temporalio/sdk-go#994]
We have a workflow which derives various child workflow execution IDs by appending subtask names (`"-start-session"` in the example below) to the current workflow execution ID. Upon replaying those histories during CI to check for non-determinism problems, we see (re-wrapped for your convenience):
```
2023/01/04 13:33:12 ERROR Workflow panic
    WorkflowType Main
    WorkflowID ReplayId
    RunID 2bc48c60-ee48-4b19-99fb-0656c4d30a99
    Attempt 1 Error unknown command
    CommandType: ChildWorkflow, ID: merchant-consumer-workflow/ed472a6d-b793-501c-af06-a501158487b6-start-session,
    possible causes are nondeterministic workflow definition code or incompatible change in the workflow definition
    StackTrace process event for Merchant [panic]:
go.temporal.io/sdk/internal.panicIllegalState(...)
        /home/drahflow/go/pkg/mod/go.temporal.io/sdk@v1.19.0/internal/internal_command_state_machine.go:532
...
```
as the re-derived child workflow IDs will now (i.e. during replay) be based upon the `ReplayId` string used as the workflow execution ID here:
https://github.com/temporalio/sdk-go/blob/06e474c93e936b71dc4afcec973460b22c13986d/internal/internal_worker.go#L1235

In reality however, there is nothing non-deterministic about such a derivation, as the workflow execution ID is fixed for a given execution.

A possible solution would be to allow providing a custom execution ID (in practice derived from the recorded history filename) when replaying a history.

----

A workaround is relatively straightforward via recording the own execution ID in a side-effect, but that seems extremely unnecessary.

**Comment by cretz** [comment]
Yeah workflow ID, unlike run ID, cannot currently be derived from history. Unlike our other SDKs, the Go SDK does not offer a way to set the workflow ID on the replayer. I have altered the title of this issue.
